import type { ModuleSeed } from '../types';

export const module2: ModuleSeed = {
  slug: 'barber-module-2',
  title: 'Module 2: Hair Science & Scalp Analysis',
  moduleOrder: 2,
  objective: 'Apply hair science and scalp analysis to guide service decisions and client consultations.',
  lessons: [
    {
      slug: 'barber-lesson-8',
      title: 'Structure of the Hair and Scalp',
      lessonOrder: 1,
      durationMin: 20,
      objective: 'Identify the layers of the hair shaft and scalp anatomy.',
      style: 'theory',
      vocabulary: [
        { term: 'Cuticle', definition: 'Outermost layer of the hair shaft — overlapping scales that protect the cortex.' },
        { term: 'Cortex', definition: 'Middle layer containing melanin (color) and keratin (strength).' },
        { term: 'Medulla', definition: 'Innermost layer — not always present in fine hair.' },
        { term: 'Follicle', definition: 'The pocket in the scalp from which hair grows.' },
      ],
      stateBoardFocus: ['hair shaft layers', 'scalp anatomy', 'follicle structure'],
      sections: [
        { type: 'table', heading: 'Hair Shaft Layers', rows: [{ label: 'Cuticle', value: 'Outer protective layer. Overlapping scales. Determines shine and porosity.' }, { label: 'Cortex', value: 'Middle layer. Contains melanin (color) and keratin (strength).' }, { label: 'Medulla', value: 'Inner core. Not always present. More common in coarse hair.' }] },
        { type: 'text', heading: 'Scalp Anatomy', body: ['The scalp has five layers: skin, connective tissue, aponeurosis, loose connective tissue, and periosteum.', 'Hair follicles are embedded in the dermis. Each follicle produces one hair strand.', 'Sebaceous glands attached to follicles produce sebum, which lubricates the hair and scalp.'] },
        { type: 'callout', heading: 'Why This Matters', tone: 'info', body: ['Understanding hair structure helps you select the right tools, products, and techniques for each client\'s hair type.'] },
      ],
      competencyChecks: ['Names the three layers of the hair shaft and their functions', 'Identifies the follicle and its role in hair growth', 'Explains how cuticle condition affects service outcomes'],
    },
    {
      slug: 'barber-lesson-9',
      title: 'Hair Growth Cycle',
      lessonOrder: 2,
      durationMin: 15,
      objective: 'Explain the three phases of the hair growth cycle.',
      style: 'theory',
      vocabulary: [
        { term: 'Anagen', definition: 'Active growth phase — lasts 2–7 years.' },
        { term: 'Catagen', definition: 'Transition phase — hair detaches from follicle. Lasts 2–3 weeks.' },
        { term: 'Telogen', definition: 'Resting phase — hair sheds. Lasts 3–4 months.' },
      ],
      stateBoardFocus: ['hair growth cycle phases', 'anagen catagen telogen'],
      sections: [
        { type: 'table', heading: 'Hair Growth Phases', rows: [{ label: 'Anagen', value: 'Active growth. 85–90% of hair at any time. Lasts 2–7 years.' }, { label: 'Catagen', value: 'Transition. Hair detaches from follicle. 2–3 weeks.' }, { label: 'Telogen', value: 'Resting/shedding. 3–4 months. Normal to shed 50–100 hairs/day.' }] },
        { type: 'callout', heading: 'Client Education', tone: 'tip', body: ['Clients often worry about shedding. Explain that telogen shedding is normal. Excessive shedding may indicate stress, nutrition, or medical issues — refer to a physician.'] },
      ],
      competencyChecks: ['Names and describes all three phases of the hair growth cycle', 'Explains what percentage of hair is in anagen at any time', 'Identifies when to refer a client for excessive shedding'],
    },
    {
      slug: 'barber-lesson-10',
      title: 'Hair Texture, Density & Porosity',
      lessonOrder: 3,
      durationMin: 20,
      objective: 'Assess hair texture, density, and porosity to select appropriate techniques.',
      style: 'practical',
      vocabulary: [
        { term: 'Texture', definition: 'Diameter of the individual hair strand — fine, medium, or coarse.' },
        { term: 'Density', definition: 'Number of hairs per square inch on the scalp.' },
        { term: 'Porosity', definition: 'Hair\'s ability to absorb and retain moisture.' },
      ],
      stateBoardFocus: ['hair texture assessment', 'porosity', 'density'],
      sections: [
        { type: 'table', heading: 'Hair Properties', rows: [{ label: 'Fine texture', value: 'Small diameter. Less volume. Prone to limpness. Use lighter products.' }, { label: 'Coarse texture', value: 'Large diameter. Strong. May resist cutting. Use more tension.' }, { label: 'Low porosity', value: 'Cuticle tightly closed. Resists moisture. Needs heat to open cuticle.' }, { label: 'High porosity', value: 'Cuticle open or damaged. Absorbs quickly but loses moisture fast.' }] },
        { type: 'text', heading: 'Decision Logic', body: ['IF hair is fine: use lighter pressure, avoid over-thinning, choose softer lines.', 'IF hair is coarse: use firmer tension, expect more resistance, check blend frequently.', 'IF hair is high porosity: product absorbs fast — apply evenly and work quickly.', 'IF hair is low porosity: product may sit on top — use heat or steam to open cuticle.'] },
      ],
      competencyChecks: ['Assesses hair texture by feel and visual inspection', 'Identifies high vs low porosity', 'Adjusts technique based on texture and density findings'],
    },
    {
      slug: 'barber-lesson-11',
      title: 'Scalp Conditions & Disorders',
      lessonOrder: 4,
      durationMin: 20,
      objective: 'Identify common scalp conditions and determine when to refer clients.',
      style: 'theory',
      stateBoardFocus: ['scalp disorders', 'contraindications', 'referral protocol'],
      sections: [
        { type: 'table', heading: 'Common Scalp Conditions', rows: [{ label: 'Dandruff (Pityriasis)', value: 'Dry flaking. Service allowed. Use appropriate shampoo.' }, { label: 'Seborrheic Dermatitis', value: 'Oily flaking, redness. Service with caution. Refer if severe.' }, { label: 'Tinea Capitis (Ringworm)', value: 'Fungal infection. DO NOT SERVICE. Refer immediately.' }, { label: 'Psoriasis', value: 'Thick silvery scales. Service allowed unless open lesions present.' }, { label: 'Alopecia', value: 'Hair loss. Service allowed. Refer to physician for diagnosis.' }] },
        { type: 'callout', heading: 'Stop Condition', tone: 'warning', body: ['If you observe open lesions, active infection, or contagious scalp conditions — stop the consultation and refer the client to a physician. Do not perform the service.'] },
      ],
      competencyChecks: ['Identifies at least 5 common scalp conditions', 'Correctly identifies which conditions require referral', 'Stops service when contraindicated scalp condition is observed'],
    },
    {
      slug: 'barber-lesson-12',
      title: 'Client Consultation',
      lessonOrder: 5,
      durationMin: 20,
      objective: 'Conduct a professional client consultation to assess needs and set expectations.',
      style: 'practical',
      stateBoardFocus: ['client consultation', 'service planning', 'contraindication screening'],
      sections: [
        { type: 'steps', heading: 'Consultation Sequence', steps: ['Greet the client and introduce yourself.', 'Ask about the desired service and any specific concerns.', 'Inspect the scalp and hair for contraindications before touching.', 'Confirm the service plan and set realistic expectations.', 'Ask about allergies, sensitivities, or recent chemical services.', 'Document findings if required by shop protocol.'] },
        { type: 'text', heading: 'What to Screen For', body: ['Open cuts, abrasions, or active skin conditions.', 'Recent chemical services that may affect today\'s service.', 'Sensitivity to products, razors, or heat.', 'Medical conditions that may affect the scalp or hair.'] },
        { type: 'callout', heading: 'Professional Standard', tone: 'tip', body: ['A good consultation takes 2–3 minutes. It protects the client, protects you, and sets the tone for the service.'] },
      ],
      competencyChecks: ['Completes consultation before touching the client', 'Screens for contraindications during consultation', 'Confirms service plan with client before beginning', 'Documents findings when required'],
    },
    {
      slug: 'barber-lesson-13',
      title: 'Shampoo & Scalp Massage',
      lessonOrder: 6,
      durationMin: 15,
      objective: 'Perform a professional shampoo service and scalp massage.',
      style: 'practical',
      tools: ['Shampoo', 'Conditioner', 'Towels', 'Cape', 'Neck strip'],
      sanitationNotes: ['Use clean towels for every client.', 'Disinfect shampoo bowl between clients.'],
      sections: [
        { type: 'steps', heading: 'Shampoo Procedure', steps: ['Drape client with neck strip and cape.', 'Wet hair thoroughly with warm water.', 'Apply shampoo and work into a lather using fingertip (not fingernail) pressure.', 'Rinse thoroughly — no product residue.', 'Apply conditioner if needed, process, and rinse.', 'Towel dry gently — do not rub aggressively.'] },
        { type: 'text', heading: 'Scalp Massage Technique', body: ['Use the pads of the fingers, not the nails.', 'Apply firm but gentle rotary movements across the scalp.', 'Massage stimulates circulation and relaxes the client.', 'Stop immediately if the client reports discomfort.'] },
      ],
      competencyChecks: ['Drapes client correctly before shampooing', 'Uses fingertip pressure — not fingernails', 'Rinses thoroughly with no product residue', 'Disinfects shampoo bowl between clients'],
    },
  ],
  checkpoint: {
    slug: 'barber-module-2-checkpoint',
    title: 'Hair Science Checkpoint',
    lessonOrder: 7,
    durationMin: 20,
    objective: 'Demonstrate mastery of hair science and scalp analysis.',
    instructions: ['Answer all questions before reviewing results.', 'A score of 70% or higher is required to advance to Module 3.'],
    rubric: ['Identifies hair shaft layers', 'Names growth cycle phases', 'Assesses texture and porosity', 'Identifies scalp conditions requiring referral', 'Conducts consultation correctly'],
    quiz: {
      passingScore: 70,
      questions: [
        { prompt: 'Which layer of the hair shaft contains melanin and keratin?', choices: ['Cuticle', 'Cortex', 'Medulla', 'Follicle'], answerIndex: 1, rationale: 'The cortex is the middle layer and contains both melanin (color) and keratin (strength).' },
        { prompt: 'During which phase does hair actively grow?', choices: ['Telogen', 'Catagen', 'Anagen', 'Exogen'], answerIndex: 2, rationale: 'Anagen is the active growth phase, lasting 2–7 years.' },
        { prompt: 'A client has tinea capitis. What is the correct action?', choices: ['Proceed with the service using gloves', 'Apply antifungal shampoo and continue', 'Refuse the service and refer to a physician', 'Use a stronger disinfectant on tools after'], answerIndex: 2, rationale: 'Tinea capitis is a contagious fungal infection. Service must be refused and the client referred.' },
        { prompt: 'Hair with high porosity will:', choices: ['Resist moisture absorption', 'Absorb moisture quickly but lose it fast', 'Always be coarse in texture', 'Require no product'], answerIndex: 1, rationale: 'High porosity hair has an open or damaged cuticle — it absorbs quickly but cannot retain moisture well.' },
        { prompt: 'What is the purpose of a client consultation before service?', choices: ['To upsell products', 'To assess needs, screen for contraindications, and confirm the service plan', 'To fill time before the appointment', 'To check the client\'s payment method'], answerIndex: 1, rationale: 'Consultation protects the client and the barber by identifying contraindications and setting expectations.' },
        { prompt: 'Which describes hair density?', choices: ['The diameter of individual strands', 'The number of hairs per square inch', 'The ability to absorb moisture', 'The phase of the growth cycle'], answerIndex: 1, rationale: 'Density refers to how many hairs are present per square inch on the scalp.' },
      ],
    },
  },
};
