import type { ModuleSeed } from '../types';

export const module3: ModuleSeed = {
  slug: 'barber-module-3',
  title: 'Module 3: Haircutting Fundamentals',
  moduleOrder: 3,
  objective: 'Execute foundational haircutting techniques with correct posture, sectioning, and elevation.',
  lessons: [
    {
      slug: 'barber-lesson-15',
      title: 'Tools of the Trade',
      lessonOrder: 1,
      durationMin: 20,
      objective: 'Identify and maintain all standard barbering tools.',
      style: 'practical',
      tools: ['Clippers', 'Trimmers', 'Shears', 'Combs', 'Brushes', 'Straight razor', 'Guards'],
      sanitationNotes: ['Disinfect all reusable tools between clients.', 'Use clipper disinfectant spray on blades after each use.', 'Discard single-use items immediately.'],
      stateBoardFocus: ['tool identification', 'tool maintenance', 'clipper blade care'],
      sections: [
        { type: 'table', heading: 'Standard Barbering Tools', rows: [{ label: 'Clippers', value: 'Electric cutting tool. Used for bulk removal and fades. Requires blade disinfection after each use.' }, { label: 'Trimmers/Edgers', value: 'Smaller precision tool. Used for outlines, edges, and detail work.' }, { label: 'Shears', value: 'Scissors for cutting and texturizing. Keep sharp and clean.' }, { label: 'Straight Razor', value: 'Used for shaving and edging. Blade must be replaced between clients.' }, { label: 'Combs', value: 'Nonporous — must be disinfected between clients.' }, { label: 'Brushes', value: 'Neck brush, cleaning brush. Disinfect between clients.' }] },
        { type: 'steps', heading: 'Clipper Blade Maintenance', steps: ['Turn off and unplug the clipper.', 'Brush all visible hair from the blade.', 'Apply clipper disinfectant spray — keep blade visibly wet for full contact time.', 'Allow to dry before reuse.', 'Oil the blade lightly after disinfection to prevent rust.'] },
        { type: 'callout', heading: 'Straight Razor Rule', tone: 'warning', body: ['Straight razor blades must be replaced between every client. A used blade is a single-use item. Never reuse a blade on a second client.'] },
      ],
      competencyChecks: ['Identifies all standard barbering tools by name and function', 'Performs clipper blade disinfection correctly', 'Replaces straight razor blade between clients', 'Disinfects all nonporous tools between clients'],
    },
    {
      slug: 'barber-lesson-16',
      title: 'Sectioning & Parting',
      lessonOrder: 2,
      durationMin: 20,
      objective: 'Create consistent sections and parts to guide haircut execution.',
      style: 'practical',
      tools: ['Comb', 'Clips', 'Spray bottle'],
      stateBoardFocus: ['sectioning', 'parting', 'guide lines'],
      sections: [
        { type: 'text', heading: 'Why Sectioning Matters', body: ['Consistent sections create consistent results. Uneven sections lead to uneven cuts.', 'Sections control the amount of hair you work with at one time.', 'Parts create visual guides that keep the cut organized.'] },
        { type: 'steps', heading: 'Basic Sectioning Sequence', steps: ['Start at the nape — establish the perimeter first.', 'Create a horizontal part from ear to ear across the crown.', 'Clip the top section out of the way.', 'Work in horizontal sections from nape to crown.', 'Release the top section and work from front to back.'] },
        { type: 'callout', heading: 'Guide Lines', tone: 'tip', body: ['A guide line is the first section cut — all subsequent sections are matched to it. Keep your guide visible at all times.'] },
      ],
      competencyChecks: ['Creates consistent horizontal sections from nape to crown', 'Establishes and maintains a guide line', 'Clips sections cleanly without tangling'],
    },
    {
      slug: 'barber-lesson-17',
      title: 'Elevation & Overdirection',
      lessonOrder: 3,
      durationMin: 20,
      objective: 'Apply elevation and overdirection to control weight and shape.',
      style: 'theory',
      vocabulary: [
        { term: 'Elevation', definition: 'The angle at which hair is held away from the head before cutting.' },
        { term: 'Overdirection', definition: 'Pulling hair away from its natural fall to create weight or length variation.' },
        { term: 'Zero elevation', definition: 'Hair held flat against the head — creates maximum weight and length.' },
        { term: '90-degree elevation', definition: 'Hair held straight out from the head — removes weight, creates layers.' },
      ],
      stateBoardFocus: ['elevation angles', 'overdirection', 'weight distribution'],
      sections: [
        { type: 'table', heading: 'Elevation Effects', rows: [{ label: '0° (no elevation)', value: 'Maximum weight. Blunt perimeter. No layering.' }, { label: '45°', value: 'Moderate weight removal. Soft layers.' }, { label: '90°', value: 'Significant weight removal. Uniform layers.' }, { label: '180°', value: 'Maximum weight removal. Highly layered.' }] },
        { type: 'text', heading: 'Overdirection', body: ['Overdirecting toward the front adds length at the back.', 'Overdirecting toward the back adds length at the front.', 'Use overdirection to create graduation or to maintain length in specific areas.'] },
      ],
      competencyChecks: ['Demonstrates 0°, 45°, and 90° elevation on a mannequin', 'Explains the weight effect of each elevation angle', 'Uses overdirection to achieve a specific shape'],
    },
    {
      slug: 'barber-lesson-18',
      title: 'Clipper Cutting Basics',
      lessonOrder: 4,
      durationMin: 25,
      objective: 'Execute basic clipper cuts using guards and open/closed blade technique.',
      style: 'practical',
      tools: ['Clippers', 'Guards (#1–#8)', 'Comb', 'Brush', 'Clipper disinfectant spray'],
      sanitationNotes: ['Apply clipper disinfectant spray after each client.', 'Brush blade before spraying.'],
      stateBoardFocus: ['clipper guard sizes', 'clipper technique', 'against the grain vs with the grain'],
      sections: [
        { type: 'table', heading: 'Guard Sizes', rows: [{ label: '#0 (no guard)', value: 'Closest cut — skin fade.' }, { label: '#1', value: '1/8 inch.' }, { label: '#2', value: '1/4 inch.' }, { label: '#3', value: '3/8 inch.' }, { label: '#4', value: '1/2 inch.' }, { label: '#8', value: '1 inch — longest standard guard.' }] },
        { type: 'steps', heading: 'Basic Clipper Technique', steps: ['Select the appropriate guard for the desired length.', 'Start at the nape and work upward against the grain.', 'Use smooth, consistent strokes — do not rush.', 'Check for evenness by combing through after each pass.', 'Blend between guard sizes using a flicking motion at the transition.'] },
        { type: 'callout', heading: 'Against the Grain', tone: 'tip', body: ['Cutting against the grain (against hair growth direction) gives a closer, more even cut. Cutting with the grain leaves more length. Know which direction the client\'s hair grows before you start.'] },
      ],
      competencyChecks: ['Selects correct guard for desired length', 'Cuts against the grain for even results', 'Blends between guard sizes without visible lines', 'Disinfects clipper blade after each client'],
    },
    {
      slug: 'barber-lesson-19',
      title: 'Scissor Over Comb',
      lessonOrder: 5,
      durationMin: 25,
      objective: 'Execute scissor-over-comb technique for blending and tapering.',
      style: 'practical',
      tools: ['Shears', 'Comb', 'Spray bottle'],
      stateBoardFocus: ['scissor over comb', 'blending', 'tapering'],
      sections: [
        { type: 'steps', heading: 'Scissor Over Comb Technique', steps: ['Hold the comb at the desired angle against the head.', 'Slide the comb upward through the hair.', 'Cut the hair that extends above the comb teeth.', 'Keep the comb moving — do not stop mid-stroke.', 'Work in small sections for even results.', 'Check blend by combing through and looking for lines.'] },
        { type: 'text', heading: 'When to Use Scissor Over Comb', body: ['Use for blending between clipper lengths.', 'Use when clippers cannot reach (around the ears, nape).', 'Use for soft tapers on fine or thin hair.'] },
        { type: 'callout', heading: 'Common Error', tone: 'warning', body: ['Stopping the comb mid-stroke creates a visible line. Keep the comb moving continuously while cutting.'] },
      ],
      competencyChecks: ['Maintains consistent comb angle throughout the stroke', 'Keeps comb moving — no stops mid-stroke', 'Blends clipper and scissor work without visible lines'],
    },
    {
      slug: 'barber-lesson-20',
      title: 'Taper & Fade Fundamentals',
      lessonOrder: 6,
      durationMin: 25,
      objective: 'Execute a basic taper and low fade.',
      style: 'practical',
      tools: ['Clippers', 'Trimmers', 'Guards', 'Comb', 'Clipper disinfectant spray'],
      sanitationNotes: ['Disinfect all tools between clients.'],
      stateBoardFocus: ['taper', 'fade', 'blend line', 'transition'],
      sections: [
        { type: 'text', heading: 'Taper vs Fade', body: ['A taper gradually decreases length from top to nape — hair is never cut to the skin.', 'A fade cuts to the skin at the nape and sides, blending upward to longer lengths.', 'Both require a smooth, invisible transition between lengths.'] },
        { type: 'steps', heading: 'Low Fade Procedure', steps: ['Establish the fade line at the desired height (low = at or below the occipital bone).', 'Use a #0 or open blade to cut the skin line.', 'Work upward with increasing guard sizes (#1, #2, #3).', 'Blend each transition using a flicking motion.', 'Check the blend from all angles.', 'Use trimmers to clean the hairline and edges.'] },
        { type: 'callout', heading: 'The Blend Check', tone: 'tip', body: ['After each guard change, comb through and look for a visible line. If you see a line, blend it before moving on. Do not wait until the end.'] },
      ],
      competencyChecks: ['Establishes a clean fade line at the correct height', 'Blends between guard sizes without visible lines', 'Checks blend from multiple angles during the cut', 'Cleans hairline with trimmers after fading'],
    },
  ],
  checkpoint: {
    slug: 'barber-module-3-checkpoint',
    title: 'Haircutting Fundamentals Checkpoint',
    lessonOrder: 7,
    durationMin: 20,
    objective: 'Demonstrate mastery of haircutting fundamentals.',
    instructions: ['Answer all questions before reviewing results.', 'A score of 70% or higher is required to advance to Module 4.'],
    rubric: ['Identifies tools and their uses', 'Explains elevation effects', 'Describes clipper guard sizes', 'Sequences a basic fade correctly', 'Identifies scissor-over-comb errors'],
    quiz: {
      passingScore: 70,
      questions: [
        { prompt: 'What guard size produces a 1/4-inch cut?', choices: ['#1', '#2', '#3', '#4'], answerIndex: 1, rationale: 'Guard #2 = 1/4 inch.' },
        { prompt: 'What does 90-degree elevation do to the hair?', choices: ['Creates maximum weight', 'Removes significant weight and creates layers', 'Creates a blunt perimeter', 'Has no effect on weight'], answerIndex: 1, rationale: '90-degree elevation holds hair straight out from the head, removing significant weight.' },
        { prompt: 'What is the correct action when you see a visible blend line during a fade?', choices: ['Continue and fix at the end', 'Blend it immediately before moving on', 'Switch to a smaller guard', 'Start the fade over'], answerIndex: 1, rationale: 'Blend lines should be corrected immediately — waiting makes them harder to fix.' },
        { prompt: 'What is the key error to avoid in scissor-over-comb technique?', choices: ['Using too much tension', 'Stopping the comb mid-stroke', 'Cutting too close to the head', 'Using the wrong shear size'], answerIndex: 1, rationale: 'Stopping the comb mid-stroke creates a visible line in the cut.' },
        { prompt: 'A straight razor blade must be replaced:', choices: ['Once a week', 'Once a day', 'Between every client', 'When it looks dull'], answerIndex: 2, rationale: 'Straight razor blades are single-use items and must be replaced between every client.' },
        { prompt: 'What is the difference between a taper and a fade?', choices: ['A taper cuts to the skin; a fade does not', 'A fade cuts to the skin; a taper does not', 'They are the same technique', 'A taper uses clippers; a fade uses scissors'], answerIndex: 1, rationale: 'A fade cuts to the skin at the nape/sides. A taper gradually decreases length without reaching the skin.' },
      ],
    },
  },
};
