import type { ModuleSeed } from '../types';

export const module5: ModuleSeed = {
  slug: 'barber-module-5',
  title: 'Module 5: Shaving & Beard Services',
  moduleOrder: 5,
  objective: 'Execute professional shave preparation, straight razor technique, beard design, and post-shave care with correct sanitation and safety protocols.',
  lessons: [
    {
      slug: 'barber-lesson-29',
      title: 'Shave Preparation & Hot Towel Service',
      lessonOrder: 1,
      durationMin: 20,
      objective: 'Prepare the skin for a professional shave using hot towel and pre-shave products.',
      style: 'practical',
      tools: ['Hot towels', 'Pre-shave oil', 'Shaving cream or soap', 'Shaving brush', 'Neck strip', 'Cape'],
      sanitationNotes: [
        'Use a clean towel for every client — never reuse.',
        'Disinfect shaving brush handle between clients.',
        'Discard single-use items immediately after use.',
      ],
      stateBoardFocus: ['shave preparation', 'hot towel application', 'pre-shave products', 'skin softening'],
      sections: [
        {
          type: 'text',
          heading: 'Why Preparation Matters',
          body: [
            'Proper preparation softens the beard, opens the pores, and reduces razor drag — preventing irritation and ingrown hairs.',
            'A well-prepared face requires fewer passes, which means less irritation and a closer result.',
          ],
        },
        {
          type: 'steps',
          heading: 'Hot Towel Application',
          steps: [
            'Soak a clean towel in hot water.',
            'Test temperature on your wrist before applying to the client.',
            'Wring out excess water.',
            'Apply to the face for 2–3 minutes.',
            'Remove and apply pre-shave oil or cream.',
          ],
        },
        {
          type: 'table',
          heading: 'Pre-Shave Products',
          rows: [
            { label: 'Pre-shave oil', value: 'Lubricates and protects the skin. Applied before lather.' },
            { label: 'Shaving cream', value: 'Creates a protective lather. Most common in barbershops.' },
            { label: 'Shaving soap', value: 'Traditional. Requires a brush to build lather.' },
          ],
        },
        {
          type: 'callout',
          heading: 'Contraindications — Do Not Proceed If',
          tone: 'warning',
          body: [
            'Client has open cuts, active acne, inflamed bumps, rash, or infection on the face.',
            'Client reports sensitivity to heat or products.',
            'Skin condition makes shaving unsafe — stop and refer to instructor or follow shop procedure.',
          ],
        },
      ],
      competencyChecks: [
        'Tests towel temperature on wrist before applying to client',
        'Applies hot towel for correct duration (2–3 minutes)',
        'Selects appropriate pre-shave product for client skin type',
        'Identifies contraindications before beginning shave preparation',
        'Uses clean towel for every client',
      ],
    },
    {
      slug: 'barber-lesson-30',
      title: 'Straight Razor Shaving Technique',
      lessonOrder: 2,
      durationMin: 25,
      objective: 'Execute a professional straight razor shave with correct angle and stroke.',
      style: 'practical',
      tools: ['Shavette with fresh blade', 'Shaving lather', 'Neck strip', 'Cape', 'Sharps container', 'Gloves'],
      sanitationNotes: [
        'Replace shavette blade between every client — blades are single-use.',
        'Dispose of used blades in a puncture-resistant sharps container immediately.',
        'Never reuse a blade on a second client.',
        'Disinfect shavette handle between clients.',
      ],
      stateBoardFocus: ['razor angle', 'three-pass shave', 'skin stretching', 'with the grain', 'against the grain', 'sharps disposal'],
      sections: [
        {
          type: 'callout',
          heading: 'Blade Safety — Non-Negotiable',
          tone: 'warning',
          body: [
            'Shavette blades are single-use. Replace between every client.',
            'Dispose of used blades in a puncture-resistant sharps container immediately after use.',
            'Never recap a used blade with your fingers. Use the blade packaging or a blade disposal tool.',
          ],
        },
        {
          type: 'text',
          heading: 'Razor Angle',
          body: [
            'Hold the razor at a 30-degree angle to the skin.',
            'Too steep (above 45°) causes cuts. Too flat (below 15°) causes drag and ineffective cutting.',
            'Maintain consistent angle throughout each stroke.',
          ],
        },
        {
          type: 'steps',
          heading: 'The Three-Pass Shave',
          steps: [
            'First pass — with the grain (WTG): follow the direction of hair growth. Removes most of the beard. Safest pass.',
            'Second pass — across the grain (XTG): cut perpendicular to growth. Closer result.',
            'Third pass — against the grain (ATG): closest shave. Only for clients with no sensitivity. Assess skin before proceeding.',
          ],
        },
        {
          type: 'text',
          heading: 'Skin Stretching',
          body: [
            'Use your free hand to keep the skin taut at all times.',
            'Loose skin causes nicks and uneven shaving.',
            'Stretch in the direction opposite to the razor stroke.',
          ],
        },
        {
          type: 'steps',
          heading: 'Stroke Technique',
          steps: [
            'Use short, controlled strokes.',
            'Rinse the blade after every 2–3 strokes.',
            'Never drag the razor — let the blade do the work.',
            'Wipe blade on a clean towel or rinse in water — never on your skin.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic (alum block or styptic) to the nick.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Replaces shavette blade between every client',
        'Disposes of used blade in sharps container immediately',
        'Maintains 30-degree razor angle throughout service',
        'Keeps skin taut with free hand during all passes',
        'Sequences passes correctly: WTG → XTG → ATG (if appropriate)',
        'Stops service and follows blood exposure protocol if skin is nicked',
      ],
    },
    {
      slug: 'barber-lesson-31',
      title: 'Beard Design & Shaping',
      lessonOrder: 3,
      durationMin: 20,
      objective: 'Design and shape a beard to complement the client\'s face shape.',
      style: 'practical',
      tools: ['Trimmer', 'Guards', 'Shavette', 'Comb', 'Beard oil', 'Clipper disinfectant spray'],
      sanitationNotes: [
        'Pre-clean trimmer blades before applying disinfectant spray.',
        'Use clipper disinfectant spray with full contact time on blades.',
        'Replace shavette blade between clients.',
      ],
      stateBoardFocus: ['face shapes', 'beard lines', 'neckline placement', 'cheek line', 'mustache line'],
      sections: [
        {
          type: 'table',
          heading: 'Face Shapes & Beard Strategy',
          rows: [
            { label: 'Oval', value: 'Most beard styles work. Maintain natural proportions.' },
            { label: 'Round', value: 'Add length on the chin. Keep sides tight.' },
            { label: 'Square', value: 'Round the corners. Fuller on the chin.' },
            { label: 'Oblong', value: 'Keep sides full. Minimize chin length.' },
          ],
        },
        {
          type: 'table',
          heading: 'Beard Lines',
          rows: [
            { label: 'Cheek line', value: 'Natural or defined. Never set too low — it shortens the face.' },
            { label: 'Neckline', value: 'Two finger-widths above the Adam\'s apple. Most common mistake: set too high.' },
            { label: 'Mustache line', value: 'Follow the natural lip line.' },
          ],
        },
        {
          type: 'steps',
          heading: 'Trimming Procedure',
          steps: [
            'Comb beard downward to its natural fall.',
            'Trim to desired length with guards.',
            'Define cheek line with trimmer.',
            'Set neckline two finger-widths above the Adam\'s apple.',
            'Define mustache line along the lip.',
            'Refine lines with razor if appropriate and skin is healthy.',
            'Apply beard oil to finish.',
          ],
        },
        {
          type: 'callout',
          heading: 'Neckline Placement',
          tone: 'exam',
          body: [
            'The most common beard design error is setting the neckline too high. Two finger-widths above the Adam\'s apple is the standard. Too high creates a floating beard effect.',
          ],
        },
      ],
      competencyChecks: [
        'Identifies face shape and selects appropriate beard strategy',
        'Sets neckline at correct position (two finger-widths above Adam\'s apple)',
        'Defines cheek line without setting it too low',
        'Follows mustache line along the natural lip line',
        'Disinfects trimmer blades with clipper disinfectant spray before service',
      ],
    },
    {
      slug: 'barber-lesson-32',
      title: 'Post-Shave Care & Skin Treatment',
      lessonOrder: 4,
      durationMin: 15,
      objective: 'Apply correct post-shave products and handle common skin reactions.',
      style: 'practical',
      tools: ['Cold towel', 'Alum block', 'Witch hazel', 'Aftershave balm', 'Gloves'],
      sanitationNotes: [
        'Use a clean cold towel for every client.',
        'Alum block: rinse between clients or use disposable applicator.',
        'Discard single-use items immediately after use.',
      ],
      stateBoardFocus: ['post-shave products', 'alum block', 'cold towel', 'razor bumps', 'nick treatment'],
      sections: [
        {
          type: 'steps',
          heading: 'Post-Shave Sequence',
          steps: [
            'Apply a cold towel to close pores and soothe the skin. Leave on for 1–2 minutes.',
            'Remove cold towel and inspect the skin for nicks or irritation.',
            'Apply alum block to any nicks — hold for 10–15 seconds.',
            'Apply witch hazel to tone and soothe.',
            'Apply aftershave balm to moisturize and calm irritation.',
          ],
        },
        {
          type: 'table',
          heading: 'Post-Shave Products',
          rows: [
            { label: 'Alum block', value: 'Stops minor bleeding from nicks. Antiseptic. Hold on nick for 10–15 seconds.' },
            { label: 'Witch hazel', value: 'Tones and soothes the skin. Mild antiseptic.' },
            { label: 'Aftershave balm', value: 'Moisturizes and calms irritation. No alcohol — gentler on sensitive skin.' },
            { label: 'Aftershave splash', value: 'Antiseptic. Contains alcohol — can sting on sensitive skin.' },
          ],
        },
        {
          type: 'callout',
          heading: 'Nick Treatment',
          tone: 'warning',
          body: [
            'Apply alum block or styptic pencil directly to the nick. Hold for 10–15 seconds.',
            'Never use a tissue — it leaves fibers in the wound.',
            'If bleeding does not stop, follow blood exposure protocol: glove up, apply pressure, dispose of contaminated materials properly.',
          ],
        },
        {
          type: 'text',
          heading: 'Razor Bumps (Pseudofolliculitis Barbae)',
          body: [
            'Common in clients with curly hair. Caused by ingrown hairs curling back into the skin.',
            'Recommend: shave with the grain only, use a single-blade razor, avoid pulling skin too tight.',
            'Do not shave over active razor bumps — refer to a physician if severe.',
          ],
        },
      ],
      competencyChecks: [
        'Applies cold towel for correct duration after shaving',
        'Uses alum block correctly on nicks — holds for 10–15 seconds',
        'Selects appropriate aftershave product for client skin type',
        'Identifies razor bumps and provides correct client education',
        'Follows blood exposure protocol if bleeding does not stop',
      ],
    },
    {
      slug: 'barber-lesson-33',
      title: 'Mustache Trimming & Styling',
      lessonOrder: 5,
      durationMin: 15,
      objective: 'Trim and style a mustache to complement the client\'s features.',
      style: 'practical',
      tools: ['Shears', 'Trimmer', 'Guards', 'Comb', 'Mustache wax', 'Clipper disinfectant spray'],
      sanitationNotes: [
        'Pre-clean trimmer blades before applying disinfectant spray.',
        'Use clipper disinfectant spray with full contact time.',
        'Disinfect shears between clients.',
      ],
      stateBoardFocus: ['mustache styles', 'philtrum', 'lip line', 'mustache trimming procedure'],
      sections: [
        {
          type: 'table',
          heading: 'Mustache Styles',
          rows: [
            { label: 'Natural', value: 'Trimmed to follow the lip line. Clean and understated.' },
            { label: 'Chevron', value: 'Full, thick, trimmed straight across. Classic masculine style.' },
            { label: 'Handlebar', value: 'Long ends styled upward with wax. Requires product and maintenance.' },
            { label: 'Pencil', value: 'Thin line above the lip. Precise trimming required.' },
          ],
        },
        {
          type: 'steps',
          heading: 'Trimming Procedure',
          steps: [
            'Comb mustache downward to its natural fall.',
            'Trim bulk with scissors or guards to desired length.',
            'Define the lip line with a trimmer — follow the natural curve.',
            'Clean up the philtrum (area between nose and lip).',
            'Apply mustache wax if styling a handlebar or shaped style.',
            'Comb through and inspect for evenness.',
          ],
        },
        {
          type: 'callout',
          heading: 'Lip Line Rule',
          tone: 'tip',
          body: [
            'Always follow the natural lip line when defining the mustache edge. Cutting above the lip line removes too much and creates an unnatural gap.',
          ],
        },
      ],
      competencyChecks: [
        'Identifies mustache style requested and selects appropriate technique',
        'Trims bulk before defining the lip line',
        'Follows natural lip line when defining the mustache edge',
        'Cleans up philtrum without overcutting',
        'Disinfects trimmer blades before service',
      ],
    },
  ],
  checkpoint: {
    slug: 'barber-module-5-checkpoint',
    title: 'Shaving & Beard Checkpoint',
    lessonOrder: 6,
    durationMin: 20,
    objective: 'Demonstrate mastery of shaving and beard services.',
    instructions: ['Answer all questions before reviewing results.', 'A score of 70% or higher is required to advance to Module 6.'],
    rubric: ['States correct razor angle', 'Sequences three-pass shave correctly', 'Identifies neckline placement', 'Names post-shave products and their uses', 'Identifies razor bump prevention strategy'],
    quiz: {
      passingScore: 70,
      questions: [
        { prompt: 'What angle should the straight razor be held at during shaving?', choices: ['15 degrees', '30 degrees', '45 degrees', '60 degrees'], answerIndex: 1, rationale: 'A 30-degree angle provides the optimal balance between closeness and safety.' },
        { prompt: 'Where should the neckline be set when shaping a beard?', choices: ['At the jawline', 'At the Adam\'s apple', 'Two finger-widths above the Adam\'s apple', 'At the chin'], answerIndex: 2, rationale: 'Two finger-widths above the Adam\'s apple is the standard neckline position.' },
        { prompt: 'What is the first pass in a three-pass shave?', choices: ['Against the grain', 'Across the grain', 'With the grain', 'In circular motions'], answerIndex: 2, rationale: 'The first pass always goes with the grain to remove bulk safely.' },
        { prompt: 'Which product stops minor bleeding from razor nicks?', choices: ['Aftershave balm', 'Witch hazel', 'Alum block', 'Pre-shave oil'], answerIndex: 2, rationale: 'An alum block is an antiseptic that constricts blood vessels to stop minor bleeding.' },
        { prompt: 'Razor bumps are most common in clients with:', choices: ['Straight hair', 'Fine hair', 'Curly hair', 'Thick hair'], answerIndex: 2, rationale: 'Curly hair is more likely to curl back into the skin, causing ingrown hairs and razor bumps.' },
        { prompt: 'How long should a hot towel be applied before shaving?', choices: ['30 seconds', '2–3 minutes', '10 minutes', '15 minutes'], answerIndex: 1, rationale: '2–3 minutes is sufficient to soften the beard and open the pores.' },
      ],
    },
  },
};
