import type { ModuleSeed } from '../types';

export const module4: ModuleSeed = {
  slug: 'barber-module-4',
  title: 'Module 4: Haircutting Techniques',
  moduleOrder: 4,
  objective: 'Execute foundational and advanced haircutting techniques with correct sanitation, safety, and NIC-compliant infection control on every service.',
  lessons: [
    {
      slug: 'barber-lesson-22',
      title: 'Head Shape & Sectioning',
      lessonOrder: 1,
      durationMin: 20,
      objective: 'Identify the sections of the head and use them to guide haircut structure.',
      style: 'theory',
      tools: ['Comb', 'Sectioning clips'],
      sanitationNotes: [
        'Pre-clean all tools before applying disinfectant.',
        'Apply EPA-registered disinfectant and maintain full contact time per label.',
        'Discard single-use items immediately after use.',
      ],
      stateBoardFocus: ['head sections', 'reference points', 'occipital bone', 'parietal ridge'],
      sections: [
        {
          type: 'table',
          heading: 'Sections of the Head',
          rows: [
            { label: 'Top', value: 'Crown to front hairline.' },
            { label: 'Sides', value: 'Temples to behind the ears.' },
            { label: 'Back', value: 'Occipital bone to nape.' },
            { label: 'Nape', value: 'Hairline at the back of the neck.' },
          ],
        },
        {
          type: 'table',
          heading: 'Key Reference Points',
          rows: [
            { label: 'Occipital bone', value: 'Bony protrusion at the back of the skull. Key reference for fade lines.' },
            { label: 'Parietal ridge', value: 'Widest part of the head. Determines where the fade transitions.' },
            { label: 'Temporal recession', value: 'Natural recession at the temples.' },
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands.',
            'Pre-clean all tools — remove hair and debris before applying disinfectant.',
            'Apply EPA-registered disinfectant and maintain full contact time per label. Do not wipe off early.',
            'Discard all single-use items after use. Do not reuse porous items.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin on the scalp, signs of scalp infection or inflammation, client reports pain or discomfort, or tool malfunction.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Identifies all head sections and reference points correctly',
        'Follows pre-clean → disinfect → contact time sequence before service',
        'Stops service and follows blood exposure protocol if skin is broken',
        'Discards single-use items immediately after use',
      ],
    },
    {
      slug: 'barber-lesson-23',
      title: 'The Fade — Low, Mid & High',
      lessonOrder: 2,
      durationMin: 30,
      objective: 'Execute low, mid, and high fade techniques with smooth transitions.',
      style: 'practical',
      tools: ['Clippers', 'Guards (#0–#4)', 'Trimmer', 'Comb', 'Clipper disinfectant spray'],
      sanitationNotes: [
        'Pre-clean clipper blades before applying disinfectant spray.',
        'Use clipper disinfectant spray — keep blades visibly wet for full contact time.',
        'Disinfect workstation and chair after each client.',
      ],
      stateBoardFocus: ['low fade', 'mid fade', 'high fade', 'skin fade', 'blend line'],
      sections: [
        {
          type: 'table',
          heading: 'Fade Types',
          rows: [
            { label: 'Low fade', value: 'Starts just above the ear and nape. Conservative, professional.' },
            { label: 'Mid fade', value: 'Starts at the temple. Versatile, most requested.' },
            { label: 'High fade', value: 'Starts at the parietal ridge. Bold, dramatic.' },
            { label: 'Skin fade (bald fade)', value: 'Goes to bare skin. Requires #0 or foil shaver.' },
          ],
        },
        {
          type: 'steps',
          heading: 'Fade Technique',
          steps: [
            'Establish the fade line with a #1 or #2.',
            'Work upward with progressively larger guards.',
            'Use the open/close lever to blend between guard sizes.',
            'Blend with a flicking motion at each transition.',
            'Check for lines from all angles and blend until smooth.',
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands.',
            'Pre-clean all tools — remove hair and debris before applying disinfectant.',
            'Apply EPA-registered disinfectant. Use clipper disinfectant spray on blades — keep visibly wet for full contact time per label.',
            'Discard all single-use items after use. Do not reuse porous items.',
            'Disinfect workstation and chair after each client.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin, signs of scalp infection or inflammation, client reports pain, or clipper malfunction or overheating.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Executes low, mid, and high fade with smooth transitions',
        'Follows pre-clean → disinfect → contact time sequence before service',
        'Uses clipper disinfectant spray with correct dwell time on blades',
        'Stops service and follows blood exposure protocol if skin is broken',
        'Discards single-use items immediately after use',
      ],
    },
    {
      slug: 'barber-lesson-24',
      title: 'Clipper Over Comb',
      lessonOrder: 3,
      durationMin: 20,
      objective: 'Use the clipper-over-comb technique to cut and blend hair.',
      style: 'practical',
      tools: ['Clippers', 'Comb', 'Clipper disinfectant spray'],
      sanitationNotes: [
        'Pre-clean clipper blades before applying disinfectant spray.',
        'Use clipper disinfectant spray with full contact time.',
        'Disinfect workstation and chair after each client.',
      ],
      stateBoardFocus: ['clipper over comb', 'blending', 'tapering'],
      sections: [
        {
          type: 'steps',
          heading: 'Clipper Over Comb Technique',
          steps: [
            'Hold the comb flat against the head at the desired angle.',
            'Lift the comb slightly to expose the hair to be cut.',
            'Run the clipper along the top of the comb in a smooth, continuous motion.',
            'Work in sections, overlapping each pass slightly.',
          ],
        },
        {
          type: 'table',
          heading: 'Common Mistakes',
          rows: [
            { label: 'Comb too far from head', value: 'Creates uneven results. Keep comb close to the scalp.' },
            { label: 'Moving too slowly', value: 'Causes clipper lines. Keep motion smooth and continuous.' },
            { label: 'Not following head curve', value: 'Creates flat spots. Follow the contour of the head.' },
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands.',
            'Pre-clean all tools — remove hair and debris before applying disinfectant.',
            'Apply EPA-registered disinfectant. Use clipper disinfectant spray on blades and maintain full contact time per label.',
            'Discard all single-use items after use. Do not reuse porous items.',
            'Disinfect workstation and chair after each client.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin, signs of scalp infection or inflammation, client reports pain, or clipper overheating or malfunction.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Executes clipper-over-comb with consistent angle and smooth motion',
        'Follows pre-clean → disinfect → contact time sequence before service',
        'Uses clipper disinfectant spray with correct dwell time on blades',
        'Stops service and follows blood exposure protocol if skin is broken',
        'Discards single-use items immediately after use',
      ],
    },
    {
      slug: 'barber-lesson-25',
      title: 'Scissor Over Comb',
      lessonOrder: 4,
      durationMin: 20,
      objective: 'Use scissor-over-comb to cut and blend the top and sides.',
      style: 'practical',
      tools: ['Shears', 'Comb', 'Spray bottle'],
      sanitationNotes: [
        'Pre-clean shears and combs before applying disinfectant.',
        'Apply EPA-registered disinfectant and maintain full contact time.',
        'Disinfect workstation and chair after each client.',
      ],
      stateBoardFocus: ['scissor over comb', 'point cutting', 'slide cutting', 'blending'],
      sections: [
        {
          type: 'steps',
          heading: 'Scissor Over Comb Technique',
          steps: [
            'Comb hair upward or outward from the head.',
            'Position the comb at the desired length.',
            'Cut along the top of the comb with the shears.',
            'Work in consistent sections.',
          ],
        },
        {
          type: 'text',
          heading: 'Advanced Techniques',
          body: [
            'Point cutting: cut into the ends at an angle to remove weight and add texture. Hold shears vertically and make small snips into the hair ends.',
            'Slide cutting: thin and taper hair by sliding the open shears down the hair shaft. Used for blending and removing bulk.',
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands.',
            'Pre-clean all tools — remove hair and debris from shears and combs before applying disinfectant.',
            'Apply EPA-registered disinfectant and maintain full contact time per label. Do not wipe off early.',
            'Discard all single-use items after use. Do not reuse porous items.',
            'Disinfect workstation and chair after each client.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin, signs of scalp infection or inflammation, client reports pain from shear contact, or shear malfunction or blade damage.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Executes scissor-over-comb with consistent angle and soft finish',
        'Follows pre-clean → disinfect → contact time sequence before service',
        'Stops service and follows blood exposure protocol if skin is broken',
        'Discards single-use items immediately after use',
        'Disinfects shears and combs with EPA-registered disinfectant before service',
      ],
    },
    {
      slug: 'barber-lesson-26',
      title: 'Lineup & Edging',
      lessonOrder: 5,
      durationMin: 20,
      objective: 'Create clean, sharp lines at the hairline, temples, around the ears, sideburns, and nape while preserving the natural hairline, protecting the skin, maintaining sanitation, and choosing shapes that suit the client and grow out cleanly.',
      style: 'practical',
      tools: ['T-liner/outliner trimmer', 'Straight razor or shavette', 'Barber comb', 'Hand mirror', 'Neck strip', 'Cape', 'Shaving gel or lather', 'EPA-registered disinfectant', 'Clipper disinfectant spray', 'Gloves'],
      sanitationNotes: [
        'Pre-clean all tools before applying disinfectant.',
        'Apply EPA-registered disinfectant and maintain full contact time per label.',
        'Use clipper disinfectant spray on trimmer blades — keep visibly wet for full contact time.',
        'Discard single-use razor blades in a sharps container immediately after use.',
        'Porous items cannot be disinfected — discard after use.',
        'Change disinfectant solution every 24 hours or sooner if contaminated.',
      ],
      stateBoardFocus: ['lineup', 'edging', 'natural hairline', 'skin tension', 'razor contraindications', 'symmetry check'],
      sections: [
        {
          type: 'text',
          heading: 'Why This Skill Matters',
          body: [
            'A lineup is a finishing service, not a haircut correction tool. Its job is to sharpen the front hairline, temples, sideburn edges, around the ears, and nape.',
            'The barber\'s rule: define what is already there. Do not invent a new hairline unless the service plan clearly calls for it and the client understands the maintenance.',
          ],
        },
        {
          type: 'callout',
          heading: 'Contraindications — Do Not Use Razor Over',
          tone: 'warning',
          body: [
            'Cuts, abrasions, or open skin.',
            'Active acne or inflamed bumps.',
            'Rash or infection.',
            'Skin that is already irritated.',
            'Areas prone to keloid scarring if razor use may trigger trauma.',
            'Non-negotiable rule: trimmer defines first, razor refines second. Never use the razor to guess the shape.',
          ],
        },
        {
          type: 'steps',
          heading: 'Service Order',
          steps: [
            'Front hairline → temples → around ears → sideburns → nape → symmetry check → razor detailing if appropriate.',
          ],
        },
        {
          type: 'steps',
          heading: 'Procedure',
          steps: [
            'Establish the front hairline: stand directly in front, identify the natural line, start at center and work outward. Use light pressure and short controlled motions. Remove only overgrowth — do not push the line back.',
            'Refine the front edge: use small anchor strokes instead of one long pass. Check from the front and slightly above eye level.',
            'Shape the temples: decide squared or softly tapered based on haircut, growth pattern, and client preference. Match both sides before deepening.',
            'Outline around the ears: fold the ear gently only as needed. Use short controlled movements around the ear curve.',
            'Balance the sideburns: comb down, check both from the front — not only from the side. Match length, width, and bottom line.',
            'Create the nape outline: ask for tapered, rounded, or square. Keep centered and symmetrical.',
            'Check symmetry: step back, use mirror to compare both sides. Correct only the uneven area — do not keep cutting both sides higher.',
            'Razor detailing if skin is healthy: apply lather, stretch skin firmly, hold razor at low angle with light pressure, use short controlled strokes. Do not go over broken, raised, or irritated skin.',
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands before touching tools or the client.',
            'Pre-clean all tools — remove all hair and debris before applying disinfectant. Debris blocks disinfectant effectiveness.',
            'Apply EPA-registered disinfectant and allow full contact time per label — typically 10 minutes. Do not wipe off early.',
            'For clipper and trimmer blades: use clipper disinfectant spray and keep blades visibly wet for the full required contact time.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin, signs of scalp infection or inflammation, client reports pain or discomfort, or tool malfunction.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
        {
          type: 'table',
          heading: 'Correct vs. Incorrect Lineup',
          rows: [
            { label: '✅ Correct', value: 'Follows natural hairline. Even from front. Matches haircut design. Preserves density at weak corners. Sharpens without irritating skin.' },
            { label: '❌ Incorrect', value: 'Pushed back to look "extra clean." One temple higher than the other. Jagged line from long uncontrolled strokes. Sideburns different in length. Razor used over broken skin.' },
          ],
        },
      ],
      competencyChecks: [
        'Demonstrates proper hand sanitation, draping, and workstation preparation',
        'Identifies contraindications before service',
        'Maintains skin tension during edging',
        'Preserves natural hairline unless redesign is intentionally planned',
        'Uses short controlled strokes instead of one long sweep',
        'Checks symmetry from the front view',
        'Selects correct nape shape based on client preference',
        'Avoids razor use on contraindicated skin',
        'Completes post-service cleanup and disinfection properly',
      ],
    },
    {
      slug: 'barber-lesson-27',
      title: 'Flat Top & Classic Cuts',
      lessonOrder: 6,
      durationMin: 20,
      objective: 'Execute a flat top and classic taper haircut.',
      style: 'practical',
      tools: ['Clippers', 'Guards', 'Flat top comb', 'Trimmer', 'Clipper disinfectant spray'],
      sanitationNotes: [
        'Pre-clean clipper blades before applying disinfectant spray.',
        'Use clipper disinfectant spray with full contact time on blades.',
        'Disinfect workstation and chair after each client.',
      ],
      stateBoardFocus: ['flat top', 'classic taper', 'level surface', 'guide line'],
      sections: [
        {
          type: 'steps',
          heading: 'Flat Top Procedure',
          steps: [
            'Establish the height on top with a pick and clipper.',
            'Use a level comb or flat top comb to guide the cut.',
            'Work from front to back, maintaining a flat plane.',
            'Fade or taper the sides.',
            'Check the level from multiple angles — front, side, and above.',
          ],
        },
        {
          type: 'steps',
          heading: 'Classic Taper Procedure',
          steps: [
            'Start with the longest guard on top.',
            'Work down with progressively shorter guards.',
            'Blend each transition smoothly.',
            'Finish with a clean lineup.',
          ],
        },
        {
          type: 'steps',
          heading: 'Pre-Service Sanitation (Required)',
          steps: [
            'Wash or sanitize hands.',
            'Pre-clean all tools — remove hair and debris before applying disinfectant.',
            'Apply EPA-registered disinfectant. Use clipper disinfectant spray on blades and maintain full contact time per label.',
            'Discard all single-use items after use. Do not reuse porous items.',
            'Disinfect workstation and chair after each client.',
          ],
        },
        {
          type: 'callout',
          heading: 'Stop Conditions',
          tone: 'warning',
          body: [
            'Stop service immediately if you observe: open cuts or broken skin, signs of scalp infection or inflammation, client reports pain, or tool malfunction or overheating.',
          ],
        },
        {
          type: 'steps',
          heading: 'Blood Exposure Protocol',
          steps: [
            'Stop service immediately.',
            'Put on gloves before touching the affected area.',
            'Apply antiseptic to the client\'s skin.',
            'Dispose of all contaminated single-use materials in a sealed bag.',
            'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.',
            'Double-bag contaminated waste before disposal.',
            'Wash hands thoroughly after removing gloves.',
          ],
        },
      ],
      competencyChecks: [
        'Executes flat top with level, even surface across the top',
        'Executes classic taper with smooth transitions from top to nape',
        'Follows pre-clean → disinfect → contact time sequence before service',
        'Uses clipper disinfectant spray with correct dwell time on blades',
        'Stops service and follows blood exposure protocol if skin is broken',
        'Discards single-use items immediately after use',
      ],
    },
  ],
  checkpoint: {
    slug: 'barber-module-4-checkpoint',
    title: 'Haircutting Checkpoint',
    lessonOrder: 7,
    durationMin: 20,
    objective: 'Demonstrate mastery of haircutting techniques.',
    instructions: ['Answer all questions before reviewing results.', 'A score of 70% or higher is required to advance to Module 5.'],
    rubric: ['Identifies head sections and reference points', 'Sequences a fade correctly', 'Describes clipper-over-comb errors', 'Identifies lineup contraindications', 'States blood exposure protocol'],
    quiz: {
      passingScore: 70,
      questions: [
        { prompt: 'A mid fade starts at which reference point?', choices: ['The nape', 'The occipital bone', 'The temple', 'The parietal ridge'], answerIndex: 2, rationale: 'A mid fade starts at the temple area, between the low and high fade.' },
        { prompt: 'Which technique produces a softer result than clipper over comb?', choices: ['Skin fade', 'Scissor over comb', 'Razor cutting', 'Clipper flicking'], answerIndex: 1, rationale: 'Scissor over comb produces a softer, more natural finish.' },
        { prompt: 'What is the parietal ridge?', choices: ['The hairline at the nape', 'The bony protrusion at the back of the skull', 'The widest part of the head', 'The front hairline'], answerIndex: 2, rationale: 'The parietal ridge is the widest part of the head and a key reference for high fades.' },
        { prompt: 'Point cutting is used to:', choices: ['Create a blunt, heavy line', 'Remove weight and add texture', 'Create a skin fade', 'Establish the guide line'], answerIndex: 1, rationale: 'Point cutting removes weight from the ends and adds texture and movement.' },
        { prompt: 'When performing a lineup, you should never:', choices: ['Use a razor', 'Cut above the natural temple hairline', 'Square the nape', 'Use a trimmer'], answerIndex: 1, rationale: 'Cutting above the natural temple hairline creates an unnatural appearance and pushes the hairline back.' },
        { prompt: 'The flat top is considered technically demanding because it requires:', choices: ['The most guards', 'A perfectly level surface on top', 'The longest cutting time', 'Special clippers'], answerIndex: 1, rationale: 'Maintaining a perfectly flat, level plane on top of the head requires precision and skill.' },
      ],
    },
  },
};
