import type { ModuleSeed } from '../types';

export const module1: ModuleSeed = {
  slug: 'barber-module-1',
  title: 'Module 1: Infection Control & Safety',
  moduleOrder: 1,
  objective: 'Apply infection control standards, OSHA requirements, and Indiana barbering law to every service.',
  lessons: [
    {
      slug: 'barber-lesson-1',
      title: 'Welcome to the Barber Apprenticeship',
      lessonOrder: 1,
      durationMin: 15,
      objective: 'Understand the structure of the DOL-registered barber apprenticeship program.',
      style: 'theory',
      stateBoardFocus: ['DOL apprenticeship requirements', 'program structure'],
      sections: [
        { type: 'text', heading: 'Program Overview', body: ['This is a DOL-registered apprenticeship program. You earn hours toward licensure while working under a licensed barber.', 'The program combines on-the-job training (OJT) with related technical instruction (RTI).', 'You must complete all required hours and pass the Indiana state board exam to receive your license.'] },
        { type: 'text', heading: 'Your Responsibilities', body: ['Clock in and out accurately for every shift.', 'Complete all LMS lessons and checkpoints.', 'Follow all shop sanitation and safety rules at all times.', 'Communicate with your supervisor and program coordinator.'] },
        { type: 'callout', heading: 'State Board Note', tone: 'exam', body: ['Indiana requires 1500 hours of apprenticeship training. Every hour must be documented and verifiable.'] },
      ],
      competencyChecks: ['Describes the DOL apprenticeship structure', 'Identifies OJT vs RTI requirements', 'Knows how to log hours correctly'],
    },
    {
      slug: 'barber-lesson-2',
      title: 'OSHA Standards & Bloodborne Pathogens',
      lessonOrder: 2,
      durationMin: 20,
      objective: 'Identify OSHA requirements and bloodborne pathogen risks in a barbershop.',
      style: 'safety',
      tools: ['Gloves', 'Sharps container', 'Biohazard bags'],
      stateBoardFocus: ['OSHA standards', 'bloodborne pathogens', 'universal precautions'],
      sections: [
        { type: 'text', heading: 'OSHA in the Barbershop', body: ['OSHA (Occupational Safety and Health Administration) sets workplace safety standards that apply to barbershops.', 'Key requirements: exposure control plan, PPE availability, employee training, and proper disposal of sharps.'] },
        { type: 'text', heading: 'Bloodborne Pathogens', body: ['Bloodborne pathogens are microorganisms in blood that can cause disease — including HIV, Hepatitis B, and Hepatitis C.', 'In barbering, exposure risk comes from cuts during shaving or edging.'] },
        { type: 'steps', heading: 'Blood Exposure Protocol', steps: ['Stop service immediately.', 'Put on gloves before touching the affected area.', 'Apply antiseptic to the client\'s skin.', 'Dispose of all contaminated single-use materials in a sealed bag.', 'Clean and disinfect blood-contaminated tools with EPA-registered disinfectant.', 'Double-bag contaminated waste before disposal.', 'Wash hands thoroughly after removing gloves.'] },
        { type: 'callout', heading: 'Universal Precautions', tone: 'warning', body: ['Treat every client\'s blood as potentially infectious. Always glove up before contact with blood or open skin.'] },
      ],
      competencyChecks: ['States OSHA requirements for barbershops', 'Demonstrates blood exposure protocol in correct order', 'Identifies bloodborne pathogen risks', 'Uses universal precautions on every service'],
    },
    {
      slug: 'barber-lesson-3',
      title: 'Sanitation vs. Disinfection vs. Sterilization',
      lessonOrder: 3,
      durationMin: 20,
      objective: 'Distinguish between sanitation, disinfection, and sterilization and apply each correctly.',
      style: 'theory',
      vocabulary: [
        { term: 'Sanitation', definition: 'Reducing the number of pathogens to a safe level — cleaning visible debris.' },
        { term: 'Disinfection', definition: 'Destroying most pathogens on nonporous surfaces using an EPA-registered disinfectant.' },
        { term: 'Sterilization', definition: 'Destroying all microbial life including spores — required for invasive tools only.' },
      ],
      stateBoardFocus: ['sanitation vs disinfection vs sterilization', 'EPA-registered disinfectant', 'contact time'],
      sections: [
        { type: 'table', heading: 'Three Levels of Decontamination', rows: [{ label: 'Sanitation', value: 'Removes visible debris. Required before disinfection.' }, { label: 'Disinfection', value: 'Destroys most pathogens. Required for all reusable nonporous tools.' }, { label: 'Sterilization', value: 'Destroys all life. Required for tools that penetrate skin.' }] },
        { type: 'steps', heading: 'Correct Disinfection Sequence', steps: ['Pre-clean: remove all visible hair and debris.', 'Apply EPA-registered disinfectant.', 'Maintain full contact time per label — do not wipe off early.', 'Remove, dry, and store in a clean covered container.'] },
        { type: 'callout', heading: 'NIC Exam Focus', tone: 'exam', body: ['NIC practical exams test sequence, not just knowledge. Pre-clean before disinfect. Contact time must be observed. This order is non-negotiable.'] },
      ],
      competencyChecks: ['Correctly sequences pre-clean → disinfect → contact time → store', 'Distinguishes sanitation from disinfection from sterilization', 'Identifies which level applies to each tool type'],
    },
    {
      slug: 'barber-lesson-4',
      title: 'Tool Disinfection Procedures',
      lessonOrder: 4,
      durationMin: 20,
      objective: 'Perform correct pre-service and post-service tool disinfection.',
      style: 'practical',
      tools: ['EPA-registered disinfectant', 'Clipper disinfectant spray', 'Cleaning brush', 'Gloves', 'Covered storage container'],
      sanitationNotes: ['Pre-clean visible debris before disinfecting.', 'Follow manufacturer contact time exactly.', 'Change disinfectant solution every 24 hours or sooner if contaminated.', 'Porous items cannot be disinfected — discard after use.'],
      stateBoardFocus: ['tool disinfection sequence', 'clipper blade protocol', 'single-use items', 'porous vs nonporous'],
      sections: [
        { type: 'steps', heading: 'Nonporous Tool Disinfection', steps: ['Put on gloves.', 'Pre-clean: remove all hair and debris with a brush.', 'Apply EPA-registered disinfectant — fully immerse or saturate.', 'Maintain contact time per label (typically 10 minutes).', 'Remove, rinse if required, dry, and store in a clean covered container.'] },
        { type: 'steps', heading: 'Clipper and Trimmer Blade Protocol', steps: ['Turn off and unplug the tool.', 'Brush away all visible hair and debris from the blade.', 'Apply clipper disinfectant spray — keep blade visibly wet for full contact time.', 'Allow to dry before reuse or storage.'] },
        { type: 'callout', heading: 'Porous Items', tone: 'warning', body: ['Porous items (wooden handles, foam, emery boards) cannot be properly disinfected once contaminated. Discard them. Do not return to service.'] },
      ],
      competencyChecks: ['Pre-cleans tools before applying disinfectant', 'Maintains full contact time without wiping early', 'Uses clipper disinfectant spray correctly on blades', 'Discards single-use and porous items after use', 'Changes disinfectant solution every 24 hours'],
    },
    {
      slug: 'barber-lesson-5',
      title: 'Shop Sanitation & Client Safety',
      lessonOrder: 5,
      durationMin: 15,
      objective: 'Maintain a sanitary workstation and protect client health.',
      style: 'practical',
      tools: ['EPA-registered disinfectant', 'Clean towels', 'Neck strips', 'Cape', 'Waste container'],
      sanitationNotes: ['Disinfect workstation surfaces between every client.', 'Replace neck strip and cape for each client.', 'Never reuse a neck strip.'],
      stateBoardFocus: ['workstation sanitation', 'client draping', 'between-client reset'],
      sections: [
        { type: 'steps', heading: 'Between-Client Station Reset', steps: ['Remove used linens, disposables, and visible debris.', 'Clean and disinfect nonporous surfaces — chair, headrest, counter.', 'Replace with clean towels, fresh neck strip, and disinfected implements.', 'Confirm station is dry, organized, and ready.'] },
        { type: 'text', heading: 'Client Draping', body: ['Always use a clean neck strip so the cape does not touch bare skin.', 'Seat the client upright with head in natural position before beginning.', 'Check draping throughout the service — do not let the cape slip.'] },
        { type: 'callout', heading: 'State Board Standard', tone: 'exam', body: ['Proper draping is tested in the NIC practical. Neck strip must be placed before the cape. Cape must not contact bare skin.'] },
      ],
      competencyChecks: ['Resets station completely between clients', 'Places neck strip before cape on every client', 'Disinfects all nonporous surfaces between clients', 'Disposes of single-use items immediately after use'],
    },
    {
      slug: 'barber-lesson-6',
      title: 'Indiana Barbering Laws & Regulations',
      lessonOrder: 6,
      durationMin: 20,
      objective: 'Identify key Indiana state barbering laws that govern practice.',
      style: 'theory',
      stateBoardFocus: ['Indiana Professional Licensing Agency', 'license requirements', 'apprenticeship hours', 'scope of practice'],
      sections: [
        { type: 'text', heading: 'Indiana Professional Licensing Agency (IPLA)', body: ['The IPLA regulates barbers in Indiana under IC 25-8.', 'You must hold a valid Indiana barber license to practice independently.', 'Apprentices must work under a licensed barber at a licensed shop.'] },
        { type: 'table', heading: 'Key Requirements', rows: [{ label: 'Apprenticeship hours', value: '1500 hours required' }, { label: 'Exam', value: 'Written + practical through PSI/NIC' }, { label: 'License renewal', value: 'Every 2 years with CE requirements' }, { label: 'Shop license', value: 'Required for every location' }] },
        { type: 'callout', heading: 'Scope of Practice', tone: 'info', body: ['Indiana barbers may perform: haircuts, shaves, beard trims, scalp treatments, and limited chemical services. Services outside scope require additional licensure.'] },
      ],
      competencyChecks: ['Identifies IPLA as the governing body for Indiana barbers', 'States the 1500-hour apprenticeship requirement', 'Describes license renewal requirements', 'Identifies services within and outside barber scope of practice'],
    },
  ],
  checkpoint: {
    slug: 'barber-module-1-checkpoint',
    title: 'Infection Control Checkpoint',
    lessonOrder: 7,
    durationMin: 20,
    objective: 'Demonstrate mastery of infection control and Indiana barbering law.',
    instructions: ['Answer all questions before reviewing results.', 'A score of 70% or higher is required to advance to Module 2.'],
    rubric: ['Correctly sequences disinfection steps', 'Identifies bloodborne pathogen risks', 'States blood exposure protocol', 'Distinguishes sanitation from disinfection from sterilization', 'Identifies Indiana licensing requirements'],
    quiz: {
      passingScore: 70,
      questions: [
        { prompt: 'What must happen before applying disinfectant to a tool?', choices: ['Rinse with water only', 'Pre-clean to remove visible debris', 'Soak in bleach', 'Dry with a towel'], answerIndex: 1, rationale: 'Disinfection is not effective on visibly soiled implements. Pre-cleaning is always the first step.' },
        { prompt: 'What is the correct first action when a client is nicked during a shave?', choices: ['Continue the service quickly', 'Stop service and put on gloves', 'Apply more lather', 'Wipe with a dry towel'], answerIndex: 1, rationale: 'Service stops immediately. Gloves go on before any contact with blood.' },
        { prompt: 'Which item must be discarded after one use?', choices: ['Metal clipper guard', 'Neck strip', 'Straight razor handle', 'Barber comb'], answerIndex: 1, rationale: 'Neck strips are single-use and must be discarded after every client.' },
        { prompt: 'How often must disinfectant solution be changed at minimum?', choices: ['Once a week', 'Every 24 hours or sooner if contaminated', 'Once a month', 'Only when it looks dirty'], answerIndex: 1, rationale: 'Fresh solution is required to maintain effectiveness.' },
        { prompt: 'Which agency regulates barbers in Indiana?', choices: ['OSHA', 'NIC', 'IPLA', 'DOL'], answerIndex: 2, rationale: 'The Indiana Professional Licensing Agency (IPLA) regulates barbers under IC 25-8.' },
        { prompt: 'What does contact time mean in disinfection?', choices: ['How long the service takes', 'How long the disinfectant must stay wet on the surface', 'How long tools are stored', 'How long the client waits'], answerIndex: 1, rationale: 'Contact time is the required dwell time for the disinfectant to be effective.' },
      ],
    },
  },
};
