import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/admin-login',
          '/api/',
          '/staff-portal/',
          '/program-holder/',
          '/workforce-board/',
          '/instructor/',
          '/creator/',
          '/employee/',
          '/shop/',
          '/lms/(app)/',
          '/programs/admin/',
          '/employer/dashboard',
          '/employer/analytics',
          '/employer/candidates',
          '/employer/compliance',
          '/employer/documents',
          '/employer/jobs',
          '/employer/opportunities',
          '/employer/placements',
          '/employer/postings',
          '/employer/reports',
          '/employer/settings',
          '/employer/verification',
          '/checkout/',
          '/payment/',
          '/reset/',
          '/verify-email',
          '/verify-identity',
          '/usermanagement',
          '/approvals',
          '/messages',
          '/chat',
          '/cm',
          '/analytics',
          '/reports',
          '/metrics',
          '/leaderboard',
          '/file-manager',
          '/curriculumupload',
          '/documents/upload',
          '/auth/',
          '/_next/',
          '/test-images',
          '/cache-diagnostic',
          '/sentry-test',
        ],
      },
    ],
    sitemap: 'https://www.elevateforhumanity.org/sitemap.xml',
  };
}
