/**
 * Per-module quiz question banks for the HVAC Technician course.
 * Each key matches a module ID (hvac-01 through hvac-16).
 * Questions align with that module's competency objectives.
 */

export interface HVACQuizQuestion {
  question: string;
  options: string[];
  answer: number;
  explanation: string;
}

export const HVAC_QUIZ_BANKS: Record<string, HVACQuizQuestion[]> = {
  'hvac-01': [
    { question: 'How many credentials does this program award?', options: ['1', '2', '3 (EPA 608, OSHA 30, CPR/AED)', '5'], answer: 2, explanation: 'The program awards EPA 608 Universal, OSHA 30-Hour Construction Safety, and CPR/AED certification.' },
    { question: 'What is the minimum attendance requirement for WIOA-funded students?', options: ['50%', '70%', '80%', '100%'], answer: 2, explanation: 'WIOA funding requires 80% minimum attendance. Missing more may jeopardize funding.' },
    { question: 'What is the first level of the HVAC career pathway?', options: ['Journeyman', 'Master Technician', 'Apprentice', 'Contractor'], answer: 2, explanation: 'The pathway is Apprentice → Journeyman → Master Technician → Contractor.' },
    { question: 'How long is this HVAC training program?', options: ['4 weeks', '8 weeks', '12 weeks', '24 weeks'], answer: 2, explanation: 'The program is a 12-week workforce pathway.' },
    { question: 'Which federal law requires EPA 608 certification to handle refrigerants?', options: ['OSHA Act', 'Clean Air Act Section 608', 'WIOA', 'ADA'], answer: 1, explanation: 'The Clean Air Act Section 608 requires certification for anyone purchasing or handling refrigerants.' },
    { question: 'What credential is required before you can legally purchase refrigerant?', options: ['OSHA 30', 'EPA 608', 'NATE Core', 'State HVAC license'], answer: 1, explanation: 'EPA 608 certification is the federal requirement for purchasing and handling refrigerants.' },
    { question: 'How many OJT hours are typically needed to reach Journeyman level?', options: ['480', '1,000', '2,000+', '4,000+'], answer: 2, explanation: 'Journeyman level typically requires 2,000+ on-the-job training hours plus passing the state exam.' },
    { question: 'What support services are available to WIOA-funded students?', options: ['Tuition only', 'Tuition and books only', 'Tuition, transportation, childcare, and tools', 'None'], answer: 2, explanation: 'WIOA supportive services can include tuition, transportation, childcare, tools, and work clothing.' },
    { question: 'What does ETPL stand for?', options: ['Emergency Training Program List', 'Eligible Training Provider List', 'Entry-level Technician Program License', 'EPA Training Provider License'], answer: 1, explanation: 'ETPL is the Eligible Training Provider List — programs must be listed for WIOA funding eligibility.' },
    { question: 'Which modality does this program use?', options: ['Fully online', 'Fully in-person', 'Hybrid (online + hands-on)', 'Self-paced only'], answer: 2, explanation: 'The program uses a hybrid modality combining online learning with hands-on lab work.' },
  ],

  'hvac-02': [
    { question: 'What are the five major components of a split AC system?', options: ['Compressor, condenser, evaporator, metering device, air handler', 'Furnace, thermostat, ductwork, filter, blower', 'Compressor, fan, filter, thermostat, ductwork', 'Heat exchanger, burner, flue, blower, filter'], answer: 0, explanation: 'A split system has a compressor, condenser coil, evaporator coil, metering device, and air handler.' },
    { question: 'What is the purpose of lockout/tagout (LOTO)?', options: ['To lock the thermostat', 'To prevent accidental energization during service', 'To lock refrigerant valves', 'To tag equipment for warranty'], answer: 1, explanation: 'LOTO prevents unexpected startup of equipment during maintenance, protecting the technician.' },
    { question: 'What does a gauge manifold measure?', options: ['Temperature only', 'Airflow only', 'Suction and discharge pressure', 'Voltage and amperage'], answer: 2, explanation: 'A gauge manifold measures low-side (suction) and high-side (discharge) refrigerant pressures.' },
    { question: 'What PPE is required when handling refrigerants?', options: ['Hard hat only', 'Safety glasses and gloves', 'Steel-toe boots only', 'No PPE needed'], answer: 1, explanation: 'Safety glasses and gloves protect against frostbite and eye injury from liquid refrigerant contact.' },
    { question: 'In a cooling cycle, where does heat rejection occur?', options: ['Evaporator', 'Compressor', 'Condenser', 'Metering device'], answer: 2, explanation: 'The condenser rejects heat from the refrigerant to the outdoor air.' },
    { question: 'What tool measures vacuum level during evacuation?', options: ['Gauge manifold', 'Micron gauge', 'Amp clamp', 'Thermometer'], answer: 1, explanation: 'A micron gauge measures deep vacuum levels (below atmospheric) during system evacuation.' },
    { question: 'What is the function of the evaporator coil?', options: ['Rejects heat outdoors', 'Compresses refrigerant', 'Absorbs heat from indoor air', 'Controls refrigerant flow'], answer: 2, explanation: 'The evaporator absorbs heat from indoor air, cooling the space.' },
    { question: 'What should you verify AFTER pulling the disconnect?', options: ['Thermostat is off', 'Filter is clean', '0 volts with a meter', 'Refrigerant pressure'], answer: 2, explanation: 'Always verify 0 volts with a multimeter after pulling the disconnect — never trust the switch alone.' },
    { question: 'What is a vacuum pump used for?', options: ['Pumping refrigerant into cylinders', 'Removing moisture and air from the system', 'Measuring airflow', 'Testing gas valves'], answer: 1, explanation: 'A vacuum pump removes moisture and non-condensable gases before charging a system.' },
    { question: 'Which component changes refrigerant from liquid to low-pressure mix?', options: ['Compressor', 'Condenser', 'Evaporator', 'Metering device (TXV/piston)'], answer: 3, explanation: 'The metering device creates a pressure drop, converting high-pressure liquid into a low-pressure mixture.' },
  ],

  'hvac-03': [
    { question: 'Ohm\'s Law states that voltage equals:', options: ['Current × Resistance', 'Current ÷ Resistance', 'Resistance ÷ Current', 'Power × Current'], answer: 0, explanation: 'V = I × R. Voltage equals current multiplied by resistance.' },
    { question: 'A contactor is stuck closed. What happens?', options: ['System won\'t run', 'Compressor runs continuously', 'Thermostat fails', 'Fuse blows immediately'], answer: 1, explanation: 'A stuck-closed contactor keeps the circuit energized — the compressor runs regardless of thermostat demand.' },
    { question: 'What does a capacitor do in an HVAC system?', options: ['Regulates voltage', 'Stores and releases energy to start/run motors', 'Measures amperage', 'Controls refrigerant flow'], answer: 1, explanation: 'Capacitors store electrical energy and release it to help start and run compressor and fan motors.' },
    { question: 'A run capacitor reads 5 µF but is rated 45 µF. What\'s the diagnosis?', options: ['Normal — within tolerance', 'Failed capacitor — replace it', 'Overcharged capacitor', 'Wrong meter setting'], answer: 1, explanation: 'A capacitor reading far below its rated value has failed and must be replaced. Tolerance is ±6%.' },
    { question: 'What does a ladder diagram show?', options: ['Physical wire routing', 'Electrical sequence of operation', 'Duct layout', 'Refrigerant piping'], answer: 1, explanation: 'Ladder diagrams show the electrical sequence — which switches/controls energize which loads.' },
    { question: 'How do you safely measure amperage on a wire?', options: ['Touch probes to bare wire', 'Use an amp clamp around the wire', 'Disconnect the wire first', 'Set meter to voltage mode'], answer: 1, explanation: 'An amp clamp measures current by clamping around an insulated wire — no contact with bare conductors.' },
    { question: 'What is the unit of electrical resistance?', options: ['Amps', 'Volts', 'Ohms', 'Watts'], answer: 2, explanation: 'Resistance is measured in ohms (Ω).' },
    { question: 'A relay differs from a contactor because:', options: ['Relays handle higher current', 'Contactors handle higher current', 'They are identical', 'Relays use refrigerant'], answer: 1, explanation: 'Contactors handle higher current loads (compressors). Relays handle lower current control circuits.' },
    { question: 'What happens if you measure voltage with the meter set to amps?', options: ['Nothing', 'Accurate reading', 'Blown fuse in the meter or damage', 'Low reading'], answer: 2, explanation: 'Measuring voltage in amp mode creates a short through the meter — blowing the internal fuse or damaging it.' },
    { question: 'A 240V circuit has 10 amps flowing. What is the resistance?', options: ['2,400 ohms', '24 ohms', '2.4 ohms', '240 ohms'], answer: 1, explanation: 'R = V/I = 240/10 = 24 ohms.' },
  ],

  'hvac-04': [
    { question: 'What ignition type uses a silicon nitride element that glows red-hot?', options: ['Standing pilot', 'Hot surface igniter (HSI)', 'Direct spark ignition (DSI)', 'Electronic pilot'], answer: 1, explanation: 'HSI uses a silicon nitride or silicon carbide element that glows to ignite gas — most common in modern furnaces.' },
    { question: 'Normal temperature rise for a gas furnace is typically:', options: ['10-20°F', '30-60°F', '80-100°F', '100-140°F'], answer: 1, explanation: 'Most furnaces specify 30-60°F temperature rise. Check the nameplate for the specific range.' },
    { question: 'What does a flame sensor do?', options: ['Ignites the gas', 'Proves flame is present — shuts gas if no flame detected', 'Measures gas pressure', 'Controls blower speed'], answer: 1, explanation: 'The flame sensor proves flame exists. If it can\'t sense flame within a few seconds, the gas valve closes.' },
    { question: 'CO in flue gas above what level is dangerous?', options: ['10 ppm', '50 ppm', '100 ppm', '400 ppm'], answer: 2, explanation: 'CO above 100 ppm in undiluted flue gas indicates a combustion problem requiring immediate attention.' },
    { question: 'What is the purpose of a heat exchanger?', options: ['Mix combustion gases with room air', 'Transfer heat from combustion to room air without mixing gases', 'Store heat for later use', 'Regulate gas flow'], answer: 1, explanation: 'The heat exchanger transfers heat from combustion gases to room air while keeping them separated.' },
    { question: 'A cracked heat exchanger is dangerous because:', options: ['It wastes energy', 'CO can enter the living space', 'It makes noise', 'The blower runs too fast'], answer: 1, explanation: 'A cracked heat exchanger can leak carbon monoxide into the conditioned air — a life-threatening hazard.' },
    { question: 'What does the reversing valve do in a heat pump?', options: ['Reverses the blower direction', 'Switches between heating and cooling mode', 'Reverses the thermostat wiring', 'Controls defrost timing'], answer: 1, explanation: 'The reversing valve changes refrigerant flow direction, switching the system between heating and cooling.' },
    { question: 'When does a heat pump defrost cycle activate?', options: ['Every 30 minutes', 'When outdoor coil ices up — based on time/temperature or pressure', 'Only manually', 'When indoor temp drops'], answer: 1, explanation: 'Defrost activates when sensors detect ice buildup on the outdoor coil, typically using time/temperature or pressure differential.' },
    { question: 'What is auxiliary heat in a heat pump system?', options: ['Solar panels', 'Electric heat strips that supplement when heat pump can\'t keep up', 'A second heat pump', 'Gas backup furnace only'], answer: 1, explanation: 'Auxiliary (aux) heat is typically electric heat strips that activate when the heat pump alone can\'t maintain setpoint.' },
    { question: 'What should you check first on a no-heat gas furnace call?', options: ['Gas pressure', 'Thermostat settings and power', 'Heat exchanger', 'Ductwork'], answer: 1, explanation: 'Start simple — verify thermostat is set to heat, temperature is set above room temp, and furnace has power.' },
  ],

  'hvac-05': [
    { question: 'What does the compressor do in a refrigeration cycle?', options: ['Cools the air directly', 'Compresses low-pressure gas into high-pressure gas', 'Filters contaminants from refrigerant', 'Regulates airflow through ductwork'], answer: 1, explanation: 'The compressor takes low-pressure vapor from the evaporator and compresses it into high-pressure, high-temperature gas that flows to the condenser.' },
    { question: 'What is superheat a measurement of?', options: ['Temperature above the boiling point of the refrigerant', 'Temperature of the air leaving the supply register', 'Pressure difference between suction and discharge', 'Ambient temperature minus return air temperature'], answer: 0, explanation: 'Superheat measures how many degrees the refrigerant vapor has been heated above its boiling point at the current pressure.' },
    { question: 'Normal suction pressure for R-410A residential cooling is approximately:', options: ['30-50 psig', '58-80 psig', '118-150 psig', '200-250 psig'], answer: 2, explanation: 'R-410A operates at higher pressures than R-22. Normal suction pressure is approximately 118-150 psig at typical cooling conditions.' },
    { question: 'What is the purpose of the metering device (TXV or piston)?', options: ['Compress refrigerant to high pressure', 'Remove moisture from the refrigerant', 'Reduce pressure and control flow into the evaporator', 'Measure airflow across the coil'], answer: 2, explanation: 'The metering device creates a pressure drop that converts high-pressure liquid into a low-pressure mix entering the evaporator.' },
    { question: 'Subcooling of 22°F (normal 8-14°F) most likely indicates:', options: ['Low refrigerant charge', 'Overcharged system', 'Restricted metering device', 'Dirty evaporator coil'], answer: 1, explanation: 'Very high subcooling means excess liquid refrigerant is stacking up in the condenser — the system has too much charge.' },
    { question: 'What are the four stages of the refrigeration cycle in order?', options: ['Evaporation, compression, condensation, expansion', 'Compression, condensation, expansion, evaporation', 'Condensation, expansion, evaporation, compression', 'Expansion, evaporation, compression, condensation'], answer: 1, explanation: 'The cycle: compressor compresses gas → condenser rejects heat → metering device expands → evaporator absorbs heat.' },
    { question: 'A scroll compressor differs from a reciprocating compressor because:', options: ['It uses pistons', 'It uses two spiral-shaped scrolls', 'It only works with R-22', 'It runs on DC power'], answer: 1, explanation: 'Scroll compressors use two interlocking spiral scrolls — one fixed, one orbiting — to compress refrigerant.' },
    { question: 'What does a TXV sense to control refrigerant flow?', options: ['Discharge pressure', 'Suction line superheat', 'Ambient temperature', 'Liquid line temperature'], answer: 1, explanation: 'A TXV has a sensing bulb on the suction line that adjusts flow based on superheat — maintaining proper evaporator performance.' },
    { question: 'Low superheat indicates:', options: ['Not enough refrigerant reaching the evaporator', 'Too much refrigerant reaching the evaporator (flood-back risk)', 'Normal operation', 'High ambient temperature'], answer: 1, explanation: 'Low superheat means liquid refrigerant may be leaving the evaporator — risking liquid flood-back to the compressor.' },
    { question: 'What tool do you use to look up saturation temperature from pressure?', options: ['Ohm\'s Law chart', 'PT (pressure-temperature) chart', 'Psychrometric chart', 'Duct calculator'], answer: 1, explanation: 'A PT chart converts between pressure and saturation temperature for each refrigerant type.' },
  ],

  'hvac-06': [
    { question: 'What depletes the ozone layer?', options: ['HFCs', 'CFCs and HCFCs', 'Nitrogen', 'Carbon dioxide'], answer: 1, explanation: 'CFCs (like R-12) and HCFCs (like R-22) contain chlorine that destroys ozone molecules.' },
    { question: 'What is the maximum fine for knowingly venting refrigerant?', options: ['$1,000', '$10,000', '$44,539 per day per violation', '$100'], answer: 2, explanation: 'Under the Clean Air Act, knowingly venting refrigerant can result in fines up to $44,539 per day per violation.' },
    { question: 'What is the difference between recovery and recycling?', options: ['They are the same thing', 'Recovery removes refrigerant; recycling cleans it for reuse', 'Recycling removes refrigerant; recovery cleans it', 'Neither involves refrigerant'], answer: 1, explanation: 'Recovery = removing refrigerant from a system. Recycling = cleaning recovered refrigerant (oil/moisture removal) for reuse.' },
    { question: 'R-410A is classified as:', options: ['CFC', 'HCFC', 'HFC', 'HFO'], answer: 2, explanation: 'R-410A is an HFC (hydrofluorocarbon) — no chlorine, zero ODP, but has high GWP.' },
    { question: 'When must refrigerant be recovered before opening a system?', options: ['Only for CFC systems', 'Only for systems over 50 lbs', 'Always — before any service that opens the system', 'Never — it can be vented'], answer: 2, explanation: 'Federal law requires recovery before any service that opens the refrigerant circuit, regardless of refrigerant type.' },
    { question: 'What does ODP stand for?', options: ['Outdoor Design Pressure', 'Ozone Depletion Potential', 'Operating Discharge Pressure', 'Optimal Design Parameter'], answer: 1, explanation: 'ODP = Ozone Depletion Potential. R-12 has ODP of 1.0 (reference). R-410A has ODP of 0.' },
    { question: 'Who can purchase refrigerant?', options: ['Anyone', 'Only EPA 608 certified technicians', 'Only contractors', 'Only wholesalers'], answer: 1, explanation: 'Since January 2018, only EPA 608 certified technicians can purchase refrigerant (including HFCs).' },
    { question: 'What is reclamation?', options: ['Reusing refrigerant on-site', 'Processing refrigerant to ARI 700 purity standards at a certified facility', 'Venting refrigerant safely', 'Mixing refrigerant types'], answer: 1, explanation: 'Reclamation processes refrigerant at a certified facility to meet ARI 700 purity standards — essentially like-new quality.' },
    { question: 'Refrigerant cylinders should be stored:', options: ['On their side', 'Upright, in a cool ventilated area, away from heat', 'In direct sunlight', 'In a sealed room'], answer: 1, explanation: 'Store cylinders upright, in cool ventilated areas. Heat increases pressure and can cause rupture.' },
    { question: 'What color is an R-410A cylinder?', options: ['Green', 'Light blue/pink (rose)', 'Yellow', 'White'], answer: 1, explanation: 'R-410A cylinders are rose/pink colored. R-22 is green. R-134a is light blue.' },
  ],

  'hvac-07': [
    { question: 'What defines a "small appliance" under EPA 608 Type I?', options: ['Any system under 50 lbs of refrigerant', 'Factory-charged systems with 5 lbs or less of refrigerant', 'Any window AC unit', 'Systems using R-410A only'], answer: 1, explanation: 'Type I covers factory-charged systems containing 5 lbs or less of refrigerant — window units, PTACs, household refrigerators, vending machines.' },
    { question: 'What is the required recovery efficiency for an operating small appliance?', options: ['80%', '90%', '95%', '100%'], answer: 1, explanation: '90% recovery is required for small appliances with an operating charge. 80% for non-operating systems.' },
    { question: 'When can you vent refrigerant from a small appliance?', options: ['Never — venting is always illegal', 'When the system has less than 1 lb', 'Only nitrogen used for leak testing', 'When recycling equipment is unavailable'], answer: 0, explanation: 'Venting is prohibited under the Clean Air Act regardless of system size or refrigerant type.' },
    { question: 'What type of recovery equipment is used for small appliances?', options: ['Only self-contained', 'Only system-dependent', 'Either self-contained or system-dependent', 'No recovery equipment needed'], answer: 2, explanation: 'Both self-contained and system-dependent recovery equipment can be used for small appliances.' },
    { question: 'System-dependent recovery relies on what to push refrigerant out?', options: ['An external compressor', 'The system\'s own compressor or pressure', 'Gravity only', 'Nitrogen pressure'], answer: 1, explanation: 'System-dependent recovery uses the appliance\'s own compressor or internal pressure to move refrigerant into the recovery vessel.' },
    { question: 'What is the recovery requirement for a non-operating small appliance?', options: ['90%', '80%', '70%', '0% — exempt'], answer: 1, explanation: '80% recovery for non-operating small appliances. If the compressor does not work, you cannot achieve 90%.' },
    { question: 'Are small appliances exempt from leak repair requirements?', options: ['No — same rules as all systems', 'Yes — small appliances are exempt from leak repair rules', 'Only if under 2 lbs', 'Only CFC systems are exempt'], answer: 1, explanation: 'Small appliances are exempt from the mandatory leak repair requirements that apply to larger systems.' },
    { question: 'What must you do before disposing of a small appliance?', options: ['Nothing special', 'Recover the refrigerant', 'Drain the oil only', 'Remove the compressor'], answer: 1, explanation: 'Refrigerant must be recovered before disposing of any appliance. This applies to scrap dealers and recyclers too.' },
    { question: 'A PTAC unit contains 3 lbs of R-410A. What EPA 608 type covers this?', options: ['Type I', 'Type II', 'Type III', 'Universal only'], answer: 0, explanation: 'PTACs with 5 lbs or less are small appliances covered under Type I.' },
    { question: 'When using system-dependent recovery, where does the refrigerant go?', options: ['Into the atmosphere', 'Into an approved recovery cylinder', 'Back into the system', 'Into a nitrogen tank'], answer: 1, explanation: 'Recovered refrigerant must go into an approved DOT recovery cylinder — never vented.' },
  ],

  'hvac-08': [
    { question: 'What is the required recovery level for a high-pressure system under 200 lbs?', options: ['0 psig', '10 inches Hg vacuum', '25 mm Hg absolute', '90% of charge'], answer: 0, explanation: 'For high-pressure systems under 200 lbs, recover to 0 psig (atmospheric pressure).' },
    { question: 'What is the required recovery level for a high-pressure system over 200 lbs?', options: ['0 psig', '10 inches Hg vacuum', '25 mm Hg absolute', '90% of charge'], answer: 1, explanation: 'For high-pressure systems 200 lbs or more, recover to 10 inches Hg vacuum.' },
    { question: 'What is the leak repair trigger rate for comfort cooling equipment?', options: ['5%', '10%', '20%', '35%'], answer: 1, explanation: 'Comfort cooling systems (residential/commercial AC) must be repaired if the annual leak rate exceeds 10%.' },
    { question: 'What is the leak repair trigger rate for commercial refrigeration?', options: ['5%', '10%', '20%', '35%'], answer: 2, explanation: 'Commercial refrigeration and industrial process systems must be repaired if the annual leak rate exceeds 20%.' },
    { question: 'What vacuum level indicates a properly evacuated system?', options: ['0 psig', '29 inches Hg', '500 microns or below', '1000 microns'], answer: 2, explanation: '500 microns or below indicates proper dehydration. The system should hold below 1000 microns for 10 minutes.' },
    { question: 'Why do you pull a vacuum on a system?', options: ['To check for leaks only', 'To remove moisture and non-condensable gases', 'To add refrigerant faster', 'To test the compressor'], answer: 1, explanation: 'Evacuation removes moisture (which causes acid) and non-condensable gases (which raise head pressure).' },
    { question: 'What tool measures deep vacuum levels?', options: ['Compound gauge', 'Micron gauge', 'Manometer', 'Psychrometer'], answer: 1, explanation: 'A micron gauge measures vacuum levels below atmospheric — compound gauges are not accurate enough for evacuation verification.' },
    { question: 'Triple evacuation involves:', options: ['Three vacuum pumps', 'Pulling vacuum, breaking with nitrogen, repeating three times', 'Three pressure tests', 'Three leak checks'], answer: 1, explanation: 'Triple evacuation: pull vacuum, break with dry nitrogen, pull vacuum, break with nitrogen, pull final vacuum. Nitrogen sweeps help remove moisture.' },
    { question: 'What happens if moisture is left in a refrigerant system?', options: ['Nothing — moisture evaporates', 'It forms acid that damages compressor windings and valves', 'It improves lubrication', 'It lowers discharge pressure'], answer: 1, explanation: 'Moisture combines with refrigerant and oil to form hydrofluoric and hydrochloric acid, which destroys compressor windings, valves, and bearings.' },
    { question: 'R-410A operates at approximately what suction pressure in cooling?', options: ['30-50 psig', '68-80 psig', '118-150 psig', '200-250 psig'], answer: 2, explanation: 'R-410A operates at higher pressures than R-22. Normal suction is approximately 118-150 psig at typical residential cooling conditions.' },
  ],

  'hvac-09': [
    { question: 'What type of systems does EPA 608 Type III cover?', options: ['Small appliances', 'High-pressure AC systems', 'Low-pressure systems (chillers)', 'Automotive AC'], answer: 2, explanation: 'Type III covers low-pressure systems — primarily centrifugal chillers using R-11, R-123, or similar low-pressure refrigerants.' },
    { question: 'Why do low-pressure systems operate below atmospheric pressure?', options: ['To save energy', 'Because their refrigerants boil at temperatures above typical conditions at atmospheric pressure', 'To prevent leaks', 'Because of EPA regulations'], answer: 1, explanation: 'Low-pressure refrigerants like R-11 boil at 74.7°F at atmospheric pressure — above typical chilled water temps. The system must operate in a vacuum to keep refrigerant liquid.' },
    { question: 'What is the function of a purge unit on a low-pressure chiller?', options: ['Adds refrigerant', 'Removes air and non-condensables that leak INTO the system', 'Cools the condenser', 'Measures refrigerant level'], answer: 1, explanation: 'Since low-pressure systems operate below atmospheric pressure, air leaks IN (not out). The purge unit removes this air and non-condensable gases.' },
    { question: 'Recovery requirement for a low-pressure system under 200 lbs:', options: ['0 psig', '10 inches Hg vacuum', '25 mm Hg absolute', '25 inches Hg vacuum'], answer: 0, explanation: 'Low-pressure systems under 200 lbs: recover to 0 psig.' },
    { question: 'Recovery requirement for a low-pressure system 200 lbs or more:', options: ['0 psig', '10 inches Hg vacuum', '25 mm Hg absolute', '29 inches Hg vacuum'], answer: 2, explanation: 'Low-pressure systems 200 lbs or more: recover to 25 mm Hg absolute.' },
    { question: 'What is the biggest risk when evacuating a low-pressure chiller?', options: ['Explosion', 'Freezing the water in the tubes, rupturing them', 'Compressor damage', 'Refrigerant contamination'], answer: 1, explanation: 'If you pull too deep a vacuum on a chiller with water still in the tubes, the water can freeze and rupture the tubes — a very expensive repair.' },
    { question: 'What causes hydrolysis in a low-pressure system?', options: ['High pressure', 'Water reacting with refrigerant to form acid', 'Oil breakdown', 'Electrical arcing'], answer: 1, explanation: 'Hydrolysis occurs when water reacts with refrigerant, forming hydrochloric or hydrofluoric acid that damages the system.' },
    { question: 'A rupture disc on a low-pressure chiller:', options: ['Regulates refrigerant flow', 'Relieves pressure if it exceeds safe limits', 'Measures vacuum level', 'Controls the purge unit'], answer: 1, explanation: 'Rupture discs are safety devices that burst to relieve pressure if the system exceeds safe limits — preventing catastrophic vessel failure.' },
    { question: 'What refrigerant is commonly used in centrifugal chillers?', options: ['R-410A', 'R-22', 'R-123', 'R-134a'], answer: 2, explanation: 'R-123 (an HCFC) is commonly used in low-pressure centrifugal chillers. It replaced R-11 (a CFC).' },
    { question: 'High purge unit run time on a chiller indicates:', options: ['Normal operation', 'Excessive air leaks into the system', 'Low refrigerant charge', 'High cooling load'], answer: 1, explanation: 'If the purge unit runs frequently, it means air is leaking into the system at a high rate — find and fix the leaks.' },
  ],

  'hvac-10': [
    { question: 'How many sections are on the EPA 608 Universal exam?', options: ['2', '3', '4 (Core, Type I, Type II, Type III)', '5'], answer: 2, explanation: 'The Universal exam has 4 sections: Core (25 questions), Type I (25), Type II (25), and Type III (25) — 100 questions total.' },
    { question: 'What is the passing score for each EPA 608 section?', options: ['50%', '60%', '70%', '80%'], answer: 2, explanation: 'You must score 70% or higher on EACH section independently. Passing Core + all three types = Universal certification.' },
    { question: 'If you pass Core, Type I, and Type II but fail Type III, what certification do you receive?', options: ['None — must pass all', 'Type I and Type II only', 'Universal with a Type III waiver', 'Core only'], answer: 1, explanation: 'You receive certification for each section you pass. Failing Type III means you get Type I and Type II but not Universal.' },
    { question: 'EPA 608 certification is valid for:', options: ['1 year', '2 years', '5 years', 'Lifetime — never expires'], answer: 3, explanation: 'EPA 608 certification never expires once earned. However, technicians must stay current with regulation changes.' },
    { question: 'The maximum fine for knowingly venting refrigerant is:', options: ['$5,000', '$10,000', '$27,500 per day', '$44,539 per day per violation'], answer: 3, explanation: 'Under the Clean Air Act, knowingly venting refrigerant can result in fines up to $44,539 per day per violation.' },
    { question: 'Who can purchase refrigerant?', options: ['Anyone over 18', 'Only licensed contractors', 'Only EPA 608 certified technicians', 'Anyone with a business license'], answer: 2, explanation: 'Since January 2018, only EPA 608 certified technicians can purchase refrigerant, including HFCs like R-410A.' },
    { question: 'What is the difference between recovery and recycling?', options: ['They are the same', 'Recovery removes refrigerant; recycling cleans it for reuse', 'Recycling is illegal', 'Recovery is only for CFCs'], answer: 1, explanation: 'Recovery = removing refrigerant from a system. Recycling = cleaning recovered refrigerant (removing oil and moisture) for reuse.' },
    { question: 'Reclamation means:', options: ['Reusing refrigerant on-site', 'Processing refrigerant to ARI 700 purity at a certified facility', 'Venting small amounts legally', 'Mixing compatible refrigerants'], answer: 1, explanation: 'Reclamation processes refrigerant at a certified facility to meet ARI 700 purity standards — essentially like-new quality.' },
    { question: 'Which refrigerant type has the highest ozone depletion potential?', options: ['HFC', 'HCFC', 'CFC', 'HFO'], answer: 2, explanation: 'CFCs (like R-12) have the highest ODP because they contain the most chlorine. HCFCs are lower, HFCs have zero ODP.' },
    { question: 'What should you do if you discover a coworker venting refrigerant?', options: ['Nothing — not your problem', 'Report it to the EPA', 'Help them do it faster', 'Only report if it is a CFC'], answer: 1, explanation: 'Knowingly venting any refrigerant is illegal. You should report violations to the EPA. Whistleblower protections apply.' },
  ],

  'hvac-11': [
    { question: 'What charging method uses liquid line temperature and pressure to determine correct charge?', options: ['Superheat method', 'Subcooling method', 'Weigh-in method', 'Approach method'], answer: 1, explanation: 'The subcooling method measures liquid line pressure and temperature. Subcooling = saturation temp minus actual liquid line temp. Target is typically 10-15°F.' },
    { question: 'High superheat and low subcooling together indicate:', options: ['Overcharge', 'Undercharge', 'Restriction', 'Normal operation'], answer: 1, explanation: 'High superheat (not enough liquid reaching evaporator) + low subcooling (not enough liquid stacking in condenser) = system is low on refrigerant.' },
    { question: 'Low superheat and high subcooling together indicate:', options: ['Undercharge', 'Overcharge', 'Dirty filter', 'Bad TXV'], answer: 1, explanation: 'Low superheat (too much liquid in evaporator) + high subcooling (excess liquid in condenser) = system has too much refrigerant.' },
    { question: 'What is the correct procedure after finding a refrigerant leak?', options: ['Add refrigerant and monitor', 'Repair the leak, recover, evacuate, then recharge', 'Replace the entire system', 'Seal the leak with epoxy'], answer: 1, explanation: 'The correct procedure: repair the leak, recover remaining refrigerant, evacuate to 500 microns, then recharge to manufacturer specification.' },
    { question: 'Normal subcooling for a system with a TXV is typically:', options: ['0-5°F', '8-14°F', '20-30°F', '35-45°F'], answer: 1, explanation: 'Most manufacturers specify 8-14°F subcooling for TXV systems. Always check the specific manufacturer data plate.' },
    { question: 'What does a nitrogen pressure test verify?', options: ['Refrigerant charge level', 'System holds pressure without leaking', 'Compressor operation', 'Airflow volume'], answer: 1, explanation: 'A nitrogen pressure test pressurizes the system to 150+ psig with dry nitrogen to verify there are no leaks before evacuation and charging.' },
    { question: 'Non-condensable gases in a system cause:', options: ['Low head pressure', 'High head pressure and reduced efficiency', 'Low suction pressure', 'No effect'], answer: 1, explanation: 'Non-condensable gases (air, nitrogen) take up space in the condenser, raising head pressure and reducing cooling capacity.' },
    { question: 'What is the weigh-in charging method?', options: ['Measuring superheat while adding charge', 'Adding the exact nameplate charge by weight using a scale', 'Charging until subcooling is correct', 'Charging until the sight glass clears'], answer: 1, explanation: 'Weigh-in: evacuate the system completely, then add the exact charge amount listed on the nameplate using a refrigerant scale.' },
    { question: 'An electronic leak detector should be calibrated:', options: ['Never — factory calibrated', 'Before each use', 'Once a year', 'Only when batteries are replaced'], answer: 1, explanation: 'Calibrate the leak detector before each use to ensure it can detect the minimum leak rate. Most detectors have a reference leak for calibration.' },
    { question: 'What causes liquid slugging in a compressor?', options: ['Low superheat — liquid refrigerant reaches the compressor', 'High superheat', 'Dirty condenser', 'Low ambient temperature only'], answer: 0, explanation: 'Liquid slugging occurs when liquid refrigerant enters the compressor. Compressors are designed to compress vapor, not liquid. Liquid is incompressible and can break valves and rods.' },
  ],

  'hvac-12': [
    { question: 'What is total external static pressure (TESP)?', options: ['Pressure inside the refrigerant lines', 'The resistance to airflow the blower must overcome in the duct system', 'The pressure at the condenser', 'Atmospheric pressure'], answer: 1, explanation: 'TESP is the total resistance to airflow in the duct system — measured as the sum of supply static and return static pressure.' },
    { question: 'Maximum recommended TESP for most residential systems is:', options: ['0.10 in. w.c.', '0.25 in. w.c.', '0.50 in. w.c.', '1.00 in. w.c.'], answer: 2, explanation: 'Most residential equipment is rated for a maximum of 0.50 inches of water column total external static pressure.' },
    { question: 'What is the purpose of a nitrogen purge during brazing?', options: ['To cool the joint', 'To prevent oxide formation inside the tubing', 'To test for leaks', 'To add pressure'], answer: 1, explanation: 'Flowing nitrogen through the tubing during brazing prevents copper oxide (black flake) from forming inside. Oxide contaminates the system and can clog metering devices.' },
    { question: 'A flare connection that leaks most likely has:', options: ['Too much torque', 'A cracked flare, improper flare angle, or debris on the seat', 'Too much refrigerant', 'A bad valve core'], answer: 1, explanation: 'Flare leaks are caused by cracked flares, wrong flare angle (45° for HVAC), overtightening, or debris between the flare and seat.' },
    { question: 'What is the normal temperature split (supply minus return) for cooling?', options: ['5-10°F', '14-22°F', '30-40°F', '40-60°F'], answer: 1, explanation: 'Normal cooling temperature split is 14-22°F. Below 14°F suggests low airflow or low charge. Above 22°F suggests restricted airflow.' },
    { question: 'Manual J is used to determine:', options: ['Duct size', 'Equipment size based on heat load calculation', 'Refrigerant charge', 'Wire size'], answer: 1, explanation: 'Manual J calculates the heating and cooling load of a building to determine the correct equipment size. Oversized or undersized equipment causes comfort and efficiency problems.' },
    { question: 'What happens if you braze without a nitrogen purge?', options: ['Nothing — nitrogen is optional', 'Copper oxide forms inside the tubing and contaminates the system', 'The joint will be stronger', 'The refrigerant will leak'], answer: 1, explanation: 'Without nitrogen purge, the heat from brazing causes copper oxide (black scale) to form inside the tubing. This contaminates the system and can clog TXVs and filter driers.' },
    { question: 'A system commissioning checklist should verify:', options: ['Only refrigerant charge', 'Charge, airflow, temperature split, electrical, and safety controls', 'Only that the system turns on', 'Only duct connections'], answer: 1, explanation: 'Commissioning verifies everything: refrigerant charge (superheat/subcooling), airflow (static pressure), temperature split, electrical (amp draw), and all safety controls.' },
    { question: 'What tool measures static pressure in ductwork?', options: ['Thermometer', 'Manometer', 'Micron gauge', 'Amp clamp'], answer: 1, explanation: 'A manometer (or digital pressure meter) measures static pressure in inches of water column (in. w.c.).' },
    { question: 'The suction line is the:', options: ['Small uninsulated copper line', 'Large insulated copper line carrying cold vapor back to the compressor', 'Condensate drain line', 'Gas supply line'], answer: 1, explanation: 'The suction line is the larger of the two refrigerant lines, insulated because it carries cold low-pressure vapor from the evaporator back to the compressor.' },
  ],

  'hvac-13': [
    { question: 'What is the first step in any HVAC troubleshooting call?', options: ['Connect gauges', 'Replace the capacitor', 'Verify thermostat settings and check for power', 'Check refrigerant charge'], answer: 2, explanation: 'Always start simple: verify the thermostat is set correctly, the system has power, and the filter is clean. Many service calls are solved at this step.' },
    { question: 'A system with high suction pressure and high discharge pressure likely has:', options: ['Low charge', 'Overcharge or non-condensables', 'Restricted metering device', 'Dirty evaporator'], answer: 1, explanation: 'Both pressures high = too much refrigerant or non-condensable gases (air) in the system.' },
    { question: 'A system with low suction pressure and high discharge pressure likely has:', options: ['Overcharge', 'Undercharge', 'Airflow restriction (dirty filter, frozen coil)', 'Normal operation'], answer: 2, explanation: 'Low suction + high discharge = restricted airflow across the evaporator. The evaporator starves for heat, dropping suction pressure. The condenser cannot reject heat efficiently, raising discharge pressure.' },
    { question: 'What is the most common cause of a no-heat call on a gas furnace?', options: ['Bad gas valve', 'Cracked heat exchanger', 'Dirty flame sensor', 'Failed control board'], answer: 2, explanation: 'A dirty flame sensor is the #1 cause of no-heat calls. Carbon buildup prevents it from sensing flame current, so the board shuts off gas as a safety measure.' },
    { question: 'A compressor that hums but does not start most likely has:', options: ['Low refrigerant', 'A failed run capacitor or locked rotor', 'A dirty filter', 'A bad thermostat'], answer: 1, explanation: 'Humming = the motor is trying to start but cannot. Most common cause is a failed run capacitor. If the capacitor is good, the compressor may be mechanically locked.' },
    { question: 'Short cycling (system turns on and off rapidly) can be caused by:', options: ['Oversized system, low charge, or thermostat location', 'Undersized system', 'Too much refrigerant only', 'Dirty condenser only'], answer: 0, explanation: 'Short cycling causes: oversized equipment (satisfies quickly), low refrigerant (trips low-pressure switch), thermostat near a heat source, or tripping safety switches.' },
    { question: 'What does a pressure-temperature (PT) chart tell you?', options: ['The correct charge amount', 'The saturation temperature at a given pressure for a specific refrigerant', 'The airflow rate', 'The electrical rating'], answer: 1, explanation: 'A PT chart converts between pressure and saturation temperature. This is essential for calculating superheat and subcooling.' },
    { question: 'If the supply air temperature is the same as the return air temperature:', options: ['System is working perfectly', 'The compressor is not running or has no refrigerant', 'The filter needs replacement', 'The thermostat is broken'], answer: 1, explanation: 'No temperature difference means no heat transfer is occurring. Either the compressor is not running, the system has no refrigerant, or the blower is not moving air across the coil.' },
    { question: 'A frozen evaporator coil is most commonly caused by:', options: ['Too much refrigerant', 'Dirty air filter or low refrigerant charge', 'High outdoor temperature', 'A new filter'], answer: 1, explanation: 'Frozen coil = not enough heat reaching the coil. Two main causes: restricted airflow (dirty filter, failed blower) or low refrigerant charge.' },
    { question: 'Before diagnosing refrigerant charge, you must first verify:', options: ['The customer complaint', 'Adequate airflow across both coils', 'The brand of equipment', 'The age of the system'], answer: 1, explanation: 'Airflow problems cause the same symptoms as charge problems. Always verify airflow (clean filter, working blower, clean coils) before connecting gauges.' },
  ],

  'hvac-14': [
    { question: 'What is the purpose of lockout/tagout (LOTO)?', options: ['To lock the thermostat', 'To prevent accidental energization during service', 'To lock refrigerant valves', 'To tag equipment for warranty'], answer: 1, explanation: 'LOTO prevents unexpected startup of equipment during maintenance, protecting the technician from electrical shock, burns, or mechanical injury.' },
    { question: 'At what height does OSHA require fall protection in construction?', options: ['4 feet', '6 feet', '10 feet', '15 feet'], answer: 1, explanation: 'OSHA requires fall protection at 6 feet in construction. This applies to HVAC technicians working on rooftops, ladders, and scaffolding.' },
    { question: 'What does GHS stand for?', options: ['General Hazard System', 'Globally Harmonized System of Classification and Labelling', 'Government Health Standards', 'Gas Handling Safety'], answer: 1, explanation: 'GHS is the Globally Harmonized System — a standardized approach to chemical hazard classification and labeling used on Safety Data Sheets.' },
    { question: 'A Safety Data Sheet (SDS) contains how many sections?', options: ['8', '12', '16', '20'], answer: 2, explanation: 'An SDS has 16 standardized sections covering identification, hazards, composition, first aid, fire-fighting, handling, exposure controls, and more.' },
    { question: 'What type of fire extinguisher is used for electrical fires?', options: ['Class A (water)', 'Class B (foam)', 'Class C (CO2 or dry chemical)', 'Class D (metal)'], answer: 2, explanation: 'Class C extinguishers (CO2 or dry chemical) are used for electrical fires. Never use water on an electrical fire.' },
    { question: 'What PPE is required when brazing copper tubing?', options: ['Safety glasses only', 'Safety glasses, gloves, and fire-resistant clothing', 'Hard hat only', 'No PPE needed for brazing'], answer: 1, explanation: 'Brazing requires safety glasses (UV/IR protection), heat-resistant gloves, and fire-resistant clothing. A fire extinguisher must be within reach.' },
    { question: 'What is a permit-required confined space?', options: ['Any small room', 'A space with limited entry/exit that may contain hazardous atmospheres', 'A locked mechanical room', 'Any attic space'], answer: 1, explanation: 'Permit-required confined spaces have limited entry/exit and may contain hazardous atmospheres (low oxygen, toxic gases). Examples: boilers, tanks, some crawl spaces.' },
    { question: 'OSHA\'s "General Duty Clause" requires employers to:', options: ['Pay overtime', 'Provide a workplace free from recognized hazards', 'Provide health insurance', 'Allow breaks every hour'], answer: 1, explanation: 'The General Duty Clause (Section 5(a)(1)) requires employers to provide a workplace free from recognized hazards that could cause death or serious harm.' },
    { question: 'What should you do AFTER pulling an electrical disconnect?', options: ['Start working immediately', 'Verify 0 volts with a multimeter', 'Wait 5 minutes', 'Check the thermostat'], answer: 1, explanation: 'Always verify 0 volts with a multimeter after pulling the disconnect. Never trust the switch alone — it could be wired incorrectly or have a stuck contact.' },
    { question: 'Hot work permits are required for:', options: ['Any outdoor work', 'Brazing, soldering, or welding that could ignite nearby materials', 'Electrical work only', 'Refrigerant recovery'], answer: 1, explanation: 'Hot work permits are required when brazing, soldering, or welding in areas where sparks or heat could ignite nearby combustible materials.' },
  ],

  'hvac-15': [
    { question: 'What is the correct compression depth for adult CPR?', options: ['1 inch', 'At least 2 inches but no more than 2.4 inches', '3 inches', '4 inches'], answer: 1, explanation: 'Adult CPR compressions should be at least 2 inches deep but no more than 2.4 inches. Too shallow is ineffective; too deep can cause injury.' },
    { question: 'What is the correct compression rate for adult CPR?', options: ['60-80 per minute', '80-100 per minute', '100-120 per minute', '120-140 per minute'], answer: 2, explanation: 'The correct rate is 100-120 compressions per minute. Push hard and fast, allowing full chest recoil between compressions.' },
    { question: 'When using an AED, what do you do when it says "analyzing rhythm"?', options: ['Continue CPR', 'Stop touching the patient and stand clear', 'Remove the pads', 'Call 911'], answer: 1, explanation: 'When the AED is analyzing, everyone must stop touching the patient. Movement can interfere with the rhythm analysis.' },
    { question: 'What is the compression-to-breath ratio for single-rescuer adult CPR?', options: ['15:2', '30:2', '15:1', '30:1'], answer: 1, explanation: '30 compressions to 2 rescue breaths for single-rescuer adult CPR.' },
    { question: 'For severe bleeding, the first step is:', options: ['Apply a tourniquet', 'Apply direct pressure with a clean cloth', 'Elevate the limb only', 'Call 911 and wait'], answer: 1, explanation: 'Apply direct pressure to the wound with a clean cloth. If bleeding does not stop with direct pressure, consider a tourniquet for extremity wounds.' },
    { question: 'Signs of heat stroke include:', options: ['Shivering and pale skin', 'Hot, red, dry skin and altered mental status', 'Mild sweating', 'Cold hands and feet'], answer: 1, explanation: 'Heat stroke: hot/red/dry skin, confusion, loss of consciousness. This is a life-threatening emergency — call 911 and cool the person immediately.' },
    { question: 'HVAC technicians are at high risk for heat-related illness because:', options: ['They work outdoors only', 'They work in attics, on rooftops, and near hot equipment in summer', 'They handle cold refrigerant', 'They work in offices'], answer: 1, explanation: 'Attics can reach 140°F+, rooftops have direct sun exposure, and working near hot equipment increases heat stress risk significantly.' },
    { question: 'What should you do if a coworker receives an electrical shock and is still in contact with the source?', options: ['Grab them and pull them away', 'Disconnect the power source before touching them', 'Pour water on them', 'Wait for the shock to stop'], answer: 1, explanation: 'Never touch someone who is still in contact with an electrical source — you will be shocked too. Disconnect power first, or use a non-conductive object to separate them.' },
    { question: 'CPR/AED certification is valid for:', options: ['1 year', '2 years', '5 years', 'Lifetime'], answer: 1, explanation: 'CPR/AED certification is valid for 2 years and must be renewed. Skills degrade without practice.' },
    { question: 'When should you use an AED?', options: ['Only if the person is breathing', 'When a person is unresponsive and not breathing normally', 'Only in a hospital', 'Only if you are certified'], answer: 1, explanation: 'Use an AED when a person is unresponsive and not breathing normally (or only gasping). AEDs are designed for use by anyone — they provide voice instructions.' },
  ],

  'hvac-16': [
    { question: 'What credentials should appear on your HVAC technician resume?', options: ['Only EPA 608', 'EPA 608 Universal, OSHA 30, CPR/AED, and training hours', 'Only your high school diploma', 'Only work experience'], answer: 1, explanation: 'List all earned credentials: EPA 608 Universal, OSHA 30-Hour Construction Safety, CPR/AED, plus total training hours and lab competencies.' },
    { question: 'During an interview, how should you describe your EPA 608 certification?', options: ['Just say you have it', 'Explain it is the federal certification required to handle refrigerants, and you passed all 4 sections', 'Say it was easy', 'Do not mention it unless asked'], answer: 1, explanation: 'Explain what it means: federal certification under the Clean Air Act, covers all refrigerant types, required by law. This shows you understand the industry.' },
    { question: 'What is the typical starting hourly wage for an entry-level HVAC technician?', options: ['$8-10/hr', '$12-15/hr', '$16-22/hr', '$30-40/hr'], answer: 2, explanation: 'Entry-level HVAC technicians typically start at $16-22/hr depending on location and employer. With experience and additional certifications, wages increase significantly.' },
    { question: 'How many OJT hours are typically needed to reach Journeyman level?', options: ['480', '1,000', '2,000+', '8,000+'], answer: 2, explanation: 'Journeyman level typically requires 2,000+ on-the-job training hours plus passing the state journeyman exam.' },
    { question: 'What should you bring to an HVAC job interview?', options: ['Nothing', 'Resume, copies of certifications, and a professional attitude', 'Your tool bag', 'A list of salary demands'], answer: 1, explanation: 'Bring your resume, copies of all certifications (EPA 608 card, OSHA 30 card, CPR card), and dress professionally. First impressions matter.' },
    { question: 'What is the most important soft skill for an HVAC technician?', options: ['Speed', 'Communication — explaining problems and solutions to customers', 'Physical strength', 'Memorization'], answer: 1, explanation: 'Communication is essential. Technicians must explain problems, repair options, and costs to customers clearly and professionally. This builds trust and repeat business.' },
    { question: 'A service report should include:', options: ['Only the repair cost', 'Customer info, system info, diagnosis, work performed, parts used, and recommendations', 'Only your name and date', 'Nothing — verbal reports are fine'], answer: 1, explanation: 'Complete documentation protects you, the company, and the customer. Include everything: what you found, what you did, what parts you used, and what you recommend.' },
    { question: 'What does OJT stand for?', options: ['Online Job Training', 'On-the-Job Training', 'Official Job Test', 'Occupational Job Tracking'], answer: 1, explanation: 'OJT = On-the-Job Training. You work alongside experienced technicians, building real-world skills while earning a paycheck.' },
    { question: 'After completing this program, your next career step is:', options: ['Open your own business immediately', 'Begin OJT as an apprentice with a licensed HVAC company', 'Take a year off', 'Enroll in a 4-year degree program'], answer: 1, explanation: 'The next step is OJT placement with a licensed HVAC company. You will work as an apprentice, building hours toward your journeyman license.' },
    { question: 'What makes Elevate graduates stand out to employers?', options: ['Nothing special', 'EPA 608 Universal + OSHA 30 + CPR + 480+ training hours + hands-on lab experience', 'A college degree', 'Previous HVAC experience only'], answer: 1, explanation: 'Graduates have 3 industry credentials, 480+ documented training hours, and hands-on lab experience — more prepared than most entry-level candidates.' },
  ],
}
