export interface ModuleTool {
  name: string;
  whatItIs: string;
  usedFor: string;
}

export interface ModuleData {
  num: number;
  title: string;
  week: string;
  teaches: string;
  whyItMatters: string;
  tools: ModuleTool[];
  systems: string[];
  skills: string[];
  jobTasks: string[];
}

export const HVAC_MODULE_DATA: ModuleData[] = [
  {
    num: 1,
    title: 'Program Orientation and Career Pathways',
    week: 'Week 1',
    teaches: 'This module introduces students to the building technician and HVAC industry. Students learn how building systems work together and what technicians do on the job every day. It explains the types of environments technicians work in, including residential buildings, commercial facilities, apartments, and industrial sites. Students learn about career opportunities such as HVAC technician, building maintenance technician, facilities technician, and mechanical maintenance technician.',
    whyItMatters: 'Before you touch a single tool, you need to understand the industry you are entering. HVAC technicians are in demand everywhere — homes, offices, hospitals, factories, data centers. Understanding the full landscape helps you choose your career direction and stay motivated through 16 weeks of intensive training.',
    tools: [
      { name: 'No tools in this module', whatItIs: 'This is orientation — tools are introduced starting in Module 2.', usedFor: 'N/A' },
    ],
    systems: [
      'Overview of residential HVAC systems (furnaces, central AC, heat pumps)',
      'Overview of commercial HVAC systems (rooftop units, chillers, VRF)',
      'How heating, cooling, ventilation, and plumbing systems work together in a building',
      'The role of building automation systems (BAS) in modern facilities',
    ],
    skills: [
      'Understand what HVAC technicians do on a daily basis',
      'Identify the four career levels: apprentice, journeyman, master, contractor',
      'Explain the three credentials earned in this program (EPA 608, OSHA 10, CPR)',
      'Describe WIOA funding requirements including attendance and documentation',
      'Map the difference between residential, commercial, and industrial HVAC work',
    ],
    jobTasks: [
      'Explaining your qualifications and career goals during a job interview',
      'Understanding what your employer expects from a first-year apprentice',
      'Knowing which certifications to pursue after completing this program',
      'Communicating professionally with supervisors and customers from day one',
    ],
  },
  {
    num: 2,
    title: 'Safety Fundamentals and OSHA Principles',
    week: 'Week 2',
    teaches: 'Safety is the foundation of all skilled trades. Students learn workplace safety practices used in mechanical trades and building maintenance. Topics include electrical safety, lockout/tagout procedures, ladder safety, personal protective equipment, and hazard recognition. Students learn basic OSHA safety principles used in the HVAC and maintenance industry.',
    whyItMatters: 'HVAC technicians work with high voltage electricity, pressurized refrigerant, natural gas, and heavy equipment — often in attics at 140°F or on rooftops in winter. One mistake can kill you. Every employer requires safety training before you touch equipment. OSHA 10 certification makes you more hireable and can add $2-4/hr to your pay.',
    tools: [
      { name: 'Safety Glasses', whatItIs: 'Impact-resistant eyewear that protects your eyes from debris, refrigerant spray, and electrical arc flash.', usedFor: 'Worn at all times when working on any HVAC equipment. Refrigerant liquid can cause instant frostbite to your eyes.' },
      { name: 'Work Gloves', whatItIs: 'Insulated gloves rated for the voltage you are working with. Different gloves for electrical work vs. refrigerant handling.', usedFor: 'Protecting hands from electrical shock, sharp metal edges on sheet metal ductwork, and frostbite from liquid refrigerant.' },
      { name: 'Non-Contact Voltage Tester', whatItIs: 'A pen-shaped device that detects the presence of AC voltage without touching bare wires. It beeps or lights up when voltage is present.', usedFor: 'Verifying that a circuit is de-energized BEFORE you touch it. This is your first check — but never your only check.' },
      { name: 'Lockout/Tagout Kit', whatItIs: 'A set of padlocks, hasps, and tags used to physically lock a disconnect switch in the OFF position so nobody can accidentally turn it back on while you are working.', usedFor: 'Preventing accidental energization of equipment during service. You lock it, you keep the key. Nobody removes your lock but you.' },
      { name: 'Digital Multimeter', whatItIs: 'A handheld electronic instrument that measures voltage (V), current (A), and resistance (Ω). The most important diagnostic tool in HVAC.', usedFor: 'Verifying 0 volts after pulling a disconnect. Never trust the switch alone — always verify with your meter.' },
    ],
    systems: [
      'Electrical disconnect switches and breaker panels',
      'Lockout/tagout points on HVAC equipment',
      'Ladder types and weight ratings (Type I, IA, IAA)',
      'Personal protective equipment (PPE) selection for different hazards',
      'Fire extinguisher types and when to use each one',
    ],
    skills: [
      'Perform lockout/tagout (LOTO) per OSHA standards on live equipment',
      'Identify workplace hazards before starting any job',
      'Select correct PPE for electrical, refrigerant, and mechanical hazards',
      'Use a non-contact voltage tester and multimeter to verify zero energy',
      'Set up ladders safely on uneven surfaces and at correct angles',
    ],
    jobTasks: [
      'De-energizing a rooftop unit before opening the electrical panel',
      'Setting up a ladder safely to access an attic or roof',
      'Selecting the right gloves and glasses before handling refrigerant',
      'Completing a job site safety assessment before starting work',
      'Responding correctly if a coworker is injured on the job',
    ],
  },
  {
    num: 3,
    title: 'HVAC Tools and Equipment',
    week: 'Week 3',
    teaches: 'This module introduces the core tools technicians use daily. Students learn the names, purpose, and correct operation of every tool used to install, diagnose, and service HVAC systems. Each tool is explained in detail — what it is, what it measures, how to read it, and when you use it on a service call.',
    whyItMatters: 'A technician without tools is just a person standing next to a broken AC unit. Knowing your tools — what they measure, how to read them, when to use them — is what separates a trained technician from someone guessing. Employers expect you to show up knowing these tools by name on day one.',
    tools: [
      { name: 'Gauge Manifold Set', whatItIs: 'A set of two pressure gauges (low-side and high-side) connected by hoses. The blue gauge reads suction pressure, the red gauge reads discharge pressure, and the yellow hose connects to a refrigerant tank or vacuum pump.', usedFor: 'Measuring refrigerant pressures on every cooling service call. You connect it to the service ports on the outdoor unit to read system pressures and diagnose problems.' },
      { name: 'Digital Multimeter', whatItIs: 'A handheld electronic instrument with a display screen, a rotary dial to select measurement type, and two probes (red and black). Measures voltage (V), current (A), resistance (Ω), and capacitance (µF).', usedFor: 'Testing every electrical component in an HVAC system — checking if a contactor is passing voltage, if a capacitor is within spec, if a motor winding is open, if a transformer is outputting 24V.' },
      { name: 'Amp Clamp (Clamp Meter)', whatItIs: 'A meter with a spring-loaded jaw that clamps around a single insulated wire. It measures the current (amperage) flowing through that wire without disconnecting anything.', usedFor: 'Checking compressor amp draw to see if it is running within nameplate specs. Checking fan motor amps. Verifying a circuit is truly dead (0 amps).' },
      { name: 'Vacuum Pump', whatItIs: 'An electric pump that creates a deep vacuum inside refrigerant lines. It pulls air and moisture out of the system down to 500 microns or below.', usedFor: 'Evacuating a system before charging it with refrigerant. Moisture inside a refrigerant system creates acid that destroys the compressor — the vacuum pump removes it.' },
      { name: 'Refrigerant Recovery Machine', whatItIs: 'A portable machine that pulls refrigerant out of an HVAC system and stores it in a recovery cylinder. It has its own compressor and gauges.', usedFor: 'Removing refrigerant before opening any part of the refrigerant circuit. Federal law requires this — venting refrigerant carries fines up to $44,539 per day per violation.' },
      { name: 'Micron Gauge', whatItIs: 'A digital gauge that measures vacuum levels far below what a standard gauge manifold can read. Displays in microns (1 micron = 1/1000 of a millimeter of mercury).', usedFor: 'Verifying that your vacuum pump has pulled the system down to 500 microns or below. If it will not hold vacuum, you have a leak.' },
      { name: 'Refrigerant Scale', whatItIs: 'A digital scale accurate to fractions of an ounce. Sits under the refrigerant cylinder to measure exactly how much refrigerant you are adding or removing.', usedFor: 'Charging a system by weight — the manufacturer specifies exactly how many pounds and ounces of refrigerant the system needs.' },
      { name: 'Tube Cutter', whatItIs: 'A hand tool with a cutting wheel that scores and cuts copper refrigerant tubing. Available in mini (for tight spaces) and standard sizes.', usedFor: 'Cutting copper line sets during installation. You must ream the inside of the cut to remove the burr — a burr restricts refrigerant flow.' },
      { name: 'Flaring Tool', whatItIs: 'A clamping tool that holds copper tubing and a cone that presses into the end to create a 45-degree flare. The flare creates a seal when tightened against a flare fitting.', usedFor: 'Making flare connections on copper tubing. A bad flare — uneven, cracked, or wrong size — is the number one cause of refrigerant leaks at fittings.' },
      { name: 'Electronic Leak Detector', whatItIs: 'A handheld device with a flexible probe tip that senses halogen gases (refrigerant) in the air. It beeps faster or changes tone when it detects a leak.', usedFor: 'Finding refrigerant leaks by slowly sweeping the probe around joints, fittings, valves, and coil connections. Always confirm with soap bubbles after the detector finds the area.' },
    ],
    systems: [
      'Service ports on outdoor condensing units (high-side and low-side)',
      'Electrical panels and disconnect switches on HVAC equipment',
      'Copper refrigerant line sets (suction line and liquid line)',
      'Flare fittings and brazed connections',
      'Recovery cylinders and refrigerant tanks',
    ],
    skills: [
      'Identify all 10 core HVAC tools by name and explain their purpose',
      'Connect a gauge manifold to service ports and read pressures correctly',
      'Use a multimeter to measure voltage, resistance, and capacitance',
      'Operate a vacuum pump and verify vacuum level with a micron gauge',
      'Cut and flare copper tubing to create a leak-free connection',
    ],
    jobTasks: [
      'Setting up your tools at a residential service call',
      'Connecting gauges to diagnose a no-cool complaint',
      'Testing a capacitor with a multimeter to determine if it has failed',
      'Recovering refrigerant before replacing a compressor',
      'Cutting and flaring copper for a mini-split installation',
    ],
  },
  {
    num: 4,
    title: 'Basic Electricity for HVAC Systems',
    week: 'Week 4',
    teaches: 'Electrical knowledge is essential for diagnosing heating and cooling systems. This module explains electrical fundamentals including voltage, current, resistance, and circuits. Students learn how electricity flows through HVAC components such as contactors, capacitors, relays, and motors. The module teaches how to read wiring diagrams and ladder diagrams — the blueprints that show how every wire in the system connects.',
    whyItMatters: 'Over 60% of HVAC service calls involve an electrical problem — a bad capacitor, a stuck contactor, a blown transformer, a failed motor winding. If you cannot read a wiring diagram and trace current flow with a meter, you cannot diagnose anything. This module is the difference between a technician and a parts changer.',
    tools: [
      { name: 'Digital Multimeter', whatItIs: 'Measures voltage (how much electrical pressure), amperage (how much current is flowing), resistance (how much opposition to current flow), and capacitance (how much charge a capacitor can store).', usedFor: 'Testing every electrical component — checking voltage at a contactor, measuring capacitance on a run capacitor, testing a motor winding for continuity or open circuit.' },
      { name: 'Amp Clamp (Clamp Meter)', whatItIs: 'Clamps around a single insulated wire to measure current flow without breaking the circuit. The jaws use magnetic induction to sense amperage.', usedFor: 'Checking if a compressor is drawing too many amps (overloaded), checking fan motor amps, verifying a circuit is truly de-energized.' },
      { name: 'Wiring Diagram Reference Sheets', whatItIs: 'Printed diagrams that show how every wire in an HVAC system connects — which terminals, which colors, which components. Found inside the equipment panel or in the installation manual.', usedFor: 'Tracing current flow to find where voltage is being lost. If the thermostat calls for cooling but the compressor does not start, you trace the diagram to find which component is not passing voltage.' },
    ],
    systems: [
      'Contactors — electromagnetic switches that turn the compressor and fan on/off',
      'Capacitors — store and release electrical energy to start and run motors (start caps and run caps)',
      'Relays — smaller electromagnetic switches used in control circuits (fan relays, time-delay relays)',
      'Transformers — step voltage down from 240V to 24V for the thermostat control circuit',
      'Motors — compressor motors, condenser fan motors, blower motors, inducer motors',
      'Fuses and circuit breakers — overcurrent protection devices',
    ],
    skills: [
      'Calculate voltage, current, and resistance using Ohm\'s Law (V = I × R)',
      'Read a ladder diagram and trace current flow from power source to load',
      'Measure voltage, amperage, resistance, and capacitance with a multimeter',
      'Test a capacitor and determine pass/fail (within ±6% of rated value)',
      'Identify open circuits, short circuits, and grounded circuits',
    ],
    jobTasks: [
      'Diagnosing why an outdoor unit is not starting — tracing voltage from disconnect through contactor to compressor',
      'Testing a run capacitor that a homeowner says "the AC hums but won\'t start"',
      'Replacing a blown 3-amp fuse on a furnace control board',
      'Reading the wiring diagram inside a condenser panel to identify wire colors and terminal locations',
      'Measuring amp draw on a compressor to determine if it is mechanically seized',
    ],
  },
  {
    num: 5,
    title: 'HVAC System Components',
    week: 'Week 5',
    teaches: 'This module teaches students how to identify the major components found inside HVAC systems. Students learn the purpose and function of compressors, condensers, evaporator coils, expansion devices, and blower motors. Students examine how each component contributes to the heating and cooling process and how technicians inspect these components during service visits.',
    whyItMatters: 'You cannot fix what you cannot identify. When you open a condenser panel or look inside an air handler, you need to instantly recognize every component — what it is, what it does, and what it looks like when it has failed. This is the foundation for all troubleshooting.',
    tools: [
      { name: 'Gauge Manifold Set', whatItIs: 'Two pressure gauges connected by hoses that measure suction and discharge pressure at the service ports.', usedFor: 'Reading system pressures to evaluate how each component is performing — high discharge pressure may mean a dirty condenser, low suction may mean a restricted metering device.' },
      { name: 'Temperature Clamps', whatItIs: 'Pipe clamp thermometers that attach to copper refrigerant lines to measure the temperature of the refrigerant inside.', usedFor: 'Measuring suction line temperature and liquid line temperature to calculate superheat and subcooling — the two most important diagnostic measurements in HVAC.' },
      { name: 'Inspection Mirror', whatItIs: 'A small mirror on a telescoping handle that lets you see into tight spaces behind equipment.', usedFor: 'Inspecting evaporator coils for ice buildup, checking condenser coils for debris, looking at connections you cannot reach directly.' },
    ],
    systems: [
      'Compressor — the pump that circulates refrigerant through the entire system (scroll, reciprocating, rotary types)',
      'Condenser coil — the outdoor coil where refrigerant releases heat to the outside air',
      'Condenser fan motor — pulls air across the condenser coil to help reject heat',
      'Evaporator coil — the indoor coil where refrigerant absorbs heat from the indoor air',
      'Metering device — TXV (thermostatic expansion valve) or fixed orifice (piston) that controls refrigerant flow into the evaporator',
      'Blower motor — pushes air across the evaporator coil and through the ductwork into the building',
      'Filter drier — removes moisture and contaminants from the refrigerant circuit',
      'Accumulator — prevents liquid refrigerant from reaching the compressor (flood-back protection)',
    ],
    skills: [
      'Identify all major components on a live split AC system by sight',
      'Explain what each component does in the refrigeration cycle',
      'Recognize visual signs of component failure (oil stains, burn marks, ice, corrosion)',
      'Trace the refrigerant path from compressor through the entire system and back',
      'Identify the difference between a TXV and a fixed orifice metering device',
    ],
    jobTasks: [
      'Walking a homeowner through what is wrong with their system using correct component names',
      'Inspecting a condenser unit and identifying a failed fan motor by sight and sound',
      'Checking an evaporator coil for ice buildup and explaining the possible causes',
      'Identifying the metering device type to determine the correct charging method',
      'Documenting which components were inspected on a maintenance checklist',
    ],
  },
  {
    num: 6,
    title: 'The Refrigeration Cycle',
    week: 'Week 6',
    teaches: 'The refrigeration cycle is the heart of every HVAC cooling system. Students learn the four stages: compression, condensation, expansion, and evaporation. Students learn how refrigerant moves through the system, how temperature and pressure change at each stage, and how to use a pressure-temperature (PT) chart to convert between pressure readings and saturation temperatures.',
    whyItMatters: 'Every cooling diagnosis starts with understanding the refrigeration cycle. When a system is not cooling, you need to know where in the cycle the problem is occurring. Is the compressor not compressing? Is the condenser not rejecting heat? Is the metering device restricted? Is the evaporator not absorbing heat? You cannot answer these questions without understanding the cycle.',
    tools: [
      { name: 'Gauge Manifold Set', whatItIs: 'Measures suction and discharge pressure — the two readings that tell you what the refrigerant is doing at every stage of the cycle.', usedFor: 'Connecting to service ports and reading pressures to evaluate system performance. Normal R-410A suction is 118-150 psig, discharge is 300-400 psig at typical conditions.' },
      { name: 'Temperature Clamps', whatItIs: 'Pipe clamp sensors that measure the actual temperature of the refrigerant line.', usedFor: 'Calculating superheat (suction line temp minus saturation temp) and subcooling (saturation temp minus liquid line temp) — the two measurements that tell you if the system has the right amount of refrigerant.' },
      { name: 'PT Chart', whatItIs: 'A pressure-temperature chart that shows the boiling point of each refrigerant at different pressures. Every refrigerant has a different PT relationship.', usedFor: 'Converting your gauge pressure reading to a saturation temperature. Example: R-410A at 118 psig has a saturation temperature of 40°F.' },
    ],
    systems: [
      'Stage 1: Compression — compressor takes low-pressure gas and compresses it into high-pressure, high-temperature gas',
      'Stage 2: Condensation — hot gas flows through the condenser coil, releases heat to outdoor air, and condenses into a high-pressure liquid',
      'Stage 3: Expansion — liquid refrigerant passes through the metering device, pressure drops dramatically, creating a cold low-pressure mixture',
      'Stage 4: Evaporation — cold mixture flows through the evaporator coil, absorbs heat from indoor air, and evaporates back into a low-pressure gas',
      'The cycle repeats continuously as long as the thermostat calls for cooling',
    ],
    skills: [
      'Diagram the complete refrigeration cycle with correct pressure and temperature states at each point',
      'Calculate superheat from live gauge readings and temperature measurements',
      'Calculate subcooling from live gauge readings and temperature measurements',
      'Use a PT chart to look up saturation temperature for R-410A, R-22, and R-134a',
      'Explain what happens to pressures and temperatures when common problems occur (low charge, overcharge, dirty coil, restriction)',
    ],
    jobTasks: [
      'Diagnosing a system that is running but not cooling by reading pressures and calculating superheat/subcooling',
      'Explaining to a customer why their system needs refrigerant and what caused the leak',
      'Determining if a system is overcharged or undercharged based on pressure and temperature readings',
      'Using a PT chart in the field to verify system performance against manufacturer specifications',
    ],
  },
  {
    num: 7,
    title: 'Refrigerants and EPA Section 608 Regulations',
    week: 'Week 7',
    teaches: 'This module prepares students for the EPA Section 608 certification. Students learn about refrigerant types (CFC, HCFC, HFC, HFO), environmental regulations, and safe refrigerant handling procedures. Students learn why refrigerant leaks are harmful to the environment and how federal regulations require technicians to properly recover and recycle refrigerant.',
    whyItMatters: 'Federal law. You cannot purchase or handle refrigerant without EPA 608 certification. The fine for knowingly venting refrigerant is up to $44,539 per day per violation. This is not optional — it is the law, and employers verify your certification before hiring you.',
    tools: [
      { name: 'Recovery Machine', whatItIs: 'A portable compressor unit that pulls refrigerant out of an HVAC system and pushes it into a recovery cylinder for proper disposal or recycling.', usedFor: 'Removing refrigerant from any system before opening the refrigerant circuit for repair. Required by federal law.' },
      { name: 'Recovery Cylinder', whatItIs: 'A DOT-approved steel cylinder (usually gray with yellow top) designed to hold recovered refrigerant. Has a float switch to prevent overfilling.', usedFor: 'Storing recovered refrigerant. Must never be filled above 80% capacity. Must be labeled with the type of refrigerant inside.' },
      { name: 'Refrigerant Scale', whatItIs: 'A digital scale accurate to fractions of an ounce that sits under the refrigerant cylinder.', usedFor: 'Weighing refrigerant during recovery and charging to ensure accurate amounts and prevent overfilling recovery cylinders.' },
      { name: 'Leak Detector', whatItIs: 'An electronic device that senses halogen gases in the air to locate refrigerant leaks.', usedFor: 'Finding leaks that must be repaired before recharging. Systems with 50+ lbs of refrigerant have mandatory leak repair timelines under EPA regulations.' },
    ],
    systems: [
      'CFC refrigerants (R-12) — banned, highest ozone depletion potential, still found in old equipment',
      'HCFC refrigerants (R-22) — phased out, cannot be manufactured, still serviced in existing systems',
      'HFC refrigerants (R-410A, R-134a) — current standard, zero ozone depletion but high global warming potential',
      'HFO refrigerants (R-1234yf) — next generation, low GWP, being adopted in automotive and some commercial',
      'Recovery, recycling, and reclamation — three different processes with different legal requirements',
    ],
    skills: [
      'Classify refrigerants by type (CFC, HCFC, HFC, HFO) and identify their environmental impact',
      'State the maximum fine for knowingly venting refrigerant ($44,539/day)',
      'Explain the difference between recovery (removing), recycling (cleaning on-site), and reclamation (processing to ARI 700 purity at a certified facility)',
      'Identify who can purchase refrigerant (EPA 608 certified technicians only, since January 2018)',
      'Score 85%+ on EPA 608 Core section practice exam',
    ],
    jobTasks: [
      'Recovering refrigerant from a system before replacing a compressor',
      'Properly labeling a recovery cylinder with refrigerant type and date',
      'Explaining to a customer why you cannot just "top off" their R-22 system without finding the leak',
      'Documenting refrigerant amounts recovered and charged on a service ticket',
      'Identifying an unknown refrigerant type before connecting your gauges (never mix refrigerants)',
    ],
  },
  {
    num: 8,
    title: 'Refrigerant Recovery and Charging Procedures',
    week: 'Week 8',
    teaches: 'Technicians must safely remove and recharge refrigerant in HVAC systems. This module teaches the hands-on procedures used to recover refrigerant from equipment, evacuate systems with a vacuum pump, and properly charge systems using both the weighing method and the superheat/subcooling method.',
    whyItMatters: 'This is what you do on almost every major repair. Compressor replacement, coil replacement, line set repair — all require recovering the refrigerant, pulling a vacuum, and recharging. If you cannot do this correctly, you cannot do the job. An improper charge wastes energy, damages equipment, and costs the customer money.',
    tools: [
      { name: 'Recovery Machine', whatItIs: 'Pulls refrigerant out of the system into a recovery cylinder. Has its own compressor, gauges, and hoses.', usedFor: 'Removing all refrigerant before opening the system. You must recover to the required vacuum level specified by EPA regulations.' },
      { name: 'Vacuum Pump', whatItIs: 'An electric pump that creates a deep vacuum (500 microns or below) inside the refrigerant lines after the system has been opened.', usedFor: 'Removing moisture and air from the system before adding refrigerant. Moisture creates acid that destroys the compressor from the inside.' },
      { name: 'Micron Gauge', whatItIs: 'A digital gauge that reads vacuum levels in microns — far more precise than a standard gauge manifold.', usedFor: 'Verifying the system has reached 500 microns or below and holds that vacuum. If it rises, you have a leak or moisture still boiling off.' },
      { name: 'Gauge Manifold Set', whatItIs: 'Connects to the system service ports and to the refrigerant tank. Controls the flow of refrigerant into the system.', usedFor: 'Monitoring pressures during charging and controlling how much refrigerant enters the system.' },
      { name: 'Refrigerant Scale', whatItIs: 'Digital scale under the refrigerant cylinder that measures weight to fractions of an ounce.', usedFor: 'Charging by weight — adding the exact amount specified by the manufacturer. The most accurate charging method.' },
      { name: 'Temperature Clamps', whatItIs: 'Pipe clamp thermometers that attach to the suction and liquid lines.', usedFor: 'Calculating superheat and subcooling during charging to verify the system has the correct amount of refrigerant.' },
    ],
    systems: [
      'Refrigerant recovery process — connecting recovery machine, monitoring pressures, verifying complete recovery',
      'System evacuation — connecting vacuum pump, pulling to 500 microns, performing a standing vacuum test',
      'Charging by weight — using the scale to add the exact factory charge amount',
      'Charging by superheat — for systems with fixed orifice (piston) metering devices',
      'Charging by subcooling — for systems with TXV metering devices',
    ],
    skills: [
      'Recover refrigerant from a system to EPA-required vacuum levels',
      'Evacuate a system to 500 microns and perform a standing vacuum test',
      'Charge a system by weight using a refrigerant scale',
      'Charge a system by superheat method (fixed orifice systems)',
      'Charge a system by subcooling method (TXV systems)',
      'Determine which charging method to use based on the metering device type',
    ],
    jobTasks: [
      'Recovering all refrigerant before replacing an evaporator coil',
      'Pulling a vacuum on a new mini-split installation and verifying 500 microns',
      'Charging a new system by weight per the manufacturer nameplate',
      'Adjusting charge on an existing system using superheat or subcooling readings',
      'Documenting all refrigerant amounts on the service ticket for EPA compliance',
    ],
  },
  {
    num: 9,
    title: 'Heating Systems Fundamentals',
    week: 'Week 9',
    teaches: 'Students explore the heating side of HVAC systems. Topics include gas furnaces (natural gas and propane), electric furnaces, heat pumps in heating mode, and combustion safety. Students learn how heating systems generate heat, how safety controls prevent dangerous conditions, and how technicians inspect heating equipment during maintenance and repair.',
    whyItMatters: 'Heating calls are half the business. In cold months, furnace breakdowns are emergencies — families with no heat in winter. You need to diagnose furnace problems quickly and safely. A cracked heat exchanger can leak carbon monoxide into a home and kill people. This is life-safety work.',
    tools: [
      { name: 'Combustion Analyzer', whatItIs: 'A handheld instrument with a probe that inserts into the furnace flue. It measures CO (carbon monoxide), CO2, O2, and flue gas temperature.', usedFor: 'Verifying that a furnace is burning fuel safely and efficiently. CO readings above 100 ppm in undiluted flue gas indicate a dangerous combustion problem.' },
      { name: 'Manometer', whatItIs: 'A digital pressure gauge that measures gas pressure in inches of water column (in. WC). Very low pressures compared to refrigerant gauges.', usedFor: 'Checking gas pressure at the furnace gas valve. Natural gas should be 3.5 in. WC, propane should be 10-11 in. WC. Wrong pressure means wrong flame.' },
      { name: 'Temperature Probes', whatItIs: 'Thermocouples or thermistors on wires that measure air temperature at specific points in the system.', usedFor: 'Measuring supply air temperature and return air temperature to calculate temperature rise. Must match the range on the furnace nameplate (typically 30-60°F).' },
      { name: 'CO Detector', whatItIs: 'A personal carbon monoxide detector worn on your body or placed in the living space during furnace service.', usedFor: 'Protecting yourself and the occupants. If your personal CO detector alarms, you evacuate immediately and ventilate the space.' },
    ],
    systems: [
      'Gas furnace components — gas valve, burners, heat exchanger, inducer motor, hot surface igniter, flame sensor, limit switch, blower motor',
      'Ignition types — standing pilot (old), hot surface igniter (HSI, most common), direct spark ignition (DSI)',
      'Heat pump in heating mode — reversing valve switches refrigerant flow so the outdoor coil absorbs heat and the indoor coil releases it',
      'Electric furnace — heating elements (like a giant toaster) controlled by sequencers',
      'Combustion air and venting — how exhaust gases exit the building safely',
    ],
    skills: [
      'Identify all components of a gas furnace by sight',
      'Measure temperature rise and verify it matches the furnace nameplate',
      'Perform CO testing and interpret the results',
      'Check gas pressure at the gas valve with a manometer',
      'Clean a flame sensor and explain why dirty sensors cause lockouts',
      'Identify the ignition type on any furnace',
    ],
    jobTasks: [
      'Diagnosing a no-heat call — checking thermostat, power, gas supply, ignition sequence',
      'Performing a furnace safety inspection including CO testing and heat exchanger visual check',
      'Cleaning a flame sensor on a furnace that keeps shutting off after a few minutes',
      'Checking gas pressure on a furnace that is producing a yellow or lazy flame',
      'Explaining to a homeowner why their cracked heat exchanger is dangerous and must be replaced',
    ],
  },
  {
    num: 10,
    title: 'Air Distribution and Ventilation',
    week: 'Week 10',
    teaches: 'Heating and cooling systems rely on airflow to deliver conditioned air throughout buildings. This module teaches how duct systems, vents, registers, filters, and air handlers distribute air. Students learn how to measure airflow, identify duct problems, and understand how poor airflow affects system performance and efficiency.',
    whyItMatters: 'The best compressor in the world cannot cool a house if the ductwork is crushed, disconnected, or undersized. Airflow problems cause frozen coils, high energy bills, hot/cold spots, and premature equipment failure. Many service calls that seem like refrigerant problems are actually airflow problems. Technicians who understand airflow solve problems faster.',
    tools: [
      { name: 'Anemometer', whatItIs: 'A handheld device with a small fan or hot-wire sensor that measures air velocity in feet per minute (FPM).', usedFor: 'Measuring airflow at supply registers and return grilles. You multiply velocity by the duct area to calculate CFM (cubic feet per minute).' },
      { name: 'Manometer (Static Pressure)', whatItIs: 'A digital pressure gauge with a probe that inserts into the ductwork through a small drilled hole. Measures pressure in inches of water column.', usedFor: 'Measuring total external static pressure — the resistance the blower must overcome to push air through the duct system. High static pressure means restricted airflow.' },
      { name: 'Duct Calculator', whatItIs: 'A slide-rule or app that calculates the correct duct size based on the required CFM and acceptable friction rate.', usedFor: 'Verifying that existing ductwork is properly sized for the equipment. Undersized ducts restrict airflow and cause problems.' },
    ],
    systems: [
      'Supply ductwork — delivers conditioned air from the air handler to each room',
      'Return ductwork — brings room air back to the air handler to be heated or cooled again',
      'Registers and grilles — the visible vents in each room that direct airflow',
      'Air filters — trap dust, pollen, and debris before air enters the equipment (MERV ratings)',
      'Air handler / blower assembly — the fan that moves air through the entire duct system',
      'Dampers — adjustable plates inside ducts that control airflow to different zones',
    ],
    skills: [
      'Measure airflow at supply registers using an anemometer',
      'Measure total external static pressure on a duct system',
      'Identify common duct problems: disconnected ducts, crushed flex duct, missing insulation, leaky joints',
      'Explain how a dirty filter reduces airflow and causes the evaporator coil to freeze',
      'Calculate approximate CFM from velocity and duct dimensions',
    ],
    jobTasks: [
      'Diagnosing a frozen evaporator coil caused by a clogged filter — not a refrigerant problem',
      'Checking airflow at registers in rooms that are not getting enough heating or cooling',
      'Measuring static pressure to determine if ductwork is restricting the system',
      'Recommending duct repairs or modifications to improve comfort and efficiency',
      'Explaining to a customer why they need to change their filter every 1-3 months',
    ],
  },
  {
    num: 11,
    title: 'Thermostats and Control Systems',
    week: 'Week 11',
    teaches: 'HVAC systems rely on controls to regulate temperature and system operation. This module explains how thermostats, sensors, control boards, and low-voltage wiring manage heating and cooling cycles. Students learn how technicians diagnose thermostat problems, wiring faults, and system communication failures between the thermostat and the equipment.',
    whyItMatters: 'The thermostat is the brain of the HVAC system. If the thermostat is not sending the right signal, nothing works — even if every other component is perfect. Thermostat and control problems account for a large percentage of service calls. Technicians who understand control wiring solve problems that stump others.',
    tools: [
      { name: 'Digital Multimeter', whatItIs: 'Measures low voltage (24V) at thermostat terminals and control board terminals to verify signals are being sent and received.', usedFor: 'Checking if the thermostat is sending 24V on the Y (cooling), W (heating), G (fan), and R (power) terminals. If voltage is present at the thermostat but not at the equipment, the wire is broken.' },
      { name: 'Thermostat Wire Tester', whatItIs: 'A simple continuity tester that checks if thermostat wires are intact from the thermostat to the equipment.', usedFor: 'Finding broken wires in walls or attics that prevent the thermostat signal from reaching the furnace or air handler.' },
      { name: 'Wiring Diagram', whatItIs: 'The schematic found inside the equipment panel showing how thermostat wires connect to the control board.', usedFor: 'Tracing which terminal on the thermostat connects to which terminal on the control board. Color codes vary — always verify with the diagram.' },
    ],
    systems: [
      'Thermostat types — mechanical, digital programmable, smart/WiFi thermostats',
      'Low-voltage control circuit — 24V transformer, thermostat wires (R, Y, W, G, C, O/B)',
      'Control boards — the circuit board inside the furnace or air handler that receives thermostat signals and controls equipment',
      'Temperature sensors — thermistors and RTDs that measure air and refrigerant temperature',
      'Zone control systems — dampers and multiple thermostats controlling different areas of a building',
    ],
    skills: [
      'Wire a thermostat to a control board using correct terminal designations',
      'Measure 24V control voltage at thermostat and equipment terminals',
      'Diagnose a thermostat that is not calling for heating or cooling',
      'Identify the difference between conventional and heat pump thermostat wiring',
      'Troubleshoot a system where the thermostat displays correctly but equipment does not respond',
    ],
    jobTasks: [
      'Installing a new programmable thermostat and wiring it correctly',
      'Diagnosing why a system will not turn on — checking for 24V at the control board',
      'Replacing a failed control board and verifying all thermostat signals are received',
      'Explaining to a customer how to program their thermostat for energy savings',
      'Troubleshooting a zone system where one zone is not getting conditioned air',
    ],
  },
  {
    num: 12,
    title: 'Preventive Maintenance Procedures',
    week: 'Week 12',
    teaches: 'Routine maintenance helps HVAC systems operate efficiently and prevents major failures. Students learn the maintenance tasks technicians perform regularly including filter replacement, coil cleaning, electrical connection inspection, refrigerant level checks, and seasonal startup/shutdown procedures. Students complete a full maintenance checklist on simulated equipment.',
    whyItMatters: 'Preventive maintenance is steady, reliable work. Many HVAC companies run maintenance agreement programs where technicians visit the same customers twice a year — spring for cooling, fall for heating. A technician who can perform thorough maintenance inspections catches problems early, prevents expensive breakdowns, and builds customer trust. This is how you build a career.',
    tools: [
      { name: 'Coil Cleaning Solution', whatItIs: 'A chemical spray (acid-based or alkaline-based) that dissolves dirt, grease, and biological growth on condenser and evaporator coils.', usedFor: 'Cleaning dirty coils that reduce heat transfer and make the system work harder. A dirty condenser coil can increase energy consumption by 30% or more.' },
      { name: 'Fin Comb', whatItIs: 'A small hand tool with different-sized teeth that straighten bent aluminum fins on condenser and evaporator coils.', usedFor: 'Straightening fins that have been bent by debris, hail, or careless handling. Bent fins block airflow across the coil.' },
      { name: 'Digital Multimeter', whatItIs: 'Used during maintenance to check capacitor values, contactor condition, and motor amp draw.', usedFor: 'Verifying that electrical components are still within specification. A capacitor that has drifted more than 6% from its rated value should be replaced before it fails.' },
      { name: 'Gauge Manifold Set', whatItIs: 'Connected during maintenance to check refrigerant pressures and verify the system is properly charged.', usedFor: 'Confirming that superheat and subcooling are within normal range. If pressures are off, there may be a leak or other problem developing.' },
    ],
    systems: [
      'Condenser coil cleaning and inspection',
      'Evaporator coil inspection (visual check for ice, dirt, biological growth)',
      'Air filter inspection and replacement (MERV ratings, filter sizes)',
      'Electrical connection tightening and inspection (loose connections cause arcing and fires)',
      'Capacitor testing (run caps and start caps)',
      'Contactor inspection (pitting, welding, chattering)',
      'Drain line clearing (condensate drain clogs cause water damage)',
      'Thermostat calibration verification',
    ],
    skills: [
      'Perform a complete cooling season maintenance inspection using a checklist',
      'Perform a complete heating season maintenance inspection using a checklist',
      'Clean a condenser coil without damaging the fins',
      'Test a capacitor and determine if it needs replacement',
      'Clear a clogged condensate drain line',
      'Document all findings on a maintenance report for the customer',
    ],
    jobTasks: [
      'Performing a spring AC tune-up at a residential customer home',
      'Performing a fall furnace inspection including CO testing',
      'Writing up a maintenance report that explains what was found and what needs attention',
      'Recommending a capacitor replacement before it fails during peak summer',
      'Explaining to a customer why annual maintenance saves money and prevents breakdowns',
    ],
  },
  {
    num: 13,
    title: 'Troubleshooting HVAC Systems',
    week: 'Week 13',
    teaches: 'Troubleshooting is one of the most valuable skills technicians develop. Students learn a systematic diagnostic process: listen to the customer complaint, inspect the system visually, take measurements, analyze the data, identify the fault, make the repair, and verify the fix. Students analyze common problems including systems not cooling, systems not heating, systems not turning on, and airflow issues.',
    whyItMatters: 'This is the job. Every service call is a troubleshooting exercise. The technician who can systematically diagnose a problem — instead of guessing and replacing parts — saves the company money, earns customer trust, and gets promoted. Parts changers stay at entry level. Diagnosticians become lead techs.',
    tools: [
      { name: 'All Previously Learned Tools', whatItIs: 'Multimeter, amp clamp, gauge manifold, temperature clamps, manometer, combustion analyzer, leak detector.', usedFor: 'Every troubleshooting scenario requires multiple tools. The skill is knowing which tool to grab first based on the symptoms.' },
      { name: 'Troubleshooting Flowchart', whatItIs: 'A step-by-step decision tree that guides diagnosis based on symptoms. Start with the complaint, check the simplest causes first, then work toward more complex possibilities.', usedFor: 'Following a logical diagnostic process instead of guessing. Example: No cooling → Check thermostat → Check power → Check contactor → Check capacitor → Check pressures.' },
    ],
    systems: [
      'No cooling diagnosis — thermostat, power, contactor, capacitor, compressor, refrigerant charge, airflow',
      'No heating diagnosis — thermostat, power, gas supply, ignition, flame sensor, limit switch, heat exchanger',
      'System short cycling — dirty filter, refrigerant overcharge, oversized equipment, failed sensor',
      'High energy bills — dirty coils, low refrigerant, duct leaks, failed insulation',
      'Water leaks — clogged condensate drain, frozen evaporator coil, cracked drain pan',
      'Strange noises — failing bearings, loose parts, refrigerant slugging, expansion/contraction',
    ],
    skills: [
      'Follow a systematic diagnostic process from complaint to verified repair',
      'Diagnose a no-cool system using pressure readings, temperature measurements, and electrical tests',
      'Diagnose a no-heat system using combustion analysis, gas pressure, and ignition sequence verification',
      'Identify the root cause — not just the symptom (example: low refrigerant is a symptom, the leak is the cause)',
      'Verify the repair by running the system and confirming normal operation before leaving',
    ],
    jobTasks: [
      'Arriving at a no-cool service call, interviewing the customer, and beginning systematic diagnosis',
      'Diagnosing a compressor that hums but will not start — testing the capacitor and finding it failed',
      'Finding a frozen evaporator coil and determining the root cause (dirty filter, low charge, or blower problem)',
      'Explaining the diagnosis and repair cost to the customer in plain language',
      'Completing the service ticket with diagnosis, parts used, refrigerant amounts, and labor time',
    ],
  },
  {
    num: 14,
    title: 'Service Call Simulation',
    week: 'Week 14',
    teaches: 'This module simulates real service calls technicians experience in the field. Students learn the complete service call workflow: receiving the dispatch, driving to the job, greeting the customer, inspecting the equipment, diagnosing the problem, recommending repairs, performing the work, verifying the fix, collecting payment, and completing documentation.',
    whyItMatters: 'Knowing how to fix equipment is only half the job. The other half is professionalism — how you communicate with customers, how you present yourself, how you document your work. Employers lose customers over poor communication more often than poor repairs. This module teaches you to be a complete technician, not just a mechanic.',
    tools: [
      { name: 'Service Call Checklist', whatItIs: 'A standardized form that guides the technician through every step of a service call — from arrival to departure.', usedFor: 'Ensuring nothing is missed. Did you check the filter? Did you test the capacitor? Did you verify the repair? Did you clean up your work area?' },
      { name: 'Invoice / Work Order', whatItIs: 'The document that records what was diagnosed, what was repaired, what parts were used, and what the customer owes.', usedFor: 'Professional documentation. This protects you, the company, and the customer. It also creates a service history for the equipment.' },
      { name: 'All Diagnostic Tools', whatItIs: 'Full tool bag — multimeter, gauges, temperature clamps, amp clamp, leak detector.', usedFor: 'Performing the actual diagnosis and repair during the simulated service call.' },
    ],
    systems: [
      'Service call workflow — dispatch, arrival, customer interview, inspection, diagnosis, repair, verification, documentation',
      'Customer communication — how to explain technical problems in plain language',
      'Flat-rate pricing vs. time-and-materials pricing',
      'Warranty vs. non-warranty service calls',
      'When to recommend repair vs. replacement',
    ],
    skills: [
      'Complete a full service call from arrival to departure following professional procedures',
      'Interview a customer to understand their complaint without using jargon',
      'Present repair options and pricing clearly and honestly',
      'Document the service call completely and accurately',
      'Leave the work area cleaner than you found it',
    ],
    jobTasks: [
      'Responding to a dispatch for a no-cool call at a residential home',
      'Greeting the customer, listening to their complaint, and asking clarifying questions',
      'Diagnosing the problem, explaining it to the customer, and getting approval for the repair',
      'Completing the repair, verifying normal operation, and walking the customer through what was done',
      'Completing the invoice and collecting payment or scheduling follow-up',
    ],
  },
  {
    num: 15,
    title: 'Career Readiness and Professional Skills',
    week: 'Week 15',
    teaches: 'Technicians must demonstrate professionalism and workplace readiness. This module prepares students for employment by teaching job search strategies, resume building, interview skills, employer expectations, and workplace communication. Students learn how to interact with customers, document service calls, and present themselves as professionals.',
    whyItMatters: 'You can be the best diagnostician in the class, but if you cannot show up on time, communicate professionally, and present yourself well in an interview, you will not get hired — or you will not keep the job. Employers hire attitude and train skill. This module makes sure you have both.',
    tools: [
      { name: 'Professional Resume', whatItIs: 'A one-page document highlighting your credentials (EPA 608, OSHA 10, CPR), training hours, and skills.', usedFor: 'Applying for HVAC technician positions. Your resume should lead with your certifications, then your training, then any work experience.' },
      { name: 'Interview Preparation Guide', whatItIs: 'Common interview questions for entry-level HVAC positions and how to answer them.', usedFor: 'Practicing answers to questions like "Why did you choose HVAC?", "What would you do if you could not diagnose a problem?", and "How do you handle a difficult customer?"' },
    ],
    systems: [
      'Job search platforms — Indeed, LinkedIn, company websites, WorkOne job board',
      'Employer expectations — punctuality, appearance, communication, work ethic, willingness to learn',
      'Customer service fundamentals — first impressions, active listening, managing expectations',
      'Workplace documentation — service tickets, time sheets, inventory logs',
      'Professional development — continuing education, manufacturer training, advanced certifications (NATE)',
    ],
    skills: [
      'Build a professional resume highlighting HVAC credentials and training',
      'Practice answering common HVAC interview questions confidently',
      'Demonstrate professional communication with customers and supervisors',
      'Understand employer expectations for attendance, appearance, and conduct',
      'Create a 1-year career development plan with specific goals',
    ],
    jobTasks: [
      'Applying for entry-level HVAC technician positions at local companies',
      'Completing a job interview and following up professionally',
      'Showing up to your first day of OJT prepared, on time, and in proper work attire',
      'Communicating with your supervisor about what you know and what you need to learn',
      'Setting goals for your first 90 days on the job',
    ],
  },
  {
    num: 16,
    title: 'Certification Preparation and Final Assessment',
    week: 'Week 16',
    teaches: 'The final module prepares students for the EPA Section 608 certification exam and program completion. Students review key HVAC concepts, safety procedures, refrigerant regulations, and refrigeration cycle knowledge needed to pass the certification exam. This module includes timed practice exams, targeted review of weak areas, and final competency assessments.',
    whyItMatters: 'This is what the entire program has been building toward. The EPA 608 Universal certification is your ticket into the HVAC industry. Without it, you cannot purchase refrigerant, you cannot legally work on cooling systems, and most employers will not hire you. Pass this exam and you are a certified HVAC technician.',
    tools: [
      { name: 'EPA 608 Practice Exam Software', whatItIs: 'Timed practice exams that simulate the real EPA 608 test — 80 questions across 4 sections (Core, Type I, Type II, Type III).', usedFor: 'Building exam confidence and identifying weak areas before the real test. You should be scoring 85%+ consistently before sitting for the proctored exam.' },
      { name: 'Study Guides', whatItIs: 'Section-by-section review materials covering every topic on the EPA 608 exam.', usedFor: 'Targeted review of areas where practice exam scores are lowest. Focus your study time where it matters most.' },
      { name: 'Flashcards', whatItIs: 'Quick-reference cards for refrigerant classifications, pressure-temperature relationships, recovery requirements, and regulatory numbers.', usedFor: 'Memorizing key facts — refrigerant types, ODP values, GWP values, fine amounts, recovery vacuum levels, and leak repair timelines.' },
    ],
    systems: [
      'EPA 608 Core section — ozone depletion, Clean Air Act, recovery/recycling/reclamation, safety, refrigerant properties',
      'EPA 608 Type I — small appliances (under 5 lbs), self-contained recovery, disposal requirements',
      'EPA 608 Type II — high-pressure systems (residential AC, heat pumps, supermarket refrigeration), recovery levels, leak repair',
      'EPA 608 Type III — low-pressure systems (centrifugal chillers), pressurization, standing vacuum test',
      'Program final assessment — comprehensive review of all 16 modules',
    ],
    skills: [
      'Pass timed practice exams for all four EPA 608 sections with 85%+ consistently',
      'Identify and review weak areas using targeted study materials',
      'Demonstrate exam-day time management (80 questions, no time limit but focus matters)',
      'Complete the program final assessment covering all 16 modules',
      'Schedule and sit for the official proctored EPA 608 Universal exam',
    ],
    jobTasks: [
      'Passing the official EPA 608 Universal certification exam',
      'Receiving your EPA certification card and adding it to your resume',
      'Completing employer partner interviews arranged by career services',
      'Beginning OJT placement with a licensed HVAC company',
      'Starting your apprenticeship hour tracking toward journeyman licensure',
    ],
  },
];
