-- PRS checkpoint quiz questions
-- Extracted directly from each checkpoint's script_text.
-- Each question tests exactly what the script_text says the learner must know.
-- 5 questions per checkpoint, 70% pass threshold (4/5 correct).
-- Module 8 final assessment uses 80% threshold per script_text.

DO $outer$
DECLARE
  v_program_id UUID;
BEGIN
  SELECT id INTO v_program_id FROM public.programs WHERE slug = 'peer-recovery-specialist-jri';
  IF v_program_id IS NULL THEN RAISE EXCEPTION 'PRS program not found'; END IF;

  -- ── Module 1: Introduction Quiz ───────────────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q1$[
    {"id":"prs1-q1","question":"What is the primary distinction between peer support and clinical treatment?","options":["Peer support is provided by licensed clinicians","Peer support draws on lived experience of recovery, not clinical credentials","Peer support is only for people in early recovery","Peer support replaces clinical treatment for most conditions"],"correctAnswer":1,"explanation":"Peer support is grounded in shared lived experience of recovery. This is what distinguishes it from clinical treatment, which is provided by credentialed professionals using clinical methods."},
    {"id":"prs1-q2","question":"Which of the following is a recovery-oriented principle in peer support?","options":["Recovery is only possible with medication","Recovery is self-directed and defined by the individual","Recovery requires abstinence from all substances","Recovery is a clinical outcome determined by a provider"],"correctAnswer":1,"explanation":"Recovery-oriented principles center the individual's own definition of recovery. Self-direction — the person choosing their own path — is a core principle of peer support practice."},
    {"id":"prs1-q3","question":"Why does lived experience matter in peer support work?","options":["It allows peers to give clinical advice","It creates credibility and hope — the peer has been where the client is","It means the peer does not need training","It replaces the need for supervision"],"correctAnswer":1,"explanation":"Lived experience creates authentic credibility and instills hope. A peer specialist can say 'I have been where you are and recovery is possible' in a way no clinician can."},
    {"id":"prs1-q4","question":"Which of the following is an early warning sign of boundary drift in peer work?","options":["Maintaining consistent meeting times","Sharing your phone number for after-hours contact without agency approval","Using reflective listening techniques","Documenting all client interactions"],"correctAnswer":1,"explanation":"Sharing personal contact information outside agency protocols is a classic early warning sign of boundary drift. It blurs the professional relationship and creates risk for both the peer and the client."},
    {"id":"prs1-q5","question":"Why does the history of the peer support movement still matter in practice today?","options":["It provides legal protection for peer specialists","It explains why peer support exists outside the clinical system and why that independence matters","It determines certification requirements in every state","It is required content for the CPRS exam only"],"correctAnswer":1,"explanation":"Understanding the history of peer support — rooted in consumer/survivor movements that challenged institutional treatment — explains why peer support operates from a different value base than clinical care. That history shapes current practice."}
  ]$q1$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-1-peer-1-5';

  -- ── Module 2: Ethics Quiz ─────────────────────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q2$[
    {"id":"prs2-q1","question":"What is the primary purpose of a code of ethics for peer recovery specialists?","options":["To protect the agency from liability","To provide a framework for professional conduct and decision-making","To replace supervision","To define clinical treatment protocols"],"correctAnswer":1,"explanation":"A code of ethics provides a shared framework for professional conduct. It guides decision-making in ambiguous situations and establishes the standards the profession holds itself to."},
    {"id":"prs2-q2","question":"Which of the following is one of the three main exceptions to confidentiality in peer support?","options":["The client requests a copy of their records","The client discloses imminent danger to self or others","The client misses a scheduled appointment","The client disagrees with their treatment plan"],"correctAnswer":1,"explanation":"The three main exceptions to confidentiality are: imminent danger to self or others, suspected abuse of a child or vulnerable adult, and a valid court order. Disclosure of imminent danger is the most common exception peers encounter."},
    {"id":"prs2-q3","question":"A peer specialist's cousin enrolls in the same recovery program where the peer works. This is an example of:","options":["A normal professional situation requiring no action","A high-risk dual relationship that must be disclosed and managed","A reason to terminate the cousin's enrollment","A situation that only requires documentation"],"correctAnswer":1,"explanation":"A dual relationship exists when a peer has a personal relationship with someone they also serve professionally. Family relationships are high-risk dual relationships that must be disclosed to a supervisor immediately and managed according to agency policy."},
    {"id":"prs2-q4","question":"When using a stepwise method for ethical problem-solving, what is the correct first step?","options":["Consult a supervisor immediately","Identify and clearly define the ethical issue","Review the agency policy manual","Document the situation in the client record"],"correctAnswer":1,"explanation":"Ethical problem-solving begins with clearly identifying what the ethical issue actually is. Acting before defining the problem leads to poor decisions. Identification comes before consultation, policy review, or documentation."},
    {"id":"prs2-q5","question":"In which situation is supervision required for a peer recovery specialist?","options":["When a client is making good progress","When a peer is uncertain about an ethical boundary or a situation exceeds their scope","When a client requests a different peer specialist","When documentation is overdue"],"correctAnswer":1,"explanation":"Supervision is required when a situation exceeds the peer's scope of practice or when the peer is uncertain about an ethical boundary. Seeking supervision in these moments is a professional obligation, not a sign of weakness."}
  ]$q2$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-2-peer-2-5';

  -- ── Module 3: Recovery Models Quiz ───────────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q3$[
    {"id":"prs3-q1","question":"Which recovery model emphasizes that recovery is a process of change through which individuals improve their health and wellness and live a self-directed life?","options":["The medical model","SAMHSA's working definition of recovery","The abstinence-only model","The 12-step model"],"correctAnswer":1,"explanation":"SAMHSA defines recovery as a process of change through which individuals improve their health and wellness, live self-directed lives, and strive to reach their full potential. This definition is broader than any single model and is the foundation of peer support practice."},
    {"id":"prs3-q2","question":"A client says they are thinking about cutting back on drinking but are not ready to quit. Which stage of change are they in?","options":["Precontemplation","Contemplation","Preparation","Action"],"correctAnswer":1,"explanation":"Contemplation is the stage where a person is aware a problem exists and is thinking about change but has not committed to action. The peer's role is to explore ambivalence, not push for action."},
    {"id":"prs3-q3","question":"Which of the eight dimensions of wellness includes employment, finances, and sense of purpose?","options":["Physical","Occupational","Social","Intellectual"],"correctAnswer":1,"explanation":"The Occupational dimension of wellness encompasses work, volunteerism, and activities that provide personal satisfaction and enrichment. Financial stability and sense of purpose are part of this dimension."},
    {"id":"prs3-q4","question":"Why is self-care described as a professional obligation for peer recovery specialists?","options":["It is required by the CPRS certification exam","A peer who neglects their own wellness cannot effectively support others and is at higher risk for burnout and relapse","It is required by agency policy in most states","It is only relevant for peers in early recovery"],"correctAnswer":1,"explanation":"Peer specialists who neglect their own wellness are at higher risk for compassion fatigue, burnout, and their own recovery challenges. Self-care is not optional — it is part of professional practice and protects both the peer and the people they serve."},
    {"id":"prs3-q5","question":"In relapse prevention, what is the difference between a trigger and a warning sign?","options":["They are the same thing","A trigger is an external or internal cue that activates craving; a warning sign is a behavioral or emotional change that signals increasing risk","A trigger is always a person; a warning sign is always a place","Warning signs come before triggers in the relapse process"],"correctAnswer":1,"explanation":"Triggers are stimuli (people, places, emotions, situations) that activate craving or urge to use. Warning signs are the behavioral and emotional changes — like isolation, irritability, or skipping meetings — that indicate the person is moving toward relapse. Both must be identified in a relapse prevention plan."}
  ]$q3$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-3-peer-3-5';

  -- ── Module 4: Peer Support Practice (scenario-based) ─────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q4$[
    {"id":"prs4-q1","question":"A client discloses they have been using again and expresses shame. What is the most appropriate peer response?","options":["Tell them they need to go back to treatment immediately","Reflect their feelings without judgment and explore what happened without problem-solving","Remind them of the consequences of relapse","Ask them why they made that choice"],"correctAnswer":1,"explanation":"Active listening and reflective response without jumping to problem-solving is the correct approach. The client needs to feel heard and not judged before they can engage in problem-solving. Shame is a barrier to recovery — the peer's job is to reduce it, not reinforce it."},
    {"id":"prs4-q2","question":"A client says nothing has worked before and they do not see the point of treatment. Which motivational interviewing technique is most appropriate?","options":["Confronting their resistance directly","Rolling with resistance — reflecting their ambivalence and exploring their own reasons for change","Providing a list of treatment success statistics","Telling them about your own recovery to motivate them"],"correctAnswer":1,"explanation":"Rolling with resistance means not arguing against the client's position. Instead, reflect their ambivalence and use open questions to help them explore their own reasons for change. Arguing increases resistance; rolling with it reduces it."},
    {"id":"prs4-q3","question":"A client asks about your own recovery history. What is the principle that guides your response?","options":["Never disclose anything personal","Strategic self-disclosure — share something useful to the client without over-disclosing","Always share your full story to build trust","Redirect the question back to the client immediately"],"correctAnswer":1,"explanation":"Strategic self-disclosure means sharing personal experience intentionally and purposefully — only what serves the client's recovery, not what meets the peer's need to be understood. Over-disclosure shifts focus from the client to the peer and blurs professional boundaries."},
    {"id":"prs4-q4","question":"A new client gives one-word answers and seems guarded. What is the most effective approach?","options":["Ask more direct questions to get more information","Practice patience, consistency, and genuine curiosity — rapport takes time","Tell them that engagement is required for the program","Refer them to a different peer specialist"],"correctAnswer":1,"explanation":"Rapport with guarded clients is built through patience, consistency, and genuine curiosity — not pressure. Showing up reliably, asking open questions without urgency, and demonstrating that you are not going anywhere is how trust develops over time."},
    {"id":"prs4-q5","question":"Which of the following best describes the OARS technique in motivational interviewing?","options":["Observe, Assess, Reflect, Summarize","Open questions, Affirmations, Reflective listening, Summaries","Outline, Agree, Resolve, Support","Orient, Advise, Reinforce, Stabilize"],"correctAnswer":1,"explanation":"OARS stands for Open questions, Affirmations, Reflective listening, and Summaries. These are the four core communication skills in motivational interviewing that build engagement and help clients explore their own motivation for change."}
  ]$q4$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-4-peer-4-5';

  -- ── Module 5: Advocacy Quiz ───────────────────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q5$[
    {"id":"prs5-q1","question":"What is the difference between self-advocacy and systems advocacy?","options":["They are the same thing","Self-advocacy is speaking up for your own needs and rights; systems advocacy is working to change policies and structures that affect many people","Self-advocacy is only for clients; systems advocacy is only for professionals","Systems advocacy requires a law degree"],"correctAnswer":1,"explanation":"Self-advocacy is the skill of identifying and communicating your own needs and rights. Systems advocacy is working to change the policies, structures, and practices that create barriers for people in recovery. Peer specialists do both."},
    {"id":"prs5-q2","question":"Which of the following is a participant right in behavioral health settings?","options":["The right to receive any treatment they request","The right to be informed about their treatment, to consent or refuse, and to receive services free from discrimination","The right to choose their own clinician in all settings","The right to access any medication they prefer"],"correctAnswer":1,"explanation":"Participants in behavioral health services have the right to informed consent, the right to refuse treatment, and the right to receive services free from discrimination. Peer specialists help clients understand and exercise these rights."},
    {"id":"prs5-q3","question":"A client does not know they can request a copy of their treatment records. What is the peer's role?","options":["Obtain the records on the client's behalf","Inform the client of their right to access their records and support them in making the request","Tell the client to ask their clinician","Advise the client that records are confidential and cannot be shared"],"correctAnswer":1,"explanation":"Self-advocacy skill-building means helping clients understand their rights and supporting them to exercise those rights themselves. The peer informs and supports — they do not act on the client's behalf unless specifically authorized."},
    {"id":"prs5-q4","question":"A client repeatedly encounters the same barrier — a local agency requires a state ID for services but many clients cannot get one. What is the appropriate systems advocacy response?","options":["Tell each client individually how to get an ID","Document the pattern and escalate it to a supervisor or advocacy body as a systemic barrier","Advise clients to use a different agency","Accept that this is how the system works"],"correctAnswer":1,"explanation":"When the same barrier affects multiple clients, it is a systemic issue. The peer's role is to document the pattern and escalate it through appropriate channels — supervisor, agency leadership, or advocacy organizations — so the barrier can be addressed at the policy level."},
    {"id":"prs5-q5","question":"Which of the following best describes the peer specialist's role in advocacy?","options":["To make decisions for clients who cannot advocate for themselves","To amplify the client's own voice and build their capacity to advocate for themselves","To represent clients in legal proceedings","To file complaints on behalf of clients without their knowledge"],"correctAnswer":1,"explanation":"The peer's advocacy role is to amplify the client's voice and build their capacity to advocate for themselves — not to speak for them or make decisions on their behalf. Empowerment, not dependency, is the goal."}
  ]$q5$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-5-peer-5-5';

  -- ── Module 6: Resource Mapping Practice ──────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q6$[
    {"id":"prs6-q1","question":"What is the purpose of resource mapping in peer support work?","options":["To create a database of all services in the state","To identify and document local resources so peers can connect clients to appropriate services efficiently","To replace the need for referrals","To track which agencies have the most funding"],"correctAnswer":1,"explanation":"Resource mapping is the process of identifying, documenting, and organizing local services so that peers can make timely, appropriate connections for clients. A good resource map is a living document updated regularly."},
    {"id":"prs6-q2","question":"What is a warm handoff and why does it matter?","options":["A referral letter sent by mail","A direct, personal introduction of the client to the receiving service — either in person or by phone — rather than just giving them a phone number","A follow-up call made 30 days after a referral","A written summary of the client's history sent to the new provider"],"correctAnswer":1,"explanation":"A warm handoff is a direct, personal introduction that bridges the client to the new service. It matters because clients in recovery often face barriers to following through on referrals. A warm handoff dramatically increases the likelihood the client actually connects with the service."},
    {"id":"prs6-q3","question":"A client needs housing but has an eviction on their record. Which approach best addresses this barrier?","options":["Tell the client there are no options for people with evictions","Identify agencies that specifically serve people with housing barriers and support the client in making contact","Advise the client to wait until the eviction is off their record","Refer the client to a general housing hotline"],"correctAnswer":1,"explanation":"Barriers to service access require targeted resource knowledge. The peer's role is to know which agencies serve people with specific barriers — not to accept the barrier as a dead end. Identifying the right resource and supporting the client in making contact is the correct approach."},
    {"id":"prs6-q4","question":"After making a referral, what is the peer's documentation responsibility?","options":["No documentation is needed for referrals","Document the referral in the client record including the agency, date, method of contact, and planned follow-up","Only document if the client successfully connects with the service","Ask the receiving agency to document on your behalf"],"correctAnswer":1,"explanation":"Every referral must be documented: the agency referred to, the date, how contact was made (warm handoff, phone, written), and the planned follow-up date. Documentation creates accountability and allows the peer to track whether the client connected with the service."},
    {"id":"prs6-q5","question":"A client was referred to a service two weeks ago but has not followed up. What should the peer do?","options":["Close the referral as complete","Follow up with the client to find out what happened and address any barriers that prevented connection","Refer the client to a different service without discussion","Document that the client refused services"],"correctAnswer":1,"explanation":"Follow-up is part of the referral process. If a client has not connected with a referred service, the peer follows up to understand what happened — transportation, fear, paperwork, a bad first interaction — and helps address the barrier. Closing a referral without follow-up is incomplete practice."}
  ]$q6$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-6-peer-6-4';

  -- ── Module 7: Crisis Response Quiz ───────────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q7$[
    {"id":"prs7-q1","question":"What is the peer recovery specialist's role in a crisis situation?","options":["To provide clinical crisis intervention","To support, stabilize, and connect — not to assess or treat — and to know when to involve clinical staff or emergency services","To make independent decisions about hospitalization","To manage the crisis without involving supervisors to protect confidentiality"],"correctAnswer":1,"explanation":"The PRS role in crisis is to support and stabilize the person, not to provide clinical crisis intervention. Peers support, connect to appropriate resources, and involve clinical staff or emergency services when the situation exceeds their scope. Knowing the limits of the role is essential."},
    {"id":"prs7-q2","question":"A client discloses they have been thinking about suicide. What is the correct first response?","options":["Call 911 immediately","Stay calm, take the disclosure seriously, ask directly about plan and intent, and involve clinical staff or emergency services based on the level of risk","Tell the client that suicidal thoughts are normal and will pass","Document the disclosure and address it at the next scheduled meeting"],"correctAnswer":1,"explanation":"When a client discloses suicidal ideation, the peer stays calm, takes it seriously, and asks directly about plan and intent. The response is calibrated to the level of risk — not every disclosure requires 911, but all require immediate clinical involvement. Never minimize or delay."},
    {"id":"prs7-q3","question":"Which of the following is a de-escalation principle?","options":["Match the client's emotional intensity to show empathy","Use a calm tone, reduce stimulation, give the person space, and avoid power struggles","Establish authority immediately to create safety","Move quickly to resolve the situation"],"correctAnswer":1,"explanation":"De-escalation involves reducing emotional intensity, not matching it. A calm tone, reduced stimulation, physical space, and avoiding power struggles are core principles. The goal is to lower arousal so the person can engage with support."},
    {"id":"prs7-q4","question":"A peer specialist learns that a client is being physically abused by a family member. What is the mandatory reporting obligation?","options":["Report only if the client gives permission","Report to the appropriate authority — child protective services or adult protective services — regardless of client consent, as required by law","Advise the client to report it themselves","Document the disclosure and discuss it with a supervisor before taking any action"],"correctAnswer":1,"explanation":"Abuse of a child or vulnerable adult is a mandatory reporting situation. The peer is legally required to report to the appropriate authority regardless of client consent. This is one of the three main exceptions to confidentiality. Supervisor consultation should happen alongside reporting, not instead of it."},
    {"id":"prs7-q5","question":"After a crisis interaction, what should the peer do?","options":["Return to normal duties immediately","Debrief with a supervisor, document the interaction, and attend to their own wellbeing","Only document if the crisis resulted in hospitalization","Wait for the client to follow up before taking any action"],"correctAnswer":1,"explanation":"After a crisis interaction, the peer debriefs with a supervisor (required), documents the interaction fully, and attends to their own wellbeing. Crisis work is emotionally demanding. Supervision and self-care after a crisis are professional obligations, not optional."}
  ]$q7$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-7-peer-7-5';

  -- ── Module 8: Final Competency Assessment ────────────────────────────────
  UPDATE public.curriculum_lessons SET quiz_questions = $q8$[
    {"id":"prs8-q1","question":"A client in early recovery tells you they are thinking about reconnecting with old friends who still use. Using your knowledge of relapse prevention, what is the most appropriate response?","options":["Tell them not to see those friends under any circumstances","Explore the ambivalence with them — acknowledge the pull of connection while helping them identify the risk and develop a plan","Refer them immediately to a higher level of care","Document the concern and wait to see what happens"],"correctAnswer":1,"explanation":"This question integrates relapse prevention (Module 3) with motivational interviewing (Module 4). The peer explores ambivalence without issuing directives. The client must arrive at their own decision. The peer helps them see the risk clearly and develop their own plan."},
    {"id":"prs8-q2","question":"A client discloses that their case manager has been sharing their information with family members without consent. What is the peer's role?","options":["Advise the client to find a new case manager","Inform the client of their confidentiality rights, support them in documenting the violation, and help them file a complaint if they choose","Contact the case manager directly on the client's behalf","Tell the client this is normal practice in behavioral health settings"],"correctAnswer":1,"explanation":"This integrates ethics (Module 2) with advocacy (Module 5). The peer informs the client of their rights, supports them in documenting the violation, and helps them exercise their right to file a complaint — without acting on their behalf without authorization."},
    {"id":"prs8-q3","question":"You are working with a client who has been stable for six months. They tell you they feel ready to reduce their peer support sessions. What is the appropriate response?","options":["Encourage them to continue at the current frequency to prevent relapse","Support their self-determination — explore what readiness looks like to them, discuss a transition plan, and ensure they have resources if they need support in the future","Tell them the decision must be made by their clinical team","Document the request and continue sessions until a supervisor approves the change"],"correctAnswer":1,"explanation":"Self-determination is a core recovery principle (Module 1). A client who feels ready to reduce services is exercising their right to direct their own recovery. The peer supports this by exploring readiness, co-creating a transition plan, and ensuring the client knows how to re-engage if needed."},
    {"id":"prs8-q4","question":"A client from a different cultural background than yours describes a healing practice that is not part of mainstream recovery programming. What is the culturally responsive approach?","options":["Explain that evidence-based practices are more effective","Express genuine curiosity, learn about the practice, and explore how it can be integrated into their recovery plan","Refer them to a peer specialist from the same background","Document the practice as a potential barrier to treatment engagement"],"correctAnswer":1,"explanation":"Cultural responsiveness (Module 7) requires genuine curiosity and openness to healing practices outside mainstream frameworks. The peer's role is to support the client's whole recovery, which may include cultural, spiritual, or community-based practices. Dismissing these practices is a barrier to engagement."},
    {"id":"prs8-q5","question":"You have completed your PRS training. What are the required next steps to become a credentialed Peer Recovery Specialist in Indiana?","options":["Begin working immediately — training is sufficient for employment","Complete supervised practicum hours, submit a CPRS application to IC&RC through DMHA, and pass the CPRS exam","Pass only the CPRS exam — practicum hours are optional","Submit an application directly to your employer"],"correctAnswer":1,"explanation":"Indiana CPRS credentialing requires: (1) completion of approved training, (2) supervised practicum hours, (3) application to IC&RC through Indiana DMHA, and (4) passing the CPRS exam. Training alone is not sufficient for credentialing."}
  ]$q8$::jsonb, updated_at = now()
  WHERE program_id = v_program_id AND lesson_slug = 'peer-mod-8-peer-8-5';

  RAISE NOTICE 'PRS checkpoint quizzes written for all 8 lessons';
END $outer$;

-- Verify
SELECT lesson_slug, lesson_title, jsonb_array_length(quiz_questions) AS q_count
FROM curriculum_lessons
WHERE program_id = (SELECT id FROM programs WHERE slug = 'peer-recovery-specialist-jri')
  AND step_type = 'checkpoint'
  AND status = 'published'
ORDER BY module_order;
