#!/usr/bin/env tsx
/**
 * scripts/seed-course-from-blueprint.ts
 *
 * End-to-end course seeder. Reads a blueprint from the registry and writes
 * courses → course_modules → course_lessons via buildCanonicalCourseFromBlueprint.
 *
 * Every lesson row gets:
 *   - lesson_type (inferred from slug suffix)
 *   - activities JSONB (NHA-style activity menu)
 *   - video_config JSONB (locked video format from blueprint)
 *
 * Usage:
 *   pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint hvac-epa608-v1 --program 4226f7f6-fbc1-44b5-83e8-b12ea149e4c7
 *   pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint hvac-epa608-v1 --program 4226f7f6-fbc1-44b5-83e8-b12ea149e4c7 --mode replace
 *
 * Flags:
 *   --blueprint  Blueprint ID or program slug (required)
 *   --program    programs.id to link the course to (required)
 *   --mode       'missing-only' (default, safe to re-run) | 'replace' (wipes and rebuilds)
 *   --dry-run    Print what would be written without touching the DB
 */

import { config } from 'dotenv';
import path from 'path';

// Load .env.local
config({ path: path.resolve(process.cwd(), '.env.local') });

import { getBlueprintById, getBlueprintByProgramSlug, getAllBlueprints } from '../lib/curriculum/blueprints/index';
import { buildCanonicalCourseFromBlueprint } from '../lib/curriculum/builders/buildCanonicalCourseFromBlueprint';

// ── Parse args ────────────────────────────────────────────────────────

const args = process.argv.slice(2);

function getArg(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : undefined;
}

const blueprintArg = getArg('--blueprint');
const programId    = getArg('--program');
const modeArg      = getArg('--mode') ?? 'missing-only';
const dryRun       = args.includes('--dry-run');
const listBlueprints = args.includes('--list');

if (listBlueprints) {
  console.log('\nAvailable blueprints:');
  getAllBlueprints().forEach(bp => {
    console.log(`  ${bp.id.padEnd(30)} slug=${bp.programSlug}  modules=${bp.modules.length}`);
  });
  process.exit(0);
}

if (!blueprintArg || !programId) {
  console.error('\nUsage: pnpm tsx scripts/seed-course-from-blueprint.ts --blueprint <id> --program <programId> [--mode replace|missing-only] [--dry-run]');
  console.error('       pnpm tsx scripts/seed-course-from-blueprint.ts --list\n');
  process.exit(1);
}

if (modeArg !== 'replace' && modeArg !== 'missing-only') {
  console.error('--mode must be "replace" or "missing-only"');
  process.exit(1);
}

// ── Resolve blueprint ─────────────────────────────────────────────────

const blueprint = getBlueprintById(blueprintArg) ?? getBlueprintByProgramSlug(blueprintArg);

if (!blueprint) {
  console.error(`\nNo blueprint found for "${blueprintArg}"`);
  console.error('Run with --list to see available blueprints.\n');
  process.exit(1);
}

// ── Dry run ───────────────────────────────────────────────────────────

if (dryRun) {
  console.log('\n── DRY RUN ──────────────────────────────────────────────');
  console.log(`Blueprint : ${blueprint.id} v${blueprint.version}`);
  console.log(`Program   : ${programId}`);
  console.log(`Mode      : ${modeArg}`);
  console.log(`Modules   : ${blueprint.modules.length}`);
  let totalLessons = 0;
  blueprint.modules.forEach(mod => {
    const count = mod.lessons?.length ?? 0;
    totalLessons += count;
    console.log(`  [${mod.orderIndex}] ${mod.title} — ${count > 0 ? count + ' lessons' : `${mod.minLessons}–${mod.maxLessons} lessons (generated)`}`);
  });
  console.log(`Lessons   : ${totalLessons > 0 ? totalLessons : 'generated by AI (no pre-defined lessons)'}`);
  console.log(`VideoConfig: ${blueprint.videoConfig ? `${blueprint.videoConfig.template} / ${blueprint.videoConfig.instructorName}` : 'none'}`);
  console.log('─────────────────────────────────────────────────────────\n');
  process.exit(0);
}

// ── Run ───────────────────────────────────────────────────────────────

async function main() {
  console.log(`\nSeeding course from blueprint: ${blueprint!.id}`);
  console.log(`Program ID : ${programId}`);
  console.log(`Mode       : ${modeArg}`);
  console.log(`Modules    : ${blueprint!.modules.length}`);
  console.log('');

  const result = await buildCanonicalCourseFromBlueprint({
    blueprint: blueprint!,
    programId: programId!,
    courseSlug: blueprint!.programSlug,
    mode: modeArg as 'replace' | 'missing-only',
  });

  console.log('✅ Done');
  console.log(`   Course ID    : ${result.courseId}`);
  console.log(`   Modules      : ${result.moduleCount}`);
  console.log(`   Lessons      : ${result.lessonCount}`);
  console.log(`   Skipped      : ${result.skipped}`);
  if (result.warnings.length > 0) {
    console.log(`\n⚠️  Warnings (${result.warnings.length}):`);
    result.warnings.forEach(w => console.log(`   - ${w}`));
  }
  console.log('');
}

main().catch(err => {
  console.error('\n❌ Seed failed:', err.message);
  process.exit(1);
});
