'use client';

/**
 * HvacLessonVideo
 *
 * Resolves the best available media for an HVAC lesson and plays it
 * through the existing LessonPlayer. Zero new dependencies, zero API
 * keys required at runtime.
 *
 * Priority (checked via HEAD request against static files):
 *   1. /generated/videos/lesson-{uuid}.mp4  — D-ID talking-head video
 *      Marcus Johnson on screen, mouth moving, lesson-specific content.
 *      Generated by: npx tsx scripts/generate-hvac-videos-did.ts
 *
 *   2. /generated/lessons/lesson-{uuid}.mp3 — lesson-specific voiceover
 *      Marcus voice reading the lesson script over b-roll video.
 *      Generated by: npx tsx scripts/generate-hvac-audio.ts
 *
 *   3. brollVideoUrl                         — b-roll video fallback
 *      Always available, always plays. No generation needed.
 *
 * Both generation scripts are run automatically on environment start
 * via .ona/automations.yaml. Once generated, files are committed to
 * the repo and served as static assets forever.
 */

import React, { useState, useEffect } from 'react';
import LessonPlayer from '@/components/lms/LessonPlayer';
import { HVAC_LESSON_UUID } from '@/lib/courses/hvac-uuids';

interface Props {
  lessonDefId: string;
  brollVideoUrl: string;
  lessonTitle: string;
  onProgress?: (percent: number) => void;
  onComplete?: () => void;
}

export default function HvacLessonVideo({
  lessonDefId,
  brollVideoUrl,
  lessonTitle,
  onProgress,
  onComplete,
}: Props) {
  const [mediaUrl, setMediaUrl] = useState<string | null>(null);

  useEffect(() => {
    const uuid = HVAC_LESSON_UUID[lessonDefId];
    if (!uuid) {
      setMediaUrl(brollVideoUrl);
      return;
    }

    const videoPath = `/generated/videos/lesson-${uuid}.mp4`;
    const audioPath = `/generated/lessons/lesson-${uuid}.mp3`;

    // Check MP4 first, then MP3, then fall back to b-roll.
    // HEAD requests are instant — no download, no API call.
    fetch(videoPath, { method: 'HEAD' })
      .then(r => {
        if (r.ok) { setMediaUrl(videoPath); return; }
        return fetch(audioPath, { method: 'HEAD' })
          .then(r2 => setMediaUrl(r2.ok ? audioPath : brollVideoUrl))
          .catch(() => setMediaUrl(brollVideoUrl));
      })
      .catch(() => {
        fetch(audioPath, { method: 'HEAD' })
          .then(r => setMediaUrl(r.ok ? audioPath : brollVideoUrl))
          .catch(() => setMediaUrl(brollVideoUrl));
      });
  }, [lessonDefId, brollVideoUrl]);

  if (!mediaUrl) return null;

  return (
    <LessonPlayer
      videoUrl={mediaUrl}
      lessonTitle={lessonTitle}
      onProgress={onProgress}
      onComplete={onComplete}
    />
  );
}
