-- Seed remaining Tax Preparer Training courses: advanced-returns, business-returns, software-mastery

-- Advanced Tax Strategies (advanced-returns) - 20 lessons
INSERT INTO training_lessons (course_id, lesson_number, title, content, duration_minutes, topics, quiz_questions) VALUES
('advanced-returns', 1, 'Rental Property Income and Expenses', '<h2>Learning Objectives</h2><ul><li>Complete Schedule E for rental income</li><li>Identify deductible rental expenses</li><li>Calculate net rental income</li></ul><h2>Key Concepts</h2><p>Rental income is reported on Schedule E. Deductible expenses include mortgage interest, property taxes, insurance, repairs, and depreciation.</p>', 45, ARRAY['Schedule E', 'rental income'], '[]'::jsonb),
('advanced-returns', 2, 'Depreciation and Section 179', '<h2>Learning Objectives</h2><ul><li>Calculate depreciation for rental property</li><li>Apply Section 179 deduction</li><li>Understand MACRS depreciation</li></ul>', 45, ARRAY['depreciation', 'Section 179', 'MACRS'], '[]'::jsonb),
('advanced-returns', 3, 'Capital Gains and Losses', '<h2>Learning Objectives</h2><ul><li>Distinguish short-term vs long-term gains</li><li>Complete Schedule D</li><li>Apply capital loss limitations</li></ul>', 45, ARRAY['capital gains', 'Schedule D'], '[]'::jsonb),
('advanced-returns', 4, 'Form 8949 for Investment Sales', '<h2>Learning Objectives</h2><ul><li>Complete Form 8949</li><li>Report stock and bond sales</li><li>Calculate cost basis</li></ul>', 45, ARRAY['Form 8949', 'investments'], '[]'::jsonb),
('advanced-returns', 5, 'Cryptocurrency Taxation', '<h2>Learning Objectives</h2><ul><li>Report cryptocurrency transactions</li><li>Calculate crypto gains/losses</li><li>Understand IRS crypto guidance</li></ul>', 45, ARRAY['cryptocurrency', 'virtual currency'], '[]'::jsonb),
('advanced-returns', 6, 'Stock Options and RSUs', '<h2>Learning Objectives</h2><ul><li>Report ISO and NQSO exercises</li><li>Calculate RSU income</li><li>Understand AMT implications</li></ul>', 45, ARRAY['stock options', 'RSU', 'ISO'], '[]'::jsonb),
('advanced-returns', 7, 'Qualified Business Income Deduction', '<h2>Learning Objectives</h2><ul><li>Calculate QBI deduction</li><li>Apply income limitations</li><li>Identify qualified trades</li></ul>', 45, ARRAY['QBI', 'Section 199A'], '[]'::jsonb),
('advanced-returns', 8, 'Home Office Deduction', '<h2>Learning Objectives</h2><ul><li>Determine home office eligibility</li><li>Calculate simplified vs regular method</li><li>Document home office use</li></ul>', 45, ARRAY['home office', 'Form 8829'], '[]'::jsonb),
('advanced-returns', 9, 'Vehicle Expenses', '<h2>Learning Objectives</h2><ul><li>Compare actual vs standard mileage</li><li>Track business mileage</li><li>Calculate vehicle deduction</li></ul>', 45, ARRAY['vehicle expenses', 'mileage'], '[]'::jsonb),
('advanced-returns', 10, 'Multi-State Tax Returns', '<h2>Learning Objectives</h2><ul><li>Determine state residency</li><li>Allocate income between states</li><li>Claim credit for taxes paid</li></ul>', 45, ARRAY['multi-state', 'state taxes'], '[]'::jsonb),
('advanced-returns', 11, 'Part-Year Resident Returns', '<h2>Learning Objectives</h2><ul><li>Complete part-year returns</li><li>Allocate income by period</li><li>Apply state rules</li></ul>', 45, ARRAY['part-year resident'], '[]'::jsonb),
('advanced-returns', 12, 'Nonresident State Returns', '<h2>Learning Objectives</h2><ul><li>Identify nonresident filing requirements</li><li>Report state-source income</li><li>Complete nonresident forms</li></ul>', 45, ARRAY['nonresident'], '[]'::jsonb),
('advanced-returns', 13, 'Retirement Distributions', '<h2>Learning Objectives</h2><ul><li>Report Form 1099-R</li><li>Calculate taxable portion</li><li>Apply early withdrawal penalties</li></ul>', 45, ARRAY['1099-R', 'retirement'], '[]'::jsonb),
('advanced-returns', 14, 'Social Security Taxation', '<h2>Learning Objectives</h2><ul><li>Calculate taxable Social Security</li><li>Apply provisional income test</li><li>Report SSA-1099</li></ul>', 45, ARRAY['Social Security', 'SSA-1099'], '[]'::jsonb),
('advanced-returns', 15, 'Health Savings Accounts', '<h2>Learning Objectives</h2><ul><li>Report HSA contributions</li><li>Calculate HSA deduction</li><li>Report HSA distributions</li></ul>', 45, ARRAY['HSA', 'Form 8889'], '[]'::jsonb),
('advanced-returns', 16, 'Alternative Minimum Tax', '<h2>Learning Objectives</h2><ul><li>Calculate AMT</li><li>Identify AMT preferences</li><li>Complete Form 6251</li></ul>', 45, ARRAY['AMT', 'Form 6251'], '[]'::jsonb),
('advanced-returns', 17, 'Net Investment Income Tax', '<h2>Learning Objectives</h2><ul><li>Calculate NIIT</li><li>Identify investment income</li><li>Apply MAGI thresholds</li></ul>', 45, ARRAY['NIIT', 'investment tax'], '[]'::jsonb),
('advanced-returns', 18, 'Self-Employment Tax Calculations', '<h2>Learning Objectives</h2><ul><li>Calculate SE tax</li><li>Apply SE tax deduction</li><li>Complete Schedule SE</li></ul>', 45, ARRAY['self-employment tax', 'Schedule SE'], '[]'::jsonb),
('advanced-returns', 19, 'Estimated Tax Payments', '<h2>Learning Objectives</h2><ul><li>Calculate estimated payments</li><li>Avoid underpayment penalty</li><li>Complete Form 2210</li></ul>', 45, ARRAY['estimated tax', 'Form 2210'], '[]'::jsonb),
('advanced-returns', 20, 'Practice: Complex Return', '<h2>Learning Objectives</h2><ul><li>Complete return with rental and investments</li><li>Apply multiple schedules</li><li>Verify accuracy</li></ul>', 60, ARRAY['practice return', 'complex return'], '[]'::jsonb)
ON CONFLICT (course_id, lesson_number) DO NOTHING;

-- Business Tax Mastery (business-returns) - 25 lessons
INSERT INTO training_lessons (course_id, lesson_number, title, content, duration_minutes, topics, quiz_questions) VALUES
('business-returns', 1, 'Business Entity Types Overview', '<h2>Learning Objectives</h2><ul><li>Compare sole proprietor, partnership, S-corp, C-corp</li><li>Understand tax implications of each</li><li>Advise clients on entity selection</li></ul>', 45, ARRAY['business entities', 'entity selection'], '[]'::jsonb),
('business-returns', 2, 'Schedule C for Sole Proprietors', '<h2>Learning Objectives</h2><ul><li>Complete Schedule C</li><li>Report business income and expenses</li><li>Calculate net profit</li></ul>', 45, ARRAY['Schedule C', 'sole proprietor'], '[]'::jsonb),
('business-returns', 3, 'Business Income and Expense Categories', '<h2>Learning Objectives</h2><ul><li>Categorize business expenses</li><li>Apply IRS expense rules</li><li>Maximize deductions</li></ul>', 45, ARRAY['business expenses', 'deductions'], '[]'::jsonb),
('business-returns', 4, 'Cost of Goods Sold', '<h2>Learning Objectives</h2><ul><li>Calculate COGS</li><li>Track inventory</li><li>Apply inventory methods</li></ul>', 45, ARRAY['COGS', 'inventory'], '[]'::jsonb),
('business-returns', 5, 'Business Use of Home', '<h2>Learning Objectives</h2><ul><li>Calculate home office for business</li><li>Complete Form 8829</li><li>Apply simplified method</li></ul>', 45, ARRAY['home office', 'Form 8829'], '[]'::jsonb),
('business-returns', 6, 'Business Vehicle Expenses', '<h2>Learning Objectives</h2><ul><li>Track business vehicle use</li><li>Calculate depreciation</li><li>Apply listed property rules</li></ul>', 45, ARRAY['vehicle expenses', 'listed property'], '[]'::jsonb),
('business-returns', 7, 'Form 1065 for Partnerships', '<h2>Learning Objectives</h2><ul><li>Complete Form 1065</li><li>Understand partnership taxation</li><li>Allocate income to partners</li></ul>', 45, ARRAY['Form 1065', 'partnership'], '[]'::jsonb),
('business-returns', 8, 'Partnership K-1s', '<h2>Learning Objectives</h2><ul><li>Prepare Schedule K-1</li><li>Report partner allocations</li><li>Understand K-1 boxes</li></ul>', 45, ARRAY['K-1', 'partnership'], '[]'::jsonb),
('business-returns', 9, 'Form 1120S for S-Corporations', '<h2>Learning Objectives</h2><ul><li>Complete Form 1120S</li><li>Understand S-corp taxation</li><li>Calculate shareholder basis</li></ul>', 45, ARRAY['Form 1120S', 'S-corporation'], '[]'::jsonb),
('business-returns', 10, 'S-Corp Shareholder Basis', '<h2>Learning Objectives</h2><ul><li>Calculate shareholder basis</li><li>Track basis adjustments</li><li>Apply loss limitations</li></ul>', 45, ARRAY['shareholder basis', 'S-corp'], '[]'::jsonb),
('business-returns', 11, 'Form 1120 for C-Corporations', '<h2>Learning Objectives</h2><ul><li>Complete Form 1120</li><li>Calculate corporate tax</li><li>Understand double taxation</li></ul>', 45, ARRAY['Form 1120', 'C-corporation'], '[]'::jsonb),
('business-returns', 12, 'Corporate Tax Rates', '<h2>Learning Objectives</h2><ul><li>Apply 21% corporate rate</li><li>Calculate corporate tax liability</li><li>Understand corporate credits</li></ul>', 45, ARRAY['corporate tax', 'tax rates'], '[]'::jsonb),
('business-returns', 13, 'Payroll Tax Basics', '<h2>Learning Objectives</h2><ul><li>Calculate payroll taxes</li><li>Understand employer obligations</li><li>Apply deposit rules</li></ul>', 45, ARRAY['payroll tax', 'FICA'], '[]'::jsonb),
('business-returns', 14, 'Form 941 Quarterly Payroll', '<h2>Learning Objectives</h2><ul><li>Complete Form 941</li><li>Report quarterly payroll</li><li>Calculate deposits</li></ul>', 45, ARRAY['Form 941', 'quarterly payroll'], '[]'::jsonb),
('business-returns', 15, 'Form 940 Unemployment Tax', '<h2>Learning Objectives</h2><ul><li>Complete Form 940</li><li>Calculate FUTA tax</li><li>Apply state credit</li></ul>', 45, ARRAY['Form 940', 'FUTA'], '[]'::jsonb),
('business-returns', 16, 'W-2 and W-3 Preparation', '<h2>Learning Objectives</h2><ul><li>Prepare Form W-2</li><li>Complete Form W-3</li><li>Meet filing deadlines</li></ul>', 45, ARRAY['W-2', 'W-3'], '[]'::jsonb),
('business-returns', 17, '1099-NEC for Contractors', '<h2>Learning Objectives</h2><ul><li>Determine 1099 requirements</li><li>Prepare Form 1099-NEC</li><li>File with IRS</li></ul>', 45, ARRAY['1099-NEC', 'contractors'], '[]'::jsonb),
('business-returns', 18, 'Sales Tax Obligations', '<h2>Learning Objectives</h2><ul><li>Understand nexus rules</li><li>Calculate sales tax</li><li>File state returns</li></ul>', 45, ARRAY['sales tax', 'nexus'], '[]'::jsonb),
('business-returns', 19, 'Business Tax Credits', '<h2>Learning Objectives</h2><ul><li>Identify available credits</li><li>Calculate credit amounts</li><li>Apply carryforward rules</li></ul>', 45, ARRAY['business credits', 'tax credits'], '[]'::jsonb),
('business-returns', 20, 'Section 199A QBI Deduction', '<h2>Learning Objectives</h2><ul><li>Calculate QBI for businesses</li><li>Apply wage/property limits</li><li>Identify SSTB limitations</li></ul>', 45, ARRAY['QBI', 'Section 199A'], '[]'::jsonb),
('business-returns', 21, 'Accounting Methods', '<h2>Learning Objectives</h2><ul><li>Compare cash vs accrual</li><li>Apply accounting method rules</li><li>Change accounting methods</li></ul>', 45, ARRAY['accounting methods', 'cash', 'accrual'], '[]'::jsonb),
('business-returns', 22, 'Inventory Valuation', '<h2>Learning Objectives</h2><ul><li>Apply FIFO, LIFO methods</li><li>Value inventory correctly</li><li>Report inventory changes</li></ul>', 45, ARRAY['inventory', 'FIFO', 'LIFO'], '[]'::jsonb),
('business-returns', 23, 'Depreciation Methods', '<h2>Learning Objectives</h2><ul><li>Apply MACRS depreciation</li><li>Calculate bonus depreciation</li><li>Use depreciation tables</li></ul>', 45, ARRAY['depreciation', 'MACRS'], '[]'::jsonb),
('business-returns', 24, 'Practice: Schedule C Return', '<h2>Learning Objectives</h2><ul><li>Complete full Schedule C</li><li>Calculate SE tax</li><li>Apply QBI deduction</li></ul>', 60, ARRAY['practice', 'Schedule C'], '[]'::jsonb),
('business-returns', 25, 'Practice: Partnership Return', '<h2>Learning Objectives</h2><ul><li>Complete Form 1065</li><li>Prepare K-1s</li><li>Allocate income correctly</li></ul>', 60, ARRAY['practice', 'partnership'], '[]'::jsonb)
ON CONFLICT (course_id, lesson_number) DO NOTHING;

-- Professional Tax Software Excellence (software-mastery) - 22 lessons
INSERT INTO training_lessons (course_id, lesson_number, title, content, duration_minutes, topics, quiz_questions) VALUES
('software-mastery', 1, 'Tax Software Overview and Navigation', '<h2>Learning Objectives</h2><ul><li>Navigate tax software interface</li><li>Understand menu structure</li><li>Access key features</li></ul>', 45, ARRAY['software navigation', 'interface'], '[]'::jsonb),
('software-mastery', 2, 'Setting Up Your Account', '<h2>Learning Objectives</h2><ul><li>Configure software settings</li><li>Set up firm information</li><li>Configure user preferences</li></ul>', 45, ARRAY['setup', 'configuration'], '[]'::jsonb),
('software-mastery', 3, 'Client Management', '<h2>Learning Objectives</h2><ul><li>Add and manage clients</li><li>Import client data</li><li>Organize client files</li></ul>', 45, ARRAY['client management', 'data entry'], '[]'::jsonb),
('software-mastery', 4, 'Creating a New Tax Return', '<h2>Learning Objectives</h2><ul><li>Start new returns</li><li>Select return type</li><li>Enter basic information</li></ul>', 45, ARRAY['new return', 'data entry'], '[]'::jsonb),
('software-mastery', 5, 'Data Entry Best Practices', '<h2>Learning Objectives</h2><ul><li>Enter data efficiently</li><li>Use keyboard shortcuts</li><li>Minimize errors</li></ul>', 45, ARRAY['data entry', 'efficiency'], '[]'::jsonb),
('software-mastery', 6, 'Form 1040 in Tax Software', '<h2>Learning Objectives</h2><ul><li>Complete 1040 in software</li><li>Navigate form sections</li><li>Review calculations</li></ul>', 45, ARRAY['Form 1040', 'software'], '[]'::jsonb),
('software-mastery', 7, 'Schedules and Forms', '<h2>Learning Objectives</h2><ul><li>Add schedules to returns</li><li>Complete supporting forms</li><li>Link forms correctly</li></ul>', 45, ARRAY['schedules', 'forms'], '[]'::jsonb),
('software-mastery', 8, 'Interview Mode vs Forms Mode', '<h2>Learning Objectives</h2><ul><li>Use interview mode</li><li>Switch to forms mode</li><li>Choose best approach</li></ul>', 45, ARRAY['interview mode', 'forms mode'], '[]'::jsonb),
('software-mastery', 9, 'Error Checking and Diagnostics', '<h2>Learning Objectives</h2><ul><li>Run diagnostics</li><li>Resolve errors</li><li>Clear warnings</li></ul>', 45, ARRAY['diagnostics', 'error checking'], '[]'::jsonb),
('software-mastery', 10, 'E-Filing from Tax Software', '<h2>Learning Objectives</h2><ul><li>Prepare returns for e-file</li><li>Submit electronically</li><li>Track e-file status</li></ul>', 45, ARRAY['e-file', 'electronic filing'], '[]'::jsonb),
('software-mastery', 11, 'Bank Products and Refund Options', '<h2>Learning Objectives</h2><ul><li>Offer bank products</li><li>Process refund transfers</li><li>Understand fees</li></ul>', 45, ARRAY['bank products', 'refunds'], '[]'::jsonb),
('software-mastery', 12, 'Document Management', '<h2>Learning Objectives</h2><ul><li>Attach documents</li><li>Organize files</li><li>Store securely</li></ul>', 45, ARRAY['documents', 'file management'], '[]'::jsonb),
('software-mastery', 13, 'Reports and Analytics', '<h2>Learning Objectives</h2><ul><li>Generate reports</li><li>Analyze practice data</li><li>Track performance</li></ul>', 45, ARRAY['reports', 'analytics'], '[]'::jsonb),
('software-mastery', 14, 'Multi-User Setup', '<h2>Learning Objectives</h2><ul><li>Add users</li><li>Set permissions</li><li>Manage access</li></ul>', 45, ARRAY['multi-user', 'permissions'], '[]'::jsonb),
('software-mastery', 15, 'Backup and Security', '<h2>Learning Objectives</h2><ul><li>Back up data</li><li>Secure client information</li><li>Implement best practices</li></ul>', 45, ARRAY['backup', 'security'], '[]'::jsonb),
('software-mastery', 16, 'Software Updates', '<h2>Learning Objectives</h2><ul><li>Install updates</li><li>Review tax law changes</li><li>Stay current</li></ul>', 45, ARRAY['updates', 'tax law'], '[]'::jsonb),
('software-mastery', 17, 'Troubleshooting Common Issues', '<h2>Learning Objectives</h2><ul><li>Diagnose problems</li><li>Find solutions</li><li>Contact support</li></ul>', 45, ARRAY['troubleshooting', 'support'], '[]'::jsonb),
('software-mastery', 18, 'Keyboard Shortcuts and Efficiency', '<h2>Learning Objectives</h2><ul><li>Learn shortcuts</li><li>Speed up workflow</li><li>Increase productivity</li></ul>', 45, ARRAY['shortcuts', 'efficiency'], '[]'::jsonb),
('software-mastery', 19, 'State Returns in Tax Software', '<h2>Learning Objectives</h2><ul><li>Add state returns</li><li>Handle multi-state</li><li>File state e-file</li></ul>', 45, ARRAY['state returns', 'multi-state'], '[]'::jsonb),
('software-mastery', 20, 'Prior Year Returns', '<h2>Learning Objectives</h2><ul><li>Access prior years</li><li>Import prior data</li><li>File late returns</li></ul>', 45, ARRAY['prior year', 'late filing'], '[]'::jsonb),
('software-mastery', 21, 'Amendments and Superseding Returns', '<h2>Learning Objectives</h2><ul><li>Prepare Form 1040-X</li><li>File amendments</li><li>Track changes</li></ul>', 45, ARRAY['amendments', 'Form 1040-X'], '[]'::jsonb),
('software-mastery', 22, 'Tax Software Practice Lab', '<h2>Learning Objectives</h2><ul><li>Complete practice scenarios</li><li>Apply all skills</li><li>Prepare for real returns</li></ul>', 60, ARRAY['practice', 'lab'], '[]'::jsonb)
ON CONFLICT (course_id, lesson_number) DO NOTHING;
