-- Seed FAQs
INSERT INTO faqs (id, question, answer, category, display_order, is_active) VALUES
  (gen_random_uuid(), 'What programs do you offer?', 'We offer career training programs in Healthcare (CNA, Medical Assistant, Phlebotomy), Skilled Trades (HVAC, Electrical, Plumbing, Welding), Technology (IT Support, Cybersecurity), Business (Tax Preparation, Entrepreneurship), and Barber/Cosmetology apprenticeships.', 'Programs', 1, true),
  (gen_random_uuid(), 'How long are the training programs?', 'Program lengths vary from 4 weeks to 16 weeks depending on the certification. Healthcare programs typically run 8-12 weeks, skilled trades 12-16 weeks, and technology programs 8-12 weeks.', 'Programs', 2, true),
  (gen_random_uuid(), 'Is the training really free?', 'Yes! Through WIOA (Workforce Innovation and Opportunity Act) funding and other grants, eligible participants can receive 100% free training. We help you determine eligibility and apply for funding.', 'Funding', 3, true),
  (gen_random_uuid(), 'What is WIOA funding?', 'WIOA (Workforce Innovation and Opportunity Act) is a federal program that provides funding for job training to eligible adults, dislocated workers, and youth. It covers tuition, books, supplies, and sometimes supportive services.', 'Funding', 4, true),
  (gen_random_uuid(), 'How do I know if I qualify for free training?', 'Eligibility depends on factors like income level, employment status, and residency. Generally, if you are unemployed, underemployed, or meet income guidelines, you may qualify. Contact us for a free eligibility assessment.', 'Funding', 5, true),
  (gen_random_uuid(), 'Do you help with job placement?', 'Yes! We provide comprehensive career services including resume writing, interview preparation, job search assistance, and connections to employer partners. Our goal is to help you get hired after completing your training.', 'Career Services', 6, true),
  (gen_random_uuid(), 'Where are you located?', 'Our main campus is located in Indianapolis, Indiana. We also offer some programs at partner locations throughout Indiana. Contact us for specific program locations.', 'General', 7, true),
  (gen_random_uuid(), 'Can I work while attending training?', 'Many of our programs offer flexible scheduling including evening and weekend options. We work with students to accommodate work schedules when possible.', 'General', 8, true),
  (gen_random_uuid(), 'What certifications will I earn?', 'Each program leads to industry-recognized certifications. For example, CNA students earn state nursing assistant certification, HVAC students earn EPA 608 certification, and IT students can earn CompTIA certifications.', 'Programs', 9, true),
  (gen_random_uuid(), 'How do I apply?', 'You can apply online through our website, call us at (317) 314-3757, or visit our campus. The application process includes an eligibility assessment, program selection, and enrollment paperwork.', 'Enrollment', 10, true)
ON CONFLICT DO NOTHING;
