-- Fix infinite RLS recursion on profiles table (Postgres error 42P17)
-- and create missing tables referenced by the codebase.
--
-- View to real table mapping:
--   courses → training_courses
--   lessons → training_lessons
--   enrollments → training_enrollments
--
-- All policies use SECURITY DEFINER helpers to avoid recursive profiles lookups.
-- Run in Supabase SQL Editor. Already applied to production 2026-02-15.
