-- Ensure all programs that have dedicated pages are published and active.
--
-- Programs were inserted with various status values ('active', 'draft', etc.)
-- but the public catalog queries require published = true AND is_active = true.
-- This migration sets those flags for every program that has a live page.
--
-- Safe to re-run: uses INSERT ... ON CONFLICT DO UPDATE.
-- Apply in Supabase Dashboard → SQL Editor.

-- ── 1. Publish all existing programs that are not archived ────────────────────
-- Any program already in the table with status != 'archived' should be visible.

UPDATE public.programs
SET
  published  = true,
  is_active  = true,
  updated_at = now()
WHERE
  (published = false OR published IS NULL OR is_active = false OR is_active IS NULL)
  AND (status IS NULL OR status != 'archived');

-- ── 2. Upsert the canonical program rows for every dedicated page ─────────────
-- Covers all slugs that have a page under app/programs/. Uses estimated_weeks
-- (the canonical column per migration 20260227000003) not duration_weeks.

INSERT INTO public.programs (
  slug, title, short_description, description, category,
  estimated_weeks, credential_name, image_url,
  published, is_active, status, wioa_approved,
  created_at, updated_at
) VALUES
  ('hvac-technician',              'HVAC Technician',                    'Earn your EPA 608 certification and enter the HVAC trade.',                                    'Hands-on HVAC training covering refrigerant handling, system diagnostics, and EPA 608 certification. WIOA and Workforce Ready Grant eligible.',                                    'Skilled Trades',       12, 'EPA 608 Universal Certification',                    '/images/pages/hvac-unit.jpg',                    true, true, 'published', true,  now(), now()),
  ('barber-apprenticeship',        'Barber Apprenticeship',              'Earn while you learn — DOL-registered barber apprenticeship.',                                 'DOL-registered barber apprenticeship. Earn wages while training to become a licensed Indiana barber. 2,000 OJT hours + 144 RTI hours.',                                          'Barber & Beauty',      72, 'Indiana Registered Barber License',                  '/images/pages/barber-hero-main.jpg',             true, true, 'published', true,  now(), now()),
  ('cna',                          'Certified Nursing Assistant',        'Become a CNA in weeks. State-approved, WIOA funded.',                                         'State-approved CNA training covering patient care, vital signs, and clinical skills. WIOA and Workforce Ready Grant eligible.',                                                   'Healthcare',            6, 'Indiana CNA Certification',                          '/images/pages/cna-nursing-real.jpg',             true, true, 'published', true,  now(), now()),
  ('cdl-training',                 'CDL Class A Training',               'Get your CDL Class A license and start earning $60k+.',                                       'Commercial driver training covering pre-trip inspection, backing maneuvers, and DOT regulations. WIOA eligible.',                                                                  'Skilled Trades',        8, 'CDL Class A License',                                '/images/pages/cdl-truck-highway.jpg',            true, true, 'published', true,  now(), now()),
  ('medical-assistant',            'Medical Assistant',                  'Launch a healthcare career as a certified medical assistant.',                                  'Clinical and administrative medical assistant training. Covers EHR, phlebotomy, injections, and patient intake. NHA certification prep.',                                          'Healthcare',           16, 'NHA Certified Medical Assistant (CCMA)',              '/images/pages/medical-assistant-real.jpg',       true, true, 'published', true,  now(), now()),
  ('cosmetology-apprenticeship',   'Cosmetology Apprenticeship',         'Earn your Indiana cosmetology license through a paid apprenticeship.',                        'DOL-registered cosmetology apprenticeship. Earn wages while completing 1,500 OJT hours and 150 RTI hours toward your Indiana license.',                                             'Barber & Beauty',      60, 'Indiana Cosmetology License',                        '/images/pages/cosmetology.jpg',                  true, true, 'published', true,  now(), now()),
  ('electrical',                   'Electrical Apprenticeship',          'DOL-registered electrical apprenticeship — earn while you learn.',                             'Federally registered electrical apprenticeship. Earn journeyman wages while completing 8,000 OJT hours and 576 RTI hours.',                                                        'Skilled Trades',      240, 'Journeyman Electrician License',                     '/images/pages/electrical.jpg',                   true, true, 'published', true,  now(), now()),
  ('plumbing',                     'Plumbing Apprenticeship',            'DOL-registered plumbing apprenticeship — earn while you learn.',                              'Federally registered plumbing apprenticeship. Earn wages while completing 8,000 OJT hours and 576 RTI hours toward journeyman license.',                                             'Skilled Trades',      240, 'Journeyman Plumber License',                         '/images/pages/plumbing.jpg',                     true, true, 'published', true,  now(), now()),
  ('welding',                      'Welding Certification',              'AWS-recognized welding certification covering MIG, TIG, and stick.',                          'Welding certification training covering MIG, TIG, and stick welding. AWS D1.1 structural welding prep. WIOA eligible.',                                                            'Skilled Trades',       12, 'AWS Certified Welder',                               '/images/pages/welding.jpg',                      true, true, 'published', true,  now(), now()),
  ('forklift',                     'Forklift Operator Certification',    'OSHA-compliant forklift certification — complete in 1 day.',                                  'OSHA-compliant forklift operator certification covering counterbalance, reach truck, and order picker. Employer-recognized.',                                                        'Skilled Trades',        1, 'OSHA Forklift Operator Certificate',                 '/images/pages/forklift.jpg',                     true, true, 'published', false, now(), now()),
  ('bookkeeping',                  'Bookkeeping & Accounting',           'QuickBooks and Excel bookkeeping certification for small business.',                           'Bookkeeping training covering QuickBooks, accounts payable/receivable, payroll, and financial reporting. Intuit certification prep.',                                                  'Business',             16, 'Intuit QuickBooks Certified User',                   '/images/pages/bookkeeping.jpg',                  true, true, 'published', true,  now(), now()),
  ('tax-preparation',              'Tax Preparation',                    'IRS-recognized tax preparer certification — PTIN eligible.',                                  'Tax preparation training covering individual returns, Schedule C, and IRS e-file. PTIN registration and IRS Annual Filing Season Program prep.',                                       'Business',              8, 'IRS Annual Filing Season Program Certificate',       '/images/pages/tax-preparation.jpg',              true, true, 'published', false, now(), now()),
  ('cybersecurity-analyst',        'Cybersecurity Analyst',              'CompTIA Security+ and CySA+ certification pathway.',                                          'Cybersecurity training covering network defense, threat analysis, and incident response. CompTIA Security+ and CySA+ certification prep.',                                            'Technology',           24, 'CompTIA Security+ / CySA+',                          '/images/pages/cybersecurity.jpg',                true, true, 'published', true,  now(), now()),
  ('software-development',         'Software Development',               'Full-stack web development with job placement support.',                                       'Full-stack software development training covering HTML, CSS, JavaScript, React, and Node.js. Portfolio-based curriculum with employer connections.',                                    'Technology',           24, 'Full-Stack Developer Certificate',                   '/images/pages/software-development.jpg',         true, true, 'published', true,  now(), now()),
  ('it-help-desk',                 'IT Help Desk',                       'CompTIA A+ certification and IT support career launch.',                                       'IT support training covering hardware, networking, operating systems, and troubleshooting. CompTIA A+ certification prep.',                                                           'Technology',           16, 'CompTIA A+',                                         '/images/pages/it-help-desk.jpg',                 true, true, 'published', true,  now(), now()),
  ('web-development',              'Web Development',                    'Build websites and launch a freelance or agency career.',                                      'Web development training covering HTML, CSS, JavaScript, and WordPress. Portfolio projects and freelance business fundamentals.',                                                       'Technology',           16, 'Web Developer Certificate',                          '/images/pages/web-development.jpg',              true, true, 'published', true,  now(), now()),
  ('entrepreneurship',             'Entrepreneurship',                   'Launch your business with a funded business plan and mentorship.',                             'Entrepreneurship training covering business planning, marketing, finance, and legal structure. Connects graduates to SBDC and funding resources.',                                     'Business',             12, 'Certificate in Entrepreneurship',                    '/images/pages/entrepreneurship.jpg',             true, true, 'published', true,  now(), now()),
  ('pharmacy-technician',          'Pharmacy Technician',                'ExCPT-certified pharmacy technician training.',                                                'Pharmacy technician training covering drug classifications, dispensing, compounding, and pharmacy law. ExCPT certification prep.',                                                    'Healthcare',           16, 'ExCPT Certified Pharmacy Technician',                '/images/pages/pharmacy-technician.jpg',          true, true, 'published', true,  now(), now()),
  ('phlebotomy',                   'Phlebotomy Technician',              'NHA-certified phlebotomy training with clinical externship.',                                  'Phlebotomy training covering venipuncture, capillary collection, specimen handling, and HIPAA. NHA CPT certification prep with clinical hours.',                                      'Healthcare',            8, 'NHA Certified Phlebotomy Technician (CPT)',           '/images/pages/phlebotomy.jpg',                   true, true, 'published', true,  now(), now()),
  ('home-health-aide',             'Home Health Aide',                   'Indiana-approved HHA training for in-home patient care.',                                     'Home health aide training covering personal care, medication reminders, and daily living assistance. Indiana state-approved curriculum.',                                               'Healthcare',            4, 'Indiana Home Health Aide Certificate',               '/images/pages/home-health-aide.jpg',             true, true, 'published', true,  now(), now()),
  ('cpr-first-aid',                'CPR / First Aid',                    'AHA-recognized CPR, AED, and First Aid certification.',                                       'CPR, AED, and First Aid certification for healthcare workers and general public. American Heart Association BLS and Heartsaver courses.',                                              'Healthcare',            1, 'AHA BLS / Heartsaver Certificate',                   '/images/pages/cpr-first-aid.jpg',                true, true, 'published', false, now(), now()),
  ('diesel-mechanic',              'Diesel Mechanic',                    'ASE diesel certification for trucks, buses, and heavy equipment.',                             'Diesel mechanic training covering engine systems, fuel, electrical, and brakes. ASE Medium/Heavy Truck certification prep.',                                                         'Skilled Trades',       24, 'ASE Medium/Heavy Truck Certification',               '/images/pages/diesel-mechanic.jpg',              true, true, 'published', true,  now(), now()),
  ('culinary-apprenticeship',      'Culinary Apprenticeship',            'DOL-registered culinary apprenticeship — earn while you cook.',                               'Federally registered culinary apprenticeship. Earn wages while completing 2,000 OJT hours and 144 RTI hours in a professional kitchen.',                                              'Skilled Trades',       60, 'Culinary Arts Certificate',                          '/images/pages/culinary.jpg',                     true, true, 'published', true,  now(), now()),
  ('nail-technician-apprenticeship','Nail Technician Apprenticeship',    'Earn your Indiana nail technician license through a paid apprenticeship.',                    'DOL-registered nail technician apprenticeship. Earn wages while completing 450 OJT hours and 50 RTI hours toward your Indiana license.',                                             'Barber & Beauty',      20, 'Indiana Nail Technician License',                    '/images/pages/nail-technician.jpg',              true, true, 'published', true,  now(), now()),
  ('esthetician',                  'Esthetician',                        'Indiana esthetician license — skin care, facials, and waxing.',                               'Esthetician training covering skin analysis, facials, chemical peels, waxing, and makeup. Indiana State Board approved. 700 clock hours.',                                            'Barber & Beauty',      20, 'Indiana Esthetician License',                        '/images/pages/esthetician.jpg',                  true, true, 'published', true,  now(), now()),
  ('beauty-career-educator',       'Beauty Career Educator',             'Train to become a licensed beauty educator and career instructor.',                            'Beauty educator training for licensed cosmetologists and barbers who want to teach. Covers curriculum design, classroom management, and state board prep.',                            'Barber & Beauty',      16, 'Indiana Cosmetology Instructor License',             '/images/pages/beauty-educator.jpg',              true, true, 'published', true,  now(), now()),
  ('office-administration',        'Office Administration',              'Microsoft Office Specialist certification for administrative careers.',                        'Office administration training covering Word, Excel, PowerPoint, Outlook, and professional communication. MOS certification prep.',                                                    'Business',             12, 'Microsoft Office Specialist Associate',              '/images/pages/office-administration.jpg',        true, true, 'published', true,  now(), now()),
  ('network-support-technician',   'Network Support Technician',         'CompTIA Network+ certification for IT networking careers.',                                    'Network support training covering TCP/IP, routing, switching, wireless, and network security. CompTIA Network+ certification prep.',                                                   'Technology',           16, 'CompTIA Network+',                                   '/images/pages/network-support.jpg',              true, true, 'published', true,  now(), now()),
  ('network-administration',       'Network Administration',             'Cisco CCNA and CompTIA Network+ for network admin careers.',                                  'Network administration training covering routing, switching, VLANs, and network management. Cisco CCNA and CompTIA Network+ prep.',                                                    'Technology',           24, 'Cisco CCNA / CompTIA Network+',                      '/images/pages/network-administration.jpg',       true, true, 'published', true,  now(), now()),
  ('project-management',           'Project Management',                 'PMP and CAPM certification pathway for project managers.',                                     'Project management training covering Agile, Scrum, risk management, and stakeholder communication. PMI CAPM and PMP certification prep.',                                              'Business',             16, 'PMI CAPM / PMP',                                     '/images/pages/project-management.jpg',           true, true, 'published', true,  now(), now()),
  ('graphic-design',               'Graphic Design',                     'Adobe Creative Suite certification for design careers.',                                       'Graphic design training covering Photoshop, Illustrator, InDesign, and brand identity. Adobe Certified Professional prep.',                                                           'Technology',           16, 'Adobe Certified Professional',                       '/images/pages/graphic-design.jpg',               true, true, 'published', true,  now(), now()),
  ('cad-drafting',                 'CAD Drafting',                       'AutoCAD certification for architecture, engineering, and manufacturing.',                      'CAD drafting training covering AutoCAD 2D/3D, blueprint reading, and technical drawing. Autodesk Certified User prep.',                                                               'Technology',           16, 'Autodesk Certified User — AutoCAD',                  '/images/pages/cad-drafting.jpg',                 true, true, 'published', true,  now(), now()),
  ('peer-recovery-specialist',     'Peer Recovery Specialist',           'Indiana CPRS certification for addiction recovery support careers.',                           'Peer recovery specialist training covering motivational interviewing, recovery coaching, and ethics. Indiana CPRS certification prep.',                                               'Human Services',        8, 'Indiana Certified Peer Recovery Specialist (CPRS)',  '/images/pages/peer-recovery.jpg',                true, true, 'published', true,  now(), now()),
  ('sanitation-infection-control', 'Sanitation & Infection Control',     'Infection prevention certification for healthcare and service environments.',                  'Sanitation and infection control training covering OSHA bloodborne pathogens, PPE, and sterilization protocols.',                                                                   'Human Services',        2, 'Infection Control Certificate',                      '/images/pages/sanitation.jpg',                   true, true, 'published', false, now(), now()),
  ('drug-alcohol-specimen-collector','Drug & Alcohol Specimen Collector', 'DOT-compliant specimen collection certification.',                                            'DOT-compliant drug and alcohol specimen collection training. Covers chain of custody, observed collections, and DOT regulations.',                                                     'Human Services',        1, 'DOT Specimen Collector Certificate',                 '/images/pages/specimen-collector.jpg',           true, true, 'published', false, now(), now()),
  ('construction-trades-certification','Construction Trades',            'OSHA 10 and construction fundamentals for skilled trades entry.',                             'Construction trades training covering OSHA 10, blueprint reading, hand tools, and site safety. Entry point for electrical, plumbing, and HVAC apprenticeships.',                      'Skilled Trades',        4, 'OSHA 10 Construction Certificate',                   '/images/pages/construction.jpg',                 true, true, 'published', true,  now(), now()),
  ('finance-bookkeeping-accounting','Finance, Bookkeeping & Accounting', 'Comprehensive finance and accounting certification pathway.',                                  'Finance and accounting training covering bookkeeping, payroll, tax preparation, and financial analysis. Multiple certification pathways.',                                             'Business',             20, 'Accounting Technician Certificate',                  '/images/pages/finance-accounting.jpg',           true, true, 'published', true,  now(), now()),
  ('business-administration',      'Business Administration',            'Business fundamentals and Microsoft Office certification.',                                    'Business administration training covering management, marketing, HR, and operations. Microsoft Office Specialist and business fundamentals certifications.',                             'Business',             16, 'Business Administration Certificate',                '/images/pages/business-administration.jpg',      true, true, 'published', true,  now(), now()),
  ('emergency-health-safety',      'Emergency Health & Safety',          'CPR, First Aid, and emergency response certification bundle.',                                 'Emergency health and safety training covering CPR/AED, First Aid, OSHA 10, and emergency response protocols. Multi-credential bundle.',                                               'Healthcare',            2, 'Emergency Health & Safety Certificate Bundle',       '/images/pages/emergency-health-safety.jpg',      true, true, 'published', false, now(), now())
ON CONFLICT (slug) DO UPDATE SET
  published    = true,
  is_active    = true,
  status       = CASE WHEN programs.status = 'archived' THEN programs.status ELSE 'published' END,
  -- Only fill in title/description if the existing row has none
  title             = COALESCE(NULLIF(programs.title, ''),             EXCLUDED.title),
  short_description = COALESCE(NULLIF(programs.short_description, ''), EXCLUDED.short_description),
  description       = COALESCE(NULLIF(programs.description, ''),       EXCLUDED.description),
  credential_name   = COALESCE(NULLIF(programs.credential_name, ''),   EXCLUDED.credential_name),
  image_url         = COALESCE(NULLIF(programs.image_url, ''),         EXCLUDED.image_url),
  estimated_weeks   = COALESCE(programs.estimated_weeks,               EXCLUDED.estimated_weeks),
  updated_at        = now();

-- ── 3. Verify ─────────────────────────────────────────────────────────────────
-- Run this after applying to confirm programs are visible:
--
-- SELECT slug, title, published, is_active, status
-- FROM public.programs
-- WHERE published = true AND is_active = true AND status != 'archived'
-- ORDER BY title;
