-- Migration: Batch 3A — Simple admin-only policies using public.is_admin()
-- Applied via exec_sql RPC in 7 chunks.
-- Covers ~130 tables from academic_integrity_violations through refund_tracking.
-- Note: Original batch was cut off at "refunds" — remaining tables (S-Z) need
-- a follow-up batch.
--
-- Pattern: DROP POLICY IF EXISTS + CREATE POLICY ... FOR ALL TO authenticated USING (public.is_admin())
-- These are non-tenant-scoped admin policies for tables that don't yet have tenant_id
-- or where tenant scoping is deferred.
--
-- Applied: 2026-02-16
-- Result: 199 policies using is_admin() across 175 tables

-- See APPLY_20260216_combined.sql for the tenant-scoped core table policies.
-- This file documents the broader admin policy sweep.
