-- Part 6: RLS policies for all new tables

DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'certifications','course_progress','job_placements','support_tickets',
      'videos','library_resources','resource_bookmarks','shared_documents',
      'study_sessions','user_connections','social_posts','user_files',
      'payment_methods','invoices','scorm_progress','group_messages',
      'forum_members','crm_leads','email_campaigns','waitlist',
      'wioa_applications','wioa_documents','certificate_templates',
      'contact_submissions','participant_barriers','volunteer_opportunities',
      'volunteers','community_groups','follow_ups','job_opportunities',
      'training_hours','onboarding_resources','program_holder_acknowledgements',
      'program_announcements','assignment_rubrics','participants'
    ])
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
    -- Allow authenticated users to read
    EXECUTE format('CREATE POLICY "Allow authenticated read" ON %I FOR SELECT TO authenticated USING (true)', tbl);
    -- Allow users to manage their own rows (for tables with user_id)
    BEGIN
      EXECUTE format('CREATE POLICY "Allow own insert" ON %I FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id)', tbl);
      EXECUTE format('CREATE POLICY "Allow own update" ON %I FOR UPDATE TO authenticated USING (auth.uid() = user_id)', tbl);
    EXCEPTION WHEN undefined_column THEN
      -- Table doesn't have user_id column, skip user-specific policies
      EXECUTE format('CREATE POLICY "Allow authenticated insert" ON %I FOR INSERT TO authenticated WITH CHECK (true)', tbl);
    END;
  END LOOP;
END $$;


-- Enable RLS
ALTER TABLE IF EXISTS account_deletion_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_account_deletion_requests" ON account_deletion_requests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS account_export_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_account_export_events" ON account_export_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS accreditations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_accreditations" ON accreditations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS activity_feed ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_activity_feed" ON activity_feed FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS advising_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_advising_requests" ON advising_requests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS affiliates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_affiliates" ON affiliates FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS agreement_signatures ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_agreement_signatures" ON agreement_signatures FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_assistant_conversations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_assistant_conversations" ON ai_assistant_conversations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_assistant_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_assistant_messages" ON ai_assistant_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_chat_context ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_chat_context" ON ai_chat_context FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_chat_history ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_chat_history" ON ai_chat_history FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_chat_interactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_chat_interactions" ON ai_chat_interactions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_chat_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_chat_sessions" ON ai_chat_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_course_generation_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_course_generation_log" ON ai_course_generation_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_instructor_assignments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_instructor_assignments" ON ai_instructor_assignments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_instructor_interactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_instructor_interactions" ON ai_instructor_interactions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_instructor_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_instructor_logs" ON ai_instructor_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_job_matches ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_job_matches" ON ai_job_matches FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_messages" ON ai_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ai_tutor_interactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ai_tutor_interactions" ON ai_tutor_interactions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ambient_music_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ambient_music_log" ON ambient_music_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS announcement_recipients ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_announcement_recipients" ON announcement_recipients FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS app_screenshot_views ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_app_screenshot_views" ON app_screenshot_views FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS application_claim_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_application_claim_log" ON application_claim_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS appointment_types ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_appointment_types" ON appointment_types FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS appointments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_appointments" ON appointments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_agreements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_agreements" ON apprentice_agreements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_document_types ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_document_types" ON apprentice_document_types FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_documents" ON apprentice_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_forms ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_forms" ON apprentice_forms FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_funding_profile ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_funding_profile" ON apprentice_funding_profile FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_hours_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_hours_log" ON apprentice_hours_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_progress" ON apprentice_progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_service_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_service_logs" ON apprentice_service_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprentice_skill_progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprentice_skill_progress" ON apprentice_skill_progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprenticeship_shop_drafts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprenticeship_shop_drafts" ON apprenticeship_shop_drafts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS apprenticeship_shops ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_apprenticeship_shops" ON apprenticeship_shops FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS approval_tokens ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_approval_tokens" ON approval_tokens FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS assessment_attempts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_assessment_attempts" ON assessment_attempts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS assessments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_assessments" ON assessments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS attendance ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_attendance" ON attendance FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS attendance_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_attendance_log" ON attendance_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS attendance_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_attendance_sessions" ON attendance_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS audio_preferences ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_audio_preferences" ON audio_preferences FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS autopilot_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_autopilot_logs" ON autopilot_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS autopilot_settings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_autopilot_settings" ON autopilot_settings FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS avatar_chat_interactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_avatar_chat_interactions" ON avatar_chat_interactions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS avatars ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_avatars" ON avatars FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS backups ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_backups" ON backups FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS banking_services ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_banking_services" ON banking_services FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS barber_payments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_barber_payments" ON barber_payments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS billing_accounts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_billing_accounts" ON billing_accounts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS bookings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_bookings" ON bookings FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS bridge_payment_plans ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_bridge_payment_plans" ON bridge_payment_plans FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS campaign_templates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_campaign_templates" ON campaign_templates FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS captcha_attempts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_captcha_attempts" ON captcha_attempts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS career_counseling_conversations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_career_counseling_conversations" ON career_counseling_conversations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS career_counseling_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_career_counseling_messages" ON career_counseling_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS carts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_carts" ON carts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_events" ON case_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_management ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_management" ON case_management FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_manager_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_manager_notes" ON case_manager_notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_notes" ON case_notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_studies ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_studies" ON case_studies FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS case_tasks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_case_tasks" ON case_tasks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS cases ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_cases" ON cases FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS cash_advance_applications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_cash_advance_applications" ON cash_advance_applications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS cert_revocation_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_cert_revocation_log" ON cert_revocation_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS certification_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_certification_submissions" ON certification_submissions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS certification_types ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_certification_types" ON certification_types FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS certiport_exam_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_certiport_exam_requests" ON certiport_exam_requests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS checkin_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_checkin_sessions" ON checkin_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS clinical_hours_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_clinical_hours_logs" ON clinical_hours_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS clinical_placements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_clinical_placements" ON clinical_placements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS clinical_sites ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_clinical_sites" ON clinical_sites FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS code_examples ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_code_examples" ON code_examples FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS collaboration_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_collaboration_messages" ON collaboration_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS collaboration_presence ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_collaboration_presence" ON collaboration_presence FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS collection_sites ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_collection_sites" ON collection_sites FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS community_event_rsvps ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_community_event_rsvps" ON community_event_rsvps FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS community_group_members ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_community_group_members" ON community_group_members FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS community_members ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_community_members" ON community_members FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS competency_tests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_competency_tests" ON competency_tests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS completions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_completions" ON completions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS compliance_audits ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_compliance_audits" ON compliance_audits FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS compliance_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_compliance_documents" ON compliance_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS compliance_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_compliance_events" ON compliance_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS compliance_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_compliance_items" ON compliance_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS consent_preferences ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_consent_preferences" ON consent_preferences FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS contact_hours ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_contact_hours" ON contact_hours FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS content_blocks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_content_blocks" ON content_blocks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS content_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_content_items" ON content_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS cookie_consent_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_cookie_consent_log" ON cookie_consent_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS copilot_usage_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_copilot_usage_log" ON copilot_usage_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_announcements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_announcements" ON course_announcements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_categories" ON course_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_completion_status ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_completion_status" ON course_completion_status FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_completions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_completions" ON course_completions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_discussions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_discussions" ON course_discussions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_enrollments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_enrollments" ON course_enrollments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_materials ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_materials" ON course_materials FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_metrics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_metrics" ON course_metrics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS course_reviews ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_course_reviews" ON course_reviews FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS creator_courses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_creator_courses" ON creator_courses FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS credential_share_links ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_credential_share_links" ON credential_share_links FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS cta_clicks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_cta_clicks" ON cta_clicks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS curvature_appointments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_curvature_appointments" ON curvature_appointments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS curvature_reviews ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_curvature_reviews" ON curvature_reviews FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS curvature_services ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_curvature_services" ON curvature_services FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS customer_billing ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_customer_billing" ON customer_billing FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS daily_streaks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_daily_streaks" ON daily_streaks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS dashboards ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_dashboards" ON dashboards FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS data_processing_jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_data_processing_jobs" ON data_processing_jobs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS deals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_deals" ON deals FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS demo_analytics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_demo_analytics" ON demo_analytics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS devstudio_chat_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_devstudio_chat_log" ON devstudio_chat_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS direct_message_conversations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_direct_message_conversations" ON direct_message_conversations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS direct_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_direct_messages" ON direct_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS discussion_replies ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_discussion_replies" ON discussion_replies FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS discussions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_discussions" ON discussions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS document_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_document_categories" ON document_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS documentation ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_documentation" ON documentation FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS donation_tiers ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_donation_tiers" ON donation_tiers FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS downloads ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_downloads" ON downloads FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS drug_test_history ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_drug_test_history" ON drug_test_history FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS drug_testing_orders ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_drug_testing_orders" ON drug_testing_orders FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS drug_testing_policies ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_drug_testing_policies" ON drug_testing_policies FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS drug_tests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_drug_tests" ON drug_tests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ecr_sync_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ecr_sync_logs" ON ecr_sync_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS email_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_email_logs" ON email_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS email_workflows ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_email_workflows" ON email_workflows FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS emails ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_emails" ON emails FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS employer_incentives ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_employer_incentives" ON employer_incentives FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS employer_sponsorships ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_employer_sponsorships" ON employer_sponsorships FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS enrollment_acknowledgments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_enrollment_acknowledgments" ON enrollment_acknowledgments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS enrollment_cases ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_enrollment_cases" ON enrollment_cases FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS enrollment_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_enrollment_events" ON enrollment_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS enrollment_jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_enrollment_jobs" ON enrollment_jobs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS enrollment_module_progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_enrollment_module_progress" ON enrollment_module_progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS entity_eligibility_checks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_entity_eligibility_checks" ON entity_eligibility_checks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS exam_attempt_questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_exam_attempt_questions" ON exam_attempt_questions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS exam_attempts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_exam_attempts" ON exam_attempts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS exam_readiness ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_exam_readiness" ON exam_readiness FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS exams ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_exams" ON exams FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS external_credentials ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_external_credentials" ON external_credentials FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS faq_search_analytics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_faq_search_analytics" ON faq_search_analytics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS feedback ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_feedback" ON feedback FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS feedback_votes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_feedback_votes" ON feedback_votes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ferpa_access_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ferpa_access_requests" ON ferpa_access_requests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ferpa_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ferpa_calendar_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ferpa_calendar_events" ON ferpa_calendar_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ferpa_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ferpa_documents" ON ferpa_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ferpa_training ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ferpa_training" ON ferpa_training FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS files ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_files" ON files FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS financial_assurances ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_financial_assurances" ON financial_assurances FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS follow_up_reminders ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_follow_up_reminders" ON follow_up_reminders FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS forum_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_forum_subscriptions" ON forum_subscriptions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS forum_thread_views ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_forum_thread_views" ON forum_thread_views FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS foundation_services ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_foundation_services" ON foundation_services FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS funding_change_audit ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_funding_change_audit" ON funding_change_audit FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS funding_options ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_funding_options" ON funding_options FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS funding_programs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_funding_programs" ON funding_programs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS funding_records ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_funding_records" ON funding_records FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS funding_tracking ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_funding_tracking" ON funding_tracking FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS gamification_points ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_gamification_points" ON gamification_points FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS gdpr_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_gdpr_requests" ON gdpr_requests FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS generated_assets ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_generated_assets" ON generated_assets FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grade_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grade_items" ON grade_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_eligibility_results ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_eligibility_results" ON grant_eligibility_results FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_entities ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_entities" ON grant_entities FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_federal_forms ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_federal_forms" ON grant_federal_forms FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_matches ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_matches" ON grant_matches FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_notification_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_notification_log" ON grant_notification_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_notifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_notifications" ON grant_notifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_packages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_packages" ON grant_packages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grant_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grant_submissions" ON grant_submissions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS grants ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_grants" ON grants FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS handbook_sections ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_handbook_sections" ON handbook_sections FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS help_search_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_help_search_log" ON help_search_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS hour_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_hour_logs" ON hour_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS hours_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_hours_log" ON hours_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS hours_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_hours_logs" ON hours_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS hsi_course_products ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_hsi_course_products" ON hsi_course_products FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS id_verifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_id_verifications" ON id_verifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS identity_verifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_identity_verifications" ON identity_verifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS impact_metrics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_impact_metrics" ON impact_metrics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS impact_statistics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_impact_statistics" ON impact_statistics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS incentives ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_incentives" ON incentives FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS industries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_industries" ON industries FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS intake_records ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_intake_records" ON intake_records FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS integrations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_integrations" ON integrations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS interviews ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_interviews" ON interviews FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS issued_certificates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_issued_certificates" ON issued_certificates FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS job_listings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_job_listings" ON job_listings FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_jobs" ON jobs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS jri_participants ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_jri_participants" ON jri_participants FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS leaderboard ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_leaderboard" ON leaderboard FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS learner_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_learner_documents" ON learner_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS learner_goals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_learner_goals" ON learner_goals FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS learner_onboarding ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_learner_onboarding" ON learner_onboarding FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS learning_resources ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_learning_resources" ON learning_resources FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS legal_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_legal_documents" ON legal_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lesson_bookmarks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lesson_bookmarks" ON lesson_bookmarks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lesson_comments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lesson_comments" ON lesson_comments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lesson_enhancements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lesson_enhancements" ON lesson_enhancements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lesson_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lesson_notes" ON lesson_notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lesson_questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lesson_questions" ON lesson_questions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS license_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS license_keys ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_license_keys" ON license_keys FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS license_leads ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_license_leads" ON license_leads FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS license_tiers ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_license_tiers" ON license_tiers FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS live_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_live_sessions" ON live_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS login_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_login_events" ON login_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS lti_platforms ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_lti_platforms" ON lti_platforms FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS marketplace_courses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_marketplace_courses" ON marketplace_courses FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS marketplace_sellers ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_marketplace_sellers" ON marketplace_sellers FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS meetings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_meetings" ON meetings FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS mentor_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_mentor_sessions" ON mentor_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS mentorships ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_mentorships" ON mentorships FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS message_notifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_message_notifications" ON message_notifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_access ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_access" ON milady_access FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_email_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_email_logs" ON milady_email_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_license_codes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_license_codes" ON milady_license_codes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_orientation_status ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_orientation_status" ON milady_orientation_status FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_provisioning_queue ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_provisioning_queue" ON milady_provisioning_queue FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS milady_rise_enrollments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_milady_rise_enrollments" ON milady_rise_enrollments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS moderation_queue ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_moderation_queue" ON moderation_queue FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS module_progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_module_progress" ON module_progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS mous ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_mous" ON mous FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS navigation_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_navigation_categories" ON navigation_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS navigation_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_navigation_items" ON navigation_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS news_articles ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_news_articles" ON news_articles FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS news_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_news_categories" ON news_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS nonprofit_services ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_nonprofit_services" ON nonprofit_services FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_notes" ON notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ojt_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ojt_notes" ON ojt_notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ojt_placements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ojt_placements" ON ojt_placements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS onboarding_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_onboarding_events" ON onboarding_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS onboarding_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_onboarding_submissions" ON onboarding_submissions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS organization_members ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_organization_members" ON organization_members FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS orientation_completions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_orientation_completions" ON orientation_completions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_acknowledgment_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_acknowledgment_items" ON partner_acknowledgment_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_acknowledgments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_acknowledgments" ON partner_acknowledgments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_attendance ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_attendance" ON partner_attendance FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_course_payments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_course_payments" ON partner_course_payments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_lms_sync_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_lms_sync_logs" ON partner_lms_sync_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_profiles ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_profiles" ON partner_profiles FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS partner_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_partner_sessions" ON partner_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS pathways ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_pathways" ON pathways FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS payment_options ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_payment_options" ON payment_options FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS payment_plan_selections ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_payment_plan_selections" ON payment_plan_selections FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS payment_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_payment_sessions" ON payment_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS payment_splits ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_payment_splits" ON payment_splits FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS payroll ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_payroll" ON payroll FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS performance_alerts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_performance_alerts" ON performance_alerts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS placements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_placements" ON placements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS platform_apps ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_platform_apps" ON platform_apps FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS platform_features ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_platform_features" ON platform_features FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS platform_products ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_platform_products" ON platform_products FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS portfolio_projects ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_portfolio_projects" ON portfolio_projects FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS pricing_plans ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_pricing_plans" ON pricing_plans FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS product_clones ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_product_clones" ON product_clones FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS product_page_views ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_product_page_views" ON product_page_views FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_banner_views ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_banner_views" ON program_banner_views FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_completion_certificates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_completion_certificates" ON program_completion_certificates FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_discussion_replies ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_discussion_replies" ON program_discussion_replies FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_discussions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_discussions" ON program_discussions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_funding_options ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_funding_options" ON program_funding_options FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_holder_banking ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_holder_banking" ON program_holder_banking FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_holder_programs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_holder_programs" ON program_holder_programs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS program_sponsorships ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_program_sponsorships" ON program_sponsorships FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_progress" ON progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS provisioning_jobs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_provisioning_jobs" ON provisioning_jobs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS push_notification_send_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_push_notification_send_log" ON push_notification_send_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS push_notifications_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_push_notifications_log" ON push_notifications_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS question_banks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_question_banks" ON question_banks FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_questions" ON questions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS quiz_submissions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_quiz_submissions" ON quiz_submissions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS recap_generation_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_recap_generation_log" ON recap_generation_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reels ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reels" ON reels FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS refund_advance_applications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_refund_advance_applications" ON refund_advance_applications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_completions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_completions" ON reporting_completions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_credentials ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_credentials" ON reporting_credentials FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_enrollments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_enrollments" ON reporting_enrollments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_funding ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_funding" ON reporting_funding FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_progress ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_progress" ON reporting_progress FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reporting_verdicts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reporting_verdicts" ON reporting_verdicts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS reports ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_reports" ON reports FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS resources ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_resources" ON resources FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS resumes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_resumes" ON resumes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS rise_participants ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_rise_participants" ON rise_participants FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS rise_programs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_rise_programs" ON rise_programs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sam_alerts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sam_alerts" ON sam_alerts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sam_documents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sam_documents" ON sam_documents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sam_entities ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sam_entities" ON sam_entities FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sam_opportunities ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sam_opportunities" ON sam_opportunities FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS scorm_attempts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_scorm_attempts" ON scorm_attempts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS scorm_cmi_data ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_scorm_cmi_data" ON scorm_cmi_data FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS scorm_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_scorm_sessions" ON scorm_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS scraper_detection_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_scraper_detection_events" ON scraper_detection_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS script_acknowledgments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_script_acknowledgments" ON script_acknowledgments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS script_deviations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_script_deviations" ON script_deviations FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS search_analytics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_search_analytics" ON search_analytics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS search_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_search_logs" ON search_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS security_alerts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_security_alerts" ON security_alerts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS security_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_security_logs" ON security_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS seller_applications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_seller_applications" ON seller_applications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS settings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_settings" ON settings FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS shop_checkin_codes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_shop_checkin_codes" ON shop_checkin_codes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS shop_profiles ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_shop_profiles" ON shop_profiles FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS shop_weekly_reports ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_shop_weekly_reports" ON shop_weekly_reports FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sites ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sites" ON sites FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS skill_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_skill_categories" ON skill_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS skills_checklist ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_skills_checklist" ON skills_checklist FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS slow_resources ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_slow_resources" ON slow_resources FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS snap_outreach_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_snap_outreach_log" ON snap_outreach_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS soc_controls ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_soc_controls" ON soc_controls FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS social_media_campaigns ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_social_media_campaigns" ON social_media_campaigns FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS ssn_verifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_ssn_verifications" ON ssn_verifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS staff ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_staff" ON staff FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS state_rules ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_state_rules" ON state_rules FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS statistics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_statistics" ON statistics FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS store_entitlements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_store_entitlements" ON store_entitlements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS store_products ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_store_products" ON store_products FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS store_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_store_subscriptions" ON store_subscriptions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_activity_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_activity_log" ON student_activity_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_ai_assignments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_ai_assignments" ON student_ai_assignments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_ai_instructors ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_ai_instructors" ON student_ai_instructors FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_funding_assignments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_funding_assignments" ON student_funding_assignments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_payments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_payments" ON student_payments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_requirements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_requirements" ON student_requirements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_risk_status ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_risk_status" ON student_risk_status FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS student_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_student_subscriptions" ON student_subscriptions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS studio_deployments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_studio_deployments" ON studio_deployments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS studio_pr_tracking ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_studio_pr_tracking" ON studio_pr_tracking FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS studio_workflow_tracking ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_studio_workflow_tracking" ON studio_workflow_tracking FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS sub_office_agreements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_sub_office_agreements" ON sub_office_agreements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS support_articles ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_support_articles" ON support_articles FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS support_groups ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_support_groups" ON support_groups FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS support_messages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_support_messages" ON support_messages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS support_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_support_sessions" ON support_sessions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS survey_responses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_survey_responses" ON survey_responses FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS surveys ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_surveys" ON surveys FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS system_configuration ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_system_configuration" ON system_configuration FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS system_errors ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_system_errors" ON system_errors FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_filing_applications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_filing_applications" ON tax_filing_applications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_information ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_information" ON tax_information FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_interview_questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_interview_questions" ON tax_interview_questions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_return_drafts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_return_drafts" ON tax_return_drafts FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_services ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_services" ON tax_services FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tax_tools ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tax_tools" ON tax_tools FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tenant_billing ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tenant_billing" ON tenant_billing FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS terminal_command_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_terminal_command_log" ON terminal_command_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS training_access_keys ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_training_access_keys" ON training_access_keys FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS training_modules ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_training_modules" ON training_modules FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS training_purchases ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_training_purchases" ON training_purchases FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS training_videos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_training_videos" ON training_videos FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS transcript_search_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_transcript_search_log" ON transcript_search_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tts_usage_log ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tts_usage_log" ON tts_usage_log FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tuition_options ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tuition_options" ON tuition_options FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tuition_payments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tuition_payments" ON tuition_payments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tuition_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tuition_subscriptions" ON tuition_subscriptions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS tutorials ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_tutorials" ON tutorials FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS updates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_updates" ON updates FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS uploads ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_uploads" ON uploads FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_access ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_access" ON user_access FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_activity_logs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_activity_logs" ON user_activity_logs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_app_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_app_subscriptions" ON user_app_subscriptions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_certifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_certifications" ON user_certifications FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_compliance_status ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_compliance_status" ON user_compliance_status FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_consents ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_consents" ON user_consents FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_credentials ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_credentials" ON user_credentials FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_entitlements ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_entitlements" ON user_entitlements FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_feedback ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_feedback" ON user_feedback FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_licenses ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_licenses" ON user_licenses FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_preferences ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_preferences" ON user_preferences FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_saved_grants ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_saved_grants" ON user_saved_grants FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS user_websites ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_user_websites" ON user_websites FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS verification_actions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_verification_actions" ON verification_actions FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS video_notes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_video_notes" ON video_notes FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS video_playback_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_video_playback_events" ON video_playback_events FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS video_views ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_video_views" ON video_views FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS website_pages ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_website_pages" ON website_pages FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS welcome_packet_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_welcome_packet_items" ON welcome_packet_items FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS workflow_enrollments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_workflow_enrollments" ON workflow_enrollments FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS workforce_referrals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_workforce_referrals" ON workforce_referrals FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS workshop_categories ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_workshop_categories" ON workshop_categories FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE IF EXISTS workshops ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "auth_read_workshops" ON workshops FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;