import type { FeatureDefinition } from './types';

export const FEATURE_REGISTRY: FeatureDefinition[] = [
  // ── Global ──────────────────────────────────────────────────────────────
  {
    id: 'global-avatar',
    name: 'Global Avatar Guide',
    description: 'Floating video avatar that adapts to the current page context.',
    component: '@/components/GlobalAvatar',
    surface: 'global',
    category: 'avatar',
    status: 'enabled',
  },
  {
    id: 'avatar-chat-bar',
    name: 'Avatar Chat Bar',
    description: 'Persistent chat bar with avatar video and AI messaging.',
    component: '@/components/AvatarChatBar',
    surface: 'global',
    category: 'avatar',
    status: 'enabled',
  },
  {
    id: 'facebook-pixel',
    name: 'Facebook Pixel',
    description: 'Meta Pixel for conversion tracking.',
    component: '@/components/FacebookPixel',
    surface: 'global',
    category: 'analytics',
    status: 'enabled',
    requiresEnvVar: 'NEXT_PUBLIC_FACEBOOK_PIXEL_ID',
  },
  {
    id: 'ai-assistant-bubble',
    name: 'AI Assistant Bubble',
    description: 'Floating AI chat bubble available site-wide.',
    component: '@/components/AIAssistantBubble',
    surface: 'global',
    category: 'ai',
    status: 'enabled',
  },

  // ── Marketing ────────────────────────────────────────────────────────────
  {
    id: 'rotating-hero-banner',
    name: 'Rotating Hero Banner',
    description: 'Auto-advancing image carousel for marketing pages.',
    component: '@/components/RotatingHeroBanner',
    surface: 'marketing',
    category: 'marketing',
    status: 'enabled',
  },
  {
    id: 'newsletter-signup',
    name: 'Newsletter Signup',
    description: 'Email capture form with honeypot spam protection.',
    component: '@/components/NewsletterSignup',
    surface: 'marketing',
    category: 'engagement',
    status: 'enabled',
  },
  {
    id: 'social-media-highlight',
    name: 'Social Media Highlight',
    description: 'Social feed embed / highlight strip.',
    component: '@/components/SocialMediaHighlight',
    surface: 'marketing',
    category: 'marketing',
    status: 'enabled',
  },

  // ── LMS ──────────────────────────────────────────────────────────────────
  {
    id: 'ar-training-modules',
    name: 'AR Training Modules',
    description: 'Augmented-reality 3D model training for technical courses.',
    component: '@/components/ARTrainingModules',
    surface: 'lms-lesson',
    category: 'video',
    status: 'beta',
  },
  {
    id: 'tiktok-video-player',
    name: 'TikTok-Style Video Player',
    description: 'Vertical short-form video player for lesson content.',
    component: '@/components/video/TikTokStyleVideoPlayer',
    surface: 'lms-lesson',
    category: 'video',
    status: 'beta',
  },
  {
    id: 'universal-course-player',
    name: 'Universal Course Player',
    description: 'Iframe-based player for partner LMS / SCORM content.',
    component: '@/components/UniversalCoursePlayer',
    surface: 'lms',
    category: 'video',
    status: 'enabled',
  },

  // ── Admin ────────────────────────────────────────────────────────────────
  {
    id: 'blockchain-credential-verification',
    name: 'Blockchain Credential Verification',
    description: 'On-chain credential issuance and verification UI.',
    component: '@/components/BlockchainCredentialVerification',
    surface: 'admin-compliance',
    category: 'compliance',
    status: 'beta',
  },
  {
    id: 'job-placement-tracking',
    name: 'Job Placement Tracking',
    description: 'Dashboard for tracking graduate job placements and salaries.',
    component: '@/components/JobPlacementTracking',
    surface: 'admin-analytics',
    category: 'tracking',
    status: 'enabled',
  },
  {
    id: 'employer-talent-pipeline',
    name: 'Employer Talent Pipeline',
    description: 'Kanban-style pipeline for employer candidate tracking.',
    component: '@/components/EmployerTalentPipeline',
    surface: 'admin-analytics',
    category: 'tracking',
    status: 'enabled',
  },
  {
    id: 'excel-chart-generator',
    name: 'Excel Chart Generator',
    description: 'Generate and export charts to Excel for reporting.',
    component: '@/components/admin/ExcelChartGenerator',
    surface: 'admin-analytics',
    category: 'analytics',
    status: 'enabled',
  },
];
